### ISSUE TITLE
bash -all.sh 无法执行.设置cookie就不用管了 自动定时脚本就会跑？

### ISSUE THREAD

**Issue by kate09280774** [SuperManito/JD-FreeFuck#1]

**Comment by SuperManito** [comment]
1.请说出你使用的操作系统并验证是否已经部署成功，如果部署失败遇到报错请提供日志，命令是`bash run-all.sh`，这是个脚本文件   
2.我不使用自动定时脚本，这个项目中也没有关于自动定时的脚本，将来我可能会写，请你持续关注此项目，需要帮助请访问原项目
