### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by PalmerCharles** [SuperManito/JD-FreeFuck#10]
WSL Ubuntu18.04执行部署命令没有反应，VMware15内装同版本Ubuntu和Cent7.9Everything也是没反应，腾讯云cent7.6正常
![Snipaste_2021-01-26_22-51-57](https://user-images.githubusercontent.com/62934244/105860966-2542ea00-6029-11eb-946c-1c1e6cd71021.png)
![Snipaste_2021-01-26_22-52-40](https://user-images.githubusercontent.com/62934244/105861016-35f36000-6029-11eb-8146-f85e26c60aa9.png)
请问是因为环境部署出问题还是什么其他原因

**Comment by SuperManito** [comment]
同样的命令 你执行出两个结果 你确定你的命令复制对了？这不是我的问题，如果你不懂linux，那就请把命令复制完整

**Comment by SuperManito** [comment]
> WSL Ubuntu18.04执行部署命令没有反应，VMware15内装同版本Ubuntu和Cent7.9Everything也是没反应，腾讯云cent7.6正常
> ![Snipaste_2021-01-26_22-51-57](https://user-images.githubusercontent.com/62934244/105860966-2542ea00-6029-11eb-946c-1c1e6cd71021.png)
> ![Snipaste_2021-01-26_22-52-40](https://user-images.githubusercontent.com/62934244/105861016-35f36000-6029-11eb-8146-f85e26c60aa9.png)
> 请问是因为环境部署出问题还是什么其他原因

还有你的图是CentOS7.9 不是你认为的7.6
