### ISSUE TITLE
clouflare workers 加速 GitHub 国内下载 速度 

### ISSUE THREAD

**Issue by hello1983** [SuperManito/JD-FreeFuck#100]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

-  [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：加入cloud flare的GitHub 加速

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

bash <(curl -sSL https://github.app-io.workers.dev/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)

**Comment by SuperManito** [comment]
你添加个hosts就能解析了。。。

**Comment by SuperManito** [comment]
或者用这个命令：

    bash <(curl -sL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)

**Comment by hello1983** [comment]
谢谢
