### ISSUE TITLE
互助码

### ISSUE THREAD

**Issue by qingdeng8866** [SuperManito/JD-FreeFuck#101]
大佬  获取互助码 那个format_share_jd_code.js   作者在两小时前更新后 在docker环境下执行 会报错了-.-  虽然你不是作者 但是跟你说一下  
![QQ截图20210228195532](https://user-images.githubusercontent.com/73421819/109417517-f12f6000-79fe-11eb-88ac-2e3aaef2f2f7.png)

**Comment by SuperManito** [comment]
收到，已向作者反馈，您可以在 Gitee分项 提交 `Issues` 进行交流
