### ISSUE TITLE
用#注释屏蔽cookie后，下方cookie无法读取。

### ISSUE THREAD

**Issue by hitaoge** [SuperManito/JD-FreeFuck#104]
``

## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》与《项目声明》并已接受

- [x] 是
- [ ] 否

Q：是否阅读了《前言》

- [X ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [X ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [X ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [X ] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [ X] Docker 版本

## 3. 安装平台

- [ ] PC
- [X ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [X ] amd64 / x86-64 / x86-32
- [ ] arm64 / aarch64 / armv8 / armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [X ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：centos7

## 7. 问题类型

- [ ] 部署问题
- [x ] 使用问题

### (1) 具体问题
A：cookie中添加了19个cookie，用#号注释掉该行cookie后，在执行任务中，其下方所有的cookie都无法读取到。
Cookie1="test1"
Cookie2="tes2"
Cookie3="test3"
#Cookie4="test4"
Cookie5="test5"
Cookie6="test6"
查看定时任务或者手动执行任务都显示，共有3个京东账号Cookie

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
本来也不能这么用啊，要不然为什么开发“临时屏蔽某个Cookie"
