### ISSUE TITLE
互助码脚本执行报错

### ISSUE THREAD

**Issue by Shawt310** [SuperManito/JD-FreeFuck#105]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》与《项目声明》并已接受

- [x] 是
- [ ] 否

Q：是否阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 / x86-64 / x86-32
- [ ] arm64 / aarch64 / armv8 / armv7
- [ ] Other

## 5. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：Ubuntu 20.04

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：互助码脚本get下来以后，按照教程执行，反馈错误

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
root@ubuntu:/home/xt310/jd# bash jd.sh format_share_jd_code.js now

🔔获取互助码并格式化/docker自动更新容器下所有账号互助码, 开始!
您的cookie选择的是用&隔开

====================共有5个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/1/2021, 12:45:39 PM=====================

(node:14857) UnhandledPromiseRejectionWarning: Error: Cannot find module '../USER_AGENTS'
Require stack:
- /opt/jd/scripts/format_share_jd_code.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /opt/jd/scripts/format_share_jd_code.js:1354:15
    at new Promise (<anonymous>)
    at TotalBean (/opt/jd/scripts/format_share_jd_code.js:1340:10)
    at /opt/jd/scripts/format_share_jd_code.js:120:13
    at Object.<anonymous> (/opt/jd/scripts/format_share_jd_code.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14857) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14857) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SuperManito** [comment]
#103
