### ISSUE TITLE
log中有个git_pull.log里显示js脚本更新失败

### ISSUE THREAD

**Issue by shenhui0929** [SuperManito/JD-FreeFuck#106]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》与《项目声明》并已接受

- [x] 是
- [ ] 否

Q：是否阅读了《前言》

- [ X] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ X] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ X] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [X ] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [ X] Docker 版本

## 3. 安装平台

- [ ] PC
- [ X] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [X ] amd64 / x86-64 / x86-32
- [ ] arm64 / aarch64 / armv8 / armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ X] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [ X] 使用问题

### (1) 具体问题
A：3.1早上删除了老的镜像，使用了新镜像部署docker，脚本和定时都没问题，但发现/opt/jd/log下有个git_pull.log里有报错，js脚本更新失败，
![微信截图_20210301131626](https://user-images.githubusercontent.com/32407042/109454936-6434e700-7a90-11eb-8d13-e7cb7fb578a4.png)
![微信截图_20210301131603](https://user-images.githubusercontent.com/32407042/109454937-65661400-7a90-11eb-925e-c8fca65e44b6.png)

报错如下

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
--------------------------------------------------------------

系统时间：2021-03-01 11:55:00

JS脚本目录：/jd/scripts

--------------------------------------------------------------

Fetching origin
Handshake: [31mRepository more than 5 connections.[0m
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at 3c3b4a1 update

js脚本更新失败，请检查原因或再次运行git_pull.sh...

/jd/config/config.sh: line 1: ﻿##: command not found
开始下载 i-chenzhe 的脚本
https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_entertainment.js
jd_entertainment.js
更新 jd_entertainment.js 完成...

[37mdiy脚本更新完成... [0m

--------------------------------------------------------------

系统时间：2021-03-01 12:55:00

JS脚本目录：/jd/scripts

--------------------------------------------------------------

Fetching origin
Handshake: [31mRepository more than 5 connections.[0m
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at 3c3b4a1 update

js脚本更新失败，请检查原因或再次运行git_pull.sh...

/jd/config/config.sh: line 1: ﻿##: command not found
开始下载 i-chenzhe 的脚本
https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_entertainment.js
jd_entertainment.js
更新 jd_entertainment.js 完成...

[37mdiy脚本更新完成... [0m

**Comment by SuperManito** [comment]
> Handshake: �[31mRepository more than 5 connections.�[0m
> fatal: Could not read from remote repository.

Gitee 的每秒同时请求链接不能超过5个，此报错为正常现象，不影响使用
