### ISSUE TITLE
nodejs实际安装成功，但是部署失败

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#108]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.3

## 7. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：Nodejs未安装成功，部署不了，但实际上npm -v以及node -v是有显示版本的

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
![image](https://user-images.githubusercontent.com/48577796/109586317-f8aa5280-7b3f-11eb-912b-390bf9270af1.png)

**Comment by SuperManito** [comment]
有没有安装成功查看一下node版本就置顶了，`node -v`

**Comment by bytepoem** [comment]
> 有没有安装成功查看一下node版本就置顶了，`node -v`

v12.16.1 有的 但是看上去与脚本下载的版本好像不一样

**Comment by SuperManito** [comment]
> > 有没有安装成功查看一下node版本就置顶了，`node -v`
> 
> v12.16.1 有的 但是看上去与脚本下载的版本好像不一样

对的，你的截图都有版本号，你系统通过yum源安装的node12没有经过nodesource安装14

**Comment by SuperManito** [comment]
我建议你根据卸载教程重装，

**Comment by bytepoem** [comment]
ok了 nodejs卸载干净就可以了
