### ISSUE TITLE
如何停止项目

### ISSUE THREAD

**Issue by iOSGL** [SuperManito/JD-FreeFuck#109]
在CentOS上部署的， 终端窗口关闭之后，项目还在运行，Server酱还在发推送

**Comment by saminlu** [comment]
crontab 里面把定时任务删掉

**Comment by SuperManito** [comment]
> 在CentOS上部署的， 终端窗口关闭之后，项目还在运行，Server酱还在发推送

项目默认自带并已配置好定时功能，如果你不想使用定时功能，删除 `config` 目录下的 `crontab.list` 文件，然后执行 `crontab -r` 命令即可
