### ISSUE TITLE
docker版本diy脚本更新失败

### ISSUE THREAD

**Issue by zhaojie199512** [SuperManito/JD-FreeFuck#110]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [x] Docker 版本

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题 
A：重新部署3.1号docker镜像后，开启了diy脚本同步，然后执行 manual-update.sh 脚本后显示diy脚本同步成功，但是在scripts文件夹下并没有diy脚本中的jd_entertainment.js,定时任务中也没有添加，于是手动后执行diy,sh脚本，报错。提示下载脚本出错，然而手动使用wget 命令可以成功下载脚本，不知道问题出在哪里。
P.S.我觉得大佬的diy脚本里可以加上几个脚本：
scripts_base_url_1=https://raw.githubusercontent.com/i-chenzhe/qx/main/
scripts_base_url_2=https://raw.githubusercontent.com/799953468/Quantumult-X/master/Scripts/JD/
my_scripts_list_1="jd_mlyjy.js jd_entertainment.js jd_jump-jump.js"
my_scripts_list_2="jd_paopao.js"
然后就是那个内置的hosts ip地址是美国的，延迟高，速度也比较慢，我找了一个香港的，试了下速度还比较快，大佬可以试下
151.101.76.133 raw.githubusercontent.com

_**额，不好意思，刚才又反复试了下，应该还是网络问题，多次执行后下载成功也添加到计划任务了，应该没问题了**_
### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
bash diy.sh 
开始下载 i-chenzhe 的脚本
https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_entertainment.js
jd_entertainment.js
scripts/jd_entertainment.js.new: No such file or directory
更新 jd_entertainment.js 失败，使用上一次正常的版本...

diy脚本更新完成... 

root@jd:/jd/config $ wget https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_entertainment.js
--2021-03-02 14:19:34--  https://raw.githubusercontent.com/i-chenzhe/qx/main/jd_entertainment.js
Resolving raw.githubusercontent.com... 151.101.88.133, 151.101.228.133
Connecting to raw.githubusercontent.com|151.101.88.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57236 (56K) [text/plain]
Saving to: 'jd_entertainment.js'

jd_entertainment.js                100%[==============================================================>]  55.89K  69.7KB/s    in 0.8s    

2021-03-02 14:19:36 (69.7 KB/s) - 'jd_entertainment.js' saved [57236/57236]

**Comment by SuperManito** [comment]
泡泡大战这个活动是哪儿来的，我看编辑日期还停留在去年11月

**Comment by zhaojie199512** [comment]
> 泡泡大战这个活动是哪儿来的，我看编辑日期还停留在去年11月

是挺老的，不过可以用。。。。。
