### ISSUE TITLE
更新之后的config.sh脚本的版本号和文件内容还不是最新的

### ISSUE THREAD

**Issue by 1304364030** [SuperManito/JD-FreeFuck#112]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [x] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：为什么更新之后的config.sh脚本的版本号和文件内容还不是最新的
![image](https://user-images.githubusercontent.com/58807785/109616045-a2550800-7b6f-11eb-8c4c-c0bbec6a52de.png)
![image](https://user-images.githubusercontent.com/58807785/109616088-b13bba80-7b6f-11eb-8571-b60a2191c9f0.png)

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
你Docker没删挂载目录吧，自行删了，然后重新复制sample里的文件

**Comment by 1304364030** [comment]
![image](https://user-images.githubusercontent.com/58807785/109617727-b6016e00-7b71-11eb-9cd6-60b5f88be372.png)
我在windows上面装的docker，想手动删除目前也找不见/opt/jd这个挂在文件夹

**Comment by 1304364030** [comment]
> 你Docker没删挂载目录吧，自行删了，然后重新复制sample里的文件


![](https://user-images.githubusercontent.com/58807785/109617727-b6016e00-7b71-11eb-9cd6-60b5f88be372.png)
我在windows上面装的docker，想手动删除目前也找不见/opt/jd这个挂在文件夹

**Comment by SuperManito** [comment]
> > 你Docker没删挂载目录吧，自行删了，然后重新复制sample里的文件
> 
> ![](https://user-images.githubusercontent.com/58807785/109617727-b6016e00-7b71-11eb-9cd6-60b5f88be372.png)
> 我在windows上面装的docker，想手动删除目前也找不见/opt/jd这个挂在文件夹

6，那你自己百度吧。。。而且不同操作系统的命令不能混着用，而且我也告诉你了，在容器里操作把你现在的配置文件删了重新从sample那里复制一个过了就行了
