### ISSUE TITLE
群晖里注册表搜索出来的镜像文件是作者你的吗？

### ISSUE THREAD

**Issue by ICEOOX** [SuperManito/JD-FreeFuck#113]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [x] Docker 版本

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] amd64 | x86-64 | x86-32
- [x] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
这个是群晖带的那个docker，注册表搜索出来的，我想问下，这个是不是作者的？我怕用错了再不是作者上传的，到时候用了别人上传的可能泄露隐私，我只相信作者自己上传的。
镜像地址：https://registry.hub.docker.com/r/supermanito/jd/
镜像图示：
[https://i.loli.net/2021/03/02/1OJnbkpAw69PmuK.png](https://i.loli.net/2021/03/02/1OJnbkpAw69PmuK.png)
[https://i.loli.net/2021/03/02/IvQrzAVisFGHmcB.png](https://i.loli.net/2021/03/02/IvQrzAVisFGHmcB.png)

**Comment by SuperManito** [comment]
对啊，是我的，但你这个可能是旧版本的，我现版本发布的镜像走的阿里云镜像仓库，镜像名前面还要加个仓库地址，虽然也同名，但我不知道在你们NAS里边叫什么
