### ISSUE TITLE
多账户时，挂机脚本只会执行第一个账户的挂机

### ISSUE THREAD

**Issue by atgfss** [SuperManito/JD-FreeFuck#114]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：centos 7.2

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：多账户时，挂机脚本只会执行第一个账户的挂机
jd.sh hangup 这个命令只会读取第一个账户挂机
jd.sh jd_crazy_joy_coin now 这个命令是会所有账户挂机
看上去像是在执行不同命令时读的cookies账户环境变量不对

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：日志无报错
挂机日志（可以看到只读到了一个账号）：
🔔crazyJoy挂机, 开始!

====================共有1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/3/2 下午5:24:50=====================

挂机开始，自动8s收一次金币
============开始第1次挂机=============

开始【京东账号1】jd152618pxx

当前JOY分布情况

30 31 32 33
34 34 34 34
34 34 34 34

当前金币:1818741751112128

此次在线收益：获得 383862702085 金币
当前信息：377 京豆，1818741751112128 金币

============开始第2次挂机=============

开始【京东账号1】jd152618pxx

jd.sh jd_crazy_joy_coin now 这个命令的日志，核心点是那个账号数

🔔crazyJoy挂机, 开始!
您的cookie选择的是用&隔开

====================共有4个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/3/2 下午5:33:14=====================

挂机开始，自动8s收一次金币
============开始第1次挂机=============

开始【京东账号1】jd152618pxx

当前JOY分布情况

30 31 32 33
34 34 34 34
34 34 34 34

当前金币:1842541238641398

此次在线收益：获得 383862702085 金币
当前信息：377 京豆，1842541238641398 金币

开始【京东账号2】jd_159517jgu

当前JOY分布情况

1 3 10 8
0 12 13 9
12 14 5 4

金币补给领取成功，获得62316000金币
分红狗生效中，预计获得 12 京豆奖励
当前金币:230787983

此次在线收益：获得 86550 金币
购买10级joy成功，剩余金币【219011983】
分红狗生效中，预计获得 12 京豆奖励
此次在线收益：获得 0 金币
开始合并两只10级joy

合并成功，获得11级Joy
合并后的JOY分布情况

1 3 0 8
11 12 13 9
12 14 5 4

开始合并两只12级joy

合并成功，获得13级Joy
合并后的JOY分布情况

1 3 0 8
11 0 13 9
13 14 5 4

当前信息：127 京豆，获取当前金币数量失败 金币

开始【京东账号3】jd_158505yslf

**Comment by SuperManito** [comment]
不清楚 你要是像挂机所有账号的话可以后台执行

    bash jd.sh jd_crazy_joy_coin now &
