### ISSUE TITLE
脚本更新是不是需要手动操作？一键更新脚本，能否加入自动更新脚本

### ISSUE THREAD

**Issue by ICEOOX** [SuperManito/JD-FreeFuck#116]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [x] Docker 版本

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] amd64 | x86-64 | x86-32
- [x] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：一键更新脚本是不是必须要手动运行才会更新？我觉得可以加入自动更新脚本，新活动自动下载自动更新

**Comment by SuperManito** [comment]
后期会加入
