### ISSUE TITLE
脚本apt更新完之后，不会进行下一步

### ISSUE THREAD

**Issue by nxcjs** [SuperManito/JD-FreeFuck#117]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：ubuntu service 20.1

## 7. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：全新安装的系统就设置了个账号密码，直接运行脚本，卡apt update ，运行了两次，手动apt upgrade，再次运行还是一样，检查完环境就不运行了，也没有报错。换源也是一样。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

root@ub:~# bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/ReplaceMirror.sh)

+---------------------------------------------------+
|                                                   |
|   =============================================   |
|                                                   |
|         欢迎使用 Linux 一键更换国内源脚本         |
|                                                   |
|   =============================================   |
|                                                   |
+---------------------------------------------------+

#####################################################

            提供以下国内更新源可供选择：

#####################################################
 *  1)    中科大
 *  2)    华为云
 *  3)    阿里云
 *  4)    网易
 *  4)    搜狐
 *  6)    清华大学
 *  7)    浙江大学
 *  8)    南京大学
 *  9)    重庆大学
 *  10)   兰州大学
 *  11)   上海交通大学
 *  12)   北京交通大学
 *  13)   北京理工大学
 *  14)   南京邮电大学
 *  15)   华中科技大学
 *  16)   哈尔滨工业大学
 *  17)   北京外国语大学

#####################################################

      当前操作系统  Ubuntu 20.10
      当前系统时间  2021-03-03 05:05

#####################################################

请输入您想使用的国内更新源 [ 1~17 ]：3
检测到已备份的 source.list源 文件，跳过备份操作......
Hit:1 https://mirrors.aliyun.com/ubuntu groovy InRelease
Hit:2 https://mirrors.aliyun.com/ubuntu groovy-security InRelease
Hit:3 https://mirrors.aliyun.com/ubuntu groovy-updates InRelease
Hit:4 https://mirrors.aliyun.com/ubuntu groovy-proposed InRelease
Hit:5 https://mirrors.aliyun.com/ubuntu groovy-backports InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@ub:~#

**换网易云源后**

root@ub:~# bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/ReplaceMirror.sh)

+---------------------------------------------------+
|                                                   |
|   =============================================   |
|                                                   |
|         欢迎使用 Linux 一键更换国内源脚本         |
|                                                   |
|   =============================================   |
|                                                   |
+---------------------------------------------------+

#####################################################

            提供以下国内更新源可供选择：

#####################################################
 *  1)    中科大
 *  2)    华为云
 *  3)    阿里云
 *  4)    网易
 *  4)    搜狐
 *  6)    清华大学
 *  7)    浙江大学
 *  8)    南京大学
 *  9)    重庆大学
 *  10)   兰州大学
 *  11)   上海交通大学
 *  12)   北京交通大学
 *  13)   北京理工大学
 *  14)   南京邮电大学
 *  15)   华中科技大学
 *  16)   哈尔滨工业大学
 *  17)   北京外国语大学

#####################################################

      当前操作系统  Ubuntu 20.10
      当前系统时间  2021-03-03 05:16

#####################################################

请输入您想使用的国内更新源 [ 1~17 ]：4
检测到已备份的 source.list源 文件，跳过备份操作......
Get:1 https://mirrors.163.com/ubuntu groovy InRelease [267 kB]
Get:2 https://mirrors.163.com/ubuntu groovy-security InRelease [110 kB]
Get:3 https://mirrors.163.com/ubuntu groovy-updates InRelease [115 kB]
Get:4 https://mirrors.163.com/ubuntu groovy-proposed InRelease [269 kB]
Get:5 https://mirrors.163.com/ubuntu groovy-backports InRelease [101 kB]
Get:6 https://mirrors.163.com/ubuntu groovy/multiverse Sources [279 kB]
Get:7 https://mirrors.163.com/ubuntu groovy/restricted Sources [13.8 kB]
Get:8 https://mirrors.163.com/ubuntu groovy/main Sources [1,300 kB]
Get:9 https://mirrors.163.com/ubuntu groovy/universe Sources [16.3 MB]
Get:10 https://mirrors.163.com/ubuntu groovy/main amd64 Packages [1,378 kB]
Get:11 https://mirrors.163.com/ubuntu groovy/main Translation-en [507 kB]
Get:12 https://mirrors.163.com/ubuntu groovy/main amd64 c-n-f Metadata [29.2 kB]
Get:13 https://mirrors.163.com/ubuntu groovy/restricted amd64 Packages [57.7 kB]
Get:14 https://mirrors.163.com/ubuntu groovy/restricted Translation-en [9,404 B]
Get:15 https://mirrors.163.com/ubuntu groovy/restricted amd64 c-n-f Metadata [456 B]
Get:16 https://mirrors.163.com/ubuntu groovy/universe amd64 Packages [12.6 MB]
Get:17 https://mirrors.163.com/ubuntu groovy/universe Translation-en [5,262 kB]
Get:18 https://mirrors.163.com/ubuntu groovy/universe amd64 c-n-f Metadata [270 kB]
Get:19 https://mirrors.163.com/ubuntu groovy/multiverse amd64 Packages [202 kB]
Get:20 https://mirrors.163.com/ubuntu groovy/multiverse Translation-en [106 kB]
Get:21 https://mirrors.163.com/ubuntu groovy/multiverse amd64 c-n-f Metadata [9,260 B]
Get:22 https://mirrors.163.com/ubuntu groovy-security/universe Sources [12.4 kB]
Get:23 https://mirrors.163.com/ubuntu groovy-security/restricted Sources [8,988 B]
Get:24 https://mirrors.163.com/ubuntu groovy-security/main Sources [63.6 kB]
Get:25 https://mirrors.163.com/ubuntu groovy-security/main amd64 Packages [221 kB]
Get:26 https://mirrors.163.com/ubuntu groovy-security/main Translation-en [55.2 kB]
Get:27 https://mirrors.163.com/ubuntu groovy-security/main amd64 c-n-f Metadata [3,388 B]
Get:28 https://mirrors.163.com/ubuntu groovy-security/restricted amd64 Packages [98.2 kB]
Get:29 https://mirrors.163.com/ubuntu groovy-security/restricted Translation-en [14.8 kB]
Get:30 https://mirrors.163.com/ubuntu groovy-security/restricted amd64 c-n-f Metadata [420 B]
Get:31 https://mirrors.163.com/ubuntu groovy-security/universe amd64 Packages [57.6 kB]
Get:32 https://mirrors.163.com/ubuntu groovy-security/universe Translation-en [25.7 kB]
Get:33 https://mirrors.163.com/ubuntu groovy-security/universe amd64 c-n-f Metadata [2,616 B]
Get:34 https://mirrors.163.com/ubuntu groovy-security/multiverse amd64 Packages [8,000 B]
Get:35 https://mirrors.163.com/ubuntu groovy-security/multiverse Translation-en [2,320 B]
Get:36 https://mirrors.163.com/ubuntu groovy-security/multiverse amd64 c-n-f Metadata [304 B]
Get:37 https://mirrors.163.com/ubuntu groovy-updates/main Sources [121 kB]
Get:38 https://mirrors.163.com/ubuntu groovy-updates/universe Sources [27.3 kB]
Get:39 https://mirrors.163.com/ubuntu groovy-updates/restricted Sources [11.7 kB]
Get:40 https://mirrors.163.com/ubuntu groovy-updates/multiverse Sources [4,456 B]
Get:41 https://mirrors.163.com/ubuntu groovy-updates/main amd64 Packages [364 kB]
Get:42 https://mirrors.163.com/ubuntu groovy-updates/main Translation-en [93.5 kB]
Get:43 https://mirrors.163.com/ubuntu groovy-updates/main amd64 c-n-f Metadata [6,416 B]
Get:44 https://mirrors.163.com/ubuntu groovy-updates/restricted amd64 Packages [120 kB]
Get:45 https://mirrors.163.com/ubuntu groovy-updates/restricted Translation-en [18.2 kB]
Get:46 https://mirrors.163.com/ubuntu groovy-updates/restricted amd64 c-n-f Metadata [460 B]
Get:47 https://mirrors.163.com/ubuntu groovy-updates/universe amd64 Packages [137 kB]
Get:48 https://mirrors.163.com/ubuntu groovy-updates/universe Translation-en [52.7 kB]
Get:49 https://mirrors.163.com/ubuntu groovy-updates/universe amd64 c-n-f Metadata [4,240 B]
Get:50 https://mirrors.163.com/ubuntu groovy-updates/multiverse amd64 Packages [13.9 kB]
Get:51 https://mirrors.163.com/ubuntu groovy-updates/multiverse Translation-en [4,012 B]
Get:52 https://mirrors.163.com/ubuntu groovy-updates/multiverse amd64 c-n-f Metadata [540 B]
Get:53 https://mirrors.163.com/ubuntu groovy-proposed/universe Sources [3,216 B]
Get:54 https://mirrors.163.com/ubuntu groovy-proposed/restricted Sources [8,992 B]
Get:55 https://mirrors.163.com/ubuntu groovy-proposed/main Sources [30.5 kB]
Get:56 https://mirrors.163.com/ubuntu groovy-proposed/main amd64 Packages [63.3 kB]
Get:57 https://mirrors.163.com/ubuntu groovy-proposed/main Translation-en [20.0 kB]
Get:58 https://mirrors.163.com/ubuntu groovy-proposed/main amd64 c-n-f Metadata [1,780 B]
Get:59 https://mirrors.163.com/ubuntu groovy-proposed/restricted amd64 Packages [56.5 kB]
Get:60 https://mirrors.163.com/ubuntu groovy-proposed/restricted Translation-en [8,540 B]
Get:61 https://mirrors.163.com/ubuntu groovy-proposed/restricted amd64 c-n-f Metadata [420 B]
Get:62 https://mirrors.163.com/ubuntu groovy-proposed/universe amd64 Packages [26.1 kB]
Get:63 https://mirrors.163.com/ubuntu groovy-proposed/universe Translation-en [14.6 kB]
Get:64 https://mirrors.163.com/ubuntu groovy-proposed/universe amd64 c-n-f Metadata [736 B]
Get:65 https://mirrors.163.com/ubuntu groovy-proposed/multiverse amd64 Packages [8,040 B]
Get:66 https://mirrors.163.com/ubuntu groovy-proposed/multiverse Translation-en [4,888 B]
Get:67 https://mirrors.163.com/ubuntu groovy-proposed/multiverse amd64 c-n-f Metadata [308 B]
Get:68 https://mirrors.163.com/ubuntu groovy-backports/universe Sources [2,004 B]
Get:69 https://mirrors.163.com/ubuntu groovy-backports/main amd64 c-n-f Metadata [112 B]
Get:70 https://mirrors.163.com/ubuntu groovy-backports/restricted amd64 c-n-f Metadata [116 B]
Get:71 https://mirrors.163.com/ubuntu groovy-backports/universe amd64 Packages [3,920 B]
Get:72 https://mirrors.163.com/ubuntu groovy-backports/universe Translation-en [1,324 B]
Get:73 https://mirrors.163.com/ubuntu groovy-backports/universe amd64 c-n-f Metadata [188 B]
Get:74 https://mirrors.163.com/ubuntu groovy-backports/multiverse amd64 c-n-f Metadata [116 B]
Fetched 41.0 MB in 21s (1,952 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@ub:~#

大佬需要ssh直接看么

**Comment by SuperManito** [comment]
哪儿卡了？你这不回到终端交互了么？我脚本没问题

**Comment by nxcjs** [comment]
> 哪儿卡了？你这不回到终端交互了么？我脚本没问题

选完源 apt更新之后就没有了下一步了QAQ

**Comment by SuperManito** [comment]
> > 哪儿卡了？你这不回到终端交互了么？我脚本没问题
> 
> 选完源 apt更新之后就没有了下一步了QAQ

你仔细看教程了吗？

**Comment by nxcjs** [comment]
> > > 哪儿卡了？你这不回到终端交互了么？我脚本没问题
> > 
> > 
> > 选完源 apt更新之后就没有了下一步了QAQ
> 
> 你仔细看教程了吗？

我的我的，啥时候更新的redeme，记的之前这个位置是安装脚本，现在换源和安装分开了
