### ISSUE TITLE
面板安装失败

### ISSUE THREAD

**Issue by baiye233** [SuperManito/JD-FreeFuck#12]
[PM2][ERROR] Script not found: /root/server.js

**Comment by baiye233** [comment]
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] Script not found: /root/server.js

**Comment by SuperManito** [comment]
你的node装上了么

**Comment by baiye233** [comment]
一键脚本里面不会安装node的吗

**Comment by SuperManito** [comment]
我不清楚 现在装上了 脚本也用不了了 项目都没了

**Comment by baiye233** [comment]
主要是想要那个扫码就能出cooks的功能

**Comment by tianqu36** [comment]
"Client network socket disconnected before secure TLS connection was established"
京豆变动通知 API请求失败，请检查网路重试
第1页: undefined
"Client network socket disconnected before secure TLS connection was established"
京豆变动通知 API请求失败，请检查网路重试
第1页: undefined
"Client network socket disconnected before secure TLS connection was established"
京豆变动通知 API请求失败，请检查网路重试

这是啥情况？求教

**Comment by SuperManito** [comment]
> "Client network socket disconnected before secure TLS connection was established"
> 京豆变动通知 API请求失败，请检查网路重试
> 第1页: undefined
> "Client network socket disconnected before secure TLS connection was established"
> 京豆变动通知 API请求失败，请检查网路重试
> 第1页: undefined
> "Client network socket disconnected before secure TLS connection was established"
> 京豆变动通知 API请求失败，请检查网路重试
> 
> 这是啥情况？求教

你不看通知吗？会发Issus不看readme？
