### ISSUE TITLE
我在部署的时候安装面板出错。

### ISSUE THREAD

**Issue by binhe-cpu** [SuperManito/JD-FreeFuck#120]
![image](https://user-images.githubusercontent.com/61576528/109778736-24146680-7c40-11eb-9089-e5aa8a1a238b.png)
请问这个怎么解决。

**Comment by SuperManito** [comment]
网不好，看《常见问题与帮助》重装

**Comment by binhe-cpu** [comment]
好的，谢谢了

**Comment by SuperManito** [comment]
客气了，很多软件包的安装都得走国外服务器，因为国内没有，没办法换国内源
