### ISSUE TITLE
挂机任务启动后，怎么停止呢？

### ISSUE THREAD

**Issue by wnyrng** [SuperManito/JD-FreeFuck#121]
jd.sh hangup运行的挂机任务，怎么停止呢？

**Comment by benlw** [comment]
ps -aux|grep jd.sh

kill ?

**Comment by SuperManito** [comment]
我都不用那功能

**Comment by SuperManito** [comment]
据说那个功能只跑一个账号，想要一直挂机的话后台执行 `crazy_joy_coin` 活动即可：

    bash jd.sh crazy_joy_coin now &

**Comment by SuperManito** [comment]
执行完上面的命令执行完会输出一个进程PID号，如果你不知道怎么查后台任务那就通过`kill``PID`来关闭
