### ISSUE TITLE
格式化互助码提取里，ForOther 只有一行

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#122]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] amd64 | x86-64 | x86-32
- [ ] arm64 | aarch64 | armv8 | armv7
- [ ] Other

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.3

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
作者你好，我是使用的 `format_share_jd_code.js ` 脚本导出的互助码，帮别人助力的那里只有一行是正常的吗，还是说有bug或者我姿势不对呢？

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
![互助码](https://user-images.githubusercontent.com/48577796/109826856-2e515780-7c76-11eb-874c-796a229980ba.png)

**Comment by SuperManito** [comment]
你是死脑筋吗？本来作者写的就是一行，你自己复制一下就行了，除了ForOther后面的序号不同其它都一样

**Comment by bytepoem** [comment]
谢谢
