### ISSUE TITLE
执行不了部署命令

### ISSUE THREAD

**Issue by liuckv** [SuperManito/JD-FreeFuck#123]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7 ` `arm/v6 `
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：20.04

## 7. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：我是在win7下面装的vm10，在vm里面安装了ubuntu，试过直接用bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)这个部署，显示netword connection error,please check the netword environment and try again later，虚拟机里面的host也添加过ip的了，虚拟机用NAT方式，win7用S S R翻，虚拟机可以正常上GG，YT之类的网站，但是执行部署命令之后，还是显示一样的网络连接问题。我的网络是单位网络，会不会和防火墙有关？
![图片1](https://user-images.githubusercontent.com/70507697/109897223-58823400-7ccd-11eb-9349-4ca26ded845b.png)

- [ ] 

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
root@liu-virtual-machine:~/桌面# cd
root@liu-virtual-machine:~# bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)

 ----- Network connection error.Please check the network environment and try again later! ----- 
root@liu-virtual-machine:~# 
root@liu-virtual-machine:~#

**Comment by SuperManito** [comment]
----- Network connection error.Please check the network environment and try again later! -----

英文看不懂？？？？？？

**Comment by SuperManito** [comment]
此报错判定是能否ping通百度

**Comment by liuckv** [comment]
能看懂英文，就是因为看懂，所以我才奇怪，百度，21cn，国内的都能进！

**Comment by SuperManito** [comment]
你自己试试虚拟机里能不能ping通百度就知道了

**Comment by liuckv** [comment]
这样应该算ping通吧？
liu@liu-virtual-machine:~/桌面$ bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
 ------------ Permission no enough, please use user ROOT! ------------ 
liu@liu-virtual-machine:~/桌面$ su
密码： 
root@liu-virtual-machine:/home/liu/桌面# bash <(curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
 ----- Network connection error.Please check the network environment and try again later! ----- 
root@liu-virtual-machine:/home/liu/桌面# ping baidu.com
PING baidu.com (39.156.69.79) 56(84) bytes of data.
![Uploading 2.png…]()

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/109910184-8160f400-7ce2-11eb-8e3d-05adefbb8113.png)
这才叫ping通

**Comment by liuckv** [comment]
ping通百度，就能连上部署命令的了吧？那我找百度问问

**Comment by liuckv** [comment]
我还以为网页能开就表示能连通

**Comment by SuperManito** [comment]
你网卡配的有问题，不是linux的网卡就是VMware的

**Comment by liuckv** [comment]
先谢谢啦，现在已经部署了，但是怎样进项目的控制面板？新手刚接触，请不要见笑。

**Comment by SuperManito** [comment]
> 先谢谢啦，现在已经部署了，但是怎样进项目的控制面板？新手刚接触，请不要见笑。

《部署前需知与准备工作》

**Comment by liuckv** [comment]
所有工作完满完成，感谢撸主的强力支持！
