### ISSUE TITLE
财富岛的互助码

### ISSUE THREAD

**Issue by miwensheng** [SuperManito/JD-FreeFuck#125]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [x] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
不知道的财富岛的互助码要在哪里改，看了财富岛的js文件，完全搞不懂。。想替换都不行。。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
在配置文件改啊，你用的是新版本么？？？

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/109921258-8b8ced80-7cf6-11eb-91cf-b27730fb7bc1.png)

**Comment by miwensheng** [comment]
晕死- -好吧。我也是一直更新的啊。
