### ISSUE TITLE
开启简洁通知，接收不到签到结果通知

### ISSUE THREAD

**Issue by zxfandyy** [SuperManito/JD-FreeFuck#126]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [x] Docker 版本

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [x] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A： Version: v3.29.0

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：定义京东多合一签到推送签到结果通知，用telegram接收消息，开启简洁通知，telegram接收不到签到结果通知，开启详细通知，能接收到签到结果通知，检查配置文件，发现446行和451行的参数是一样的，均为export JD_BEAN_STOP=""，我在451行填的是“true”，446行未填，按配置说明应该是发送简洁通知的，实际上确收不到通知，是否因为446行和451行参数一样导致的原因？

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
已修复，感谢指出问题，已更新配置文件版本号到3.30.1

https://github.com/SuperManito/JD-FreeFuck/blob/source/sample/config.sh.sample
