### ISSUE TITLE
hosts文件会重复添加diy.sh里面的host

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#130]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：
7.3

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
hosts文件会重复添加diy.sh里面的host

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
![image](https://user-images.githubusercontent.com/48577796/110087862-2822be80-7dcf-11eb-955c-4be1fb9a4f27.png)

**Comment by SuperManito** [comment]
这个是别人写的 我把它删了吧
