### ISSUE TITLE
在控制面板无法保存config.sh是怎么回事？？

### ISSUE THREAD

**Issue by Mzs-1118** [SuperManito/JD-FreeFuck#131]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [ ] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
重启控制面板尝试

**Comment by SuperManito** [comment]
看《使用与更新》教程

**Comment by Mzs-1118** [comment]
用指令 手动关闭控制面板    再手动开启控制面板   还是无法保存   只能用sudo  gedit    去编辑了
