### ISSUE TITLE
关于删除失效任务的通知

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#132]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 使用版本

- [x] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：
v3.30.0

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：我发现删除失效任务的通知刚好是diy脚本里面新增的活动，这个正常吗？

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
![image](https://user-images.githubusercontent.com/48577796/110115194-b5c2d600-7df0-11eb-8e97-6567861321b8.png)

**Comment by SuperManito** [comment]
正常的，因为你启用了diy脚本，这些活动都是diy脚本里的，每次执行diy脚本都会删掉原来的重新下载
