### ISSUE TITLE
重装系统重新部署

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#133]
1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [ x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x ] 是
- [ ] 否

2. 使用版本

- [x ] Linux 版本
- [ ] Docker 版本

3. 安装平台

- [ ] PC
- [x ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

 4. 安装平台架构

- [ z] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

 5. 安装环境

- [ x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

6. 安装环境版本

A：Ubuntu18.04

7. 问题类型

- [ x] 部署问题
- [ ] 使用问题

8. 详细叙述您的问题
 (1) 具体问题
A：
问个问题，比如像3月5号修复更新的这些命令。
我要是重装系统重新部署，那还需要执行3月5号修复更新命令吗？

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
肯定不需要啊
