### ISSUE TITLE
财富岛 我自己的号没有被助力   全帮别人助力了    是我设置哪里出错了吗？？

### ISSUE THREAD

**Issue by Mzs-1118** [SuperManito/JD-FreeFuck#134]
![QQ图片20210306092017](https://user-images.githubusercontent.com/79925406/110190325-ab8af100-7e5d-11eb-8550-75bbeea1169a.png)

## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [ ] 是
- [ ] 否

## 2. 使用版本

- [ ] Linux 版本
- [ ] Docker 版本

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
不清楚，去问lxk

**Comment by Mzs-1118** [comment]
设置这样是没错的吧？

**Comment by SuperManito** [comment]
> 设置这样是没错的吧？

有错，我刚才没仔细看

**Comment by SuperManito** [comment]
> 设置这样是没错的吧？

自己领悟
![image](https://user-images.githubusercontent.com/68613938/110198107-0129c280-7e8b-11eb-8cbf-cdef1e41f184.png)

**Comment by Mzs-1118** [comment]
领悟到了！！  名字不对  下面助力的名字和上面对不上

**Comment by Mzs-1118** [comment]
谢谢大佬！！

**Comment by Mzs-1118** [comment]
大佬  我控制面板还是没办法保存！！不知道是什么情况！！手动关闭再开启还是一样不能保存！！

**Comment by luoli8** [comment]
> 领悟到了！！ 名字不对 下面助力的名字和上面对不上

哪错了，我怎么还没看明白

**Comment by Mzs-1118** [comment]
仔细看助力码的名称  和下面被助力的名称！！

**Comment by SuperManito** [comment]
> 大佬 我控制面板还是没办法保存！！不知道是什么情况！！手动关闭再开启还是一样不能保存！！

你用的VPS么
