### ISSUE TITLE
diy.sh 中 Grep 找不到文件

### ISSUE THREAD

**Issue by siche** [SuperManito/JD-FreeFuck#136]
我是在wsl中运行的，在更新diy脚本的时候，grep报错，如下：
![image](https://user-images.githubusercontent.com/19707283/110226798-f293e780-7f2c-11eb-94c7-5baed4ce230f.png)
需要手动修改成完整的路径(/opt/jd/config/crontab.list)才有效，可能是wsl自己的问题。

**Comment by SuperManito** [comment]
你用的是我的项目么，我的项目不会出现这个问题，而且这脚本也不是我项目里的
