### ISSUE TITLE
/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list...

### ISSUE THREAD

**Issue by GSMix** [SuperManito/JD-FreeFuck#138]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：CentOS8

## 7. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：删除了原先使用过的config文件夹内容。然后1.下载镜像 2.按照命令部署，出现如题所示，部署失败。所以该项目默认部署前需要主动上传list文件到config文件夹吗？

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
```
========================1. 更新源代码========================

crond[8]: crond (busybox 1.31.1) started, log level 8

-----------------------------------------------

        当前系统时间：2021-03-08 06:44

        活动脚本目录：/jd/scripts

-----------------------------------------------

更新 JD-FreeFuck 项目脚本：

Fetching origin
HEAD is now at cc458e9 Update jd.sh

更新 lxk0301 活动脚本：

Fetching origin
HEAD is now at 88143d5 签到文件添加进.gitignore

-----------------------------------------------

/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list...

活动脚本更新完成......

sed: /jd/config/config.sh: No such file or directory
```

**Comment by infisz** [comment]
同样问题，部署完成后无法正常启动容器！其他容器正常！

**Comment by atopsecret** [comment]
我昨天晚上遇到了一样的问题，容器无法正常启动

发自我的iPhone

在 2021年3月8日，09:11，infisz <notifications@github.com> 写道：

﻿

同样问题，部署完成后无法正常启动容器！其他容器正常！

**Comment by SuperManito** [comment]
> 同样问题，部署完成后无法正常启动容器！其他容器正常！

不需要，你到底是用的Docker版本还是linux版本

**Comment by atopsecret** [comment]
我是docker

发自我的iPhone

在 2021年3月8日，11:25，SuperManito <notifications@github.com> 写道：

﻿

同样问题，部署完成后无法正常启动容器！其他容器正常！

不需要，你到底是用的Docker版本还是linux版本

**Comment by SuperManito** [comment]
不需要，初始化容器的时候如果未检测到这个定时文件会自动从sample里复制过去

**Comment by infisz** [comment]
> > 同样问题，部署完成后无法正常启动容器！其他容器正常！
> 
> 不需要，你到底是用的Docker版本还是linux版本

DOCKER版本，重新部署，初始化容器，没有显示容器启动成功，进JD目录config文件夹空白。

**Comment by SuperManito** [comment]
确实有问题，可能跟我昨天更新初始化脚本有关系，我看看

**Comment by wxuuu** [comment]
docker run -dit \
-v /home/ubuntu/jd/scripts:/jd/scripts \
-v /home/ubuntu/jd/config:/jd/config \
-v /home/ubuntu/jd/log:/jd/log \
-p 5678:5678 \
-e ENABLE_HANGUP=true \
-e ENABLE_WEB_PANEL=true \
--name jd \
--network bridge \
--hostname jd \
--restart always \
registry.cn-hangzhou.aliyuncs.com/supermanito/jd

提示/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list...

**Comment by live8712** [comment]
控制面板启动成功...

如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito

请访问 http://<ip>:5678 登陆并修改配置...

容器启动成功......

Welcome to Node.js v14.16.0.
Type ".help" for more information.
> crond[8]: USER root pid 1565 cmd bash jd jd_jdfactory
crond[8]: USER root pid 2164 cmd bash /jd/jd.sh jd_xxl_gh
crond[8]: USER root pid 3244 cmd bash git_pull >> /jd/log/git_pull.log 2>&1
crond[8]: USER root pid 3246 cmd bash /jd/jd.sh jd_axc
crond[8]: USER root pid 3247 cmd bash jd jd_plantBean
crond[8]: USER root pid 3283 cmd bash jd jd_jdzz
crond[8]: USER root pid 3284 cmd bash jd jd_joy_run

========================1. 更新源代码========================

crond[8]: crond (busybox 1.31.1) started, log level 8
bash: git_pull: No such file or directory

部署成功了 重启容器后就不停的重启

**Comment by wxuuu** [comment]
> 控制面板启动成功...
> 
> 如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito
> 
> 请访问 http://:5678 登陆并修改配置...
> 
> 容器启动成功......
> 
> Welcome to Node.js v14.16.0.
> Type ".help" for more information.
> 
> > crond[8]: USER root pid 1565 cmd bash jd jd_jdfactory
> > crond[8]: USER root pid 2164 cmd bash /jd/jd.sh jd_xxl_gh
> > crond[8]: USER root pid 3244 cmd bash git_pull >> /jd/log/git_pull.log 2>&1
> > crond[8]: USER root pid 3246 cmd bash /jd/jd.sh jd_axc
> > crond[8]: USER root pid 3247 cmd bash jd jd_plantBean
> > crond[8]: USER root pid 3283 cmd bash jd jd_jdzz
> > crond[8]: USER root pid 3284 cmd bash jd jd_joy_run
> 
> ========================1. 更新源代码========================
> 
> crond[8]: crond (busybox 1.31.1) started, log level 8
> bash: git_pull: No such file or directory
> 
> 部署成功了 重启容器后就不停的重启

因为crontab.list文件没自动创建，不知道怎么解决

**Comment by SuperManito** [comment]
目前以定位到问题，正在解决

**Comment by SuperManito** [comment]
已经修复，请各位重新创建容器即可

**Comment by atopsecret** [comment]
收到，感谢大佬

发自我的iPhone

在 2021年3月8日，11:56，SuperManito <notifications@github.com> 写道：

﻿

已经修复，请各位重新创建容器即可
