### ISSUE TITLE
Docker版本修复与升级

### ISSUE THREAD

**Issue by kinggkl** [SuperManito/JD-FreeFuck#139]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：20.10.2

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：更新提示错误，已手动解决。
1、升级提示没有找到文件。
2、翻看代码无创建目录命令于是手动创建。
3、创建目录后执行脚本仍提示找不到文件。
4、根据脚本内容手动下载。
5、成功执行升级脚本，DIY脚本更新报错。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
root@jd:/jd $ bash <(curl -sSL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)
--2021-03-08 08:45:43--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh                                      [ <=>                                                                                        ]  14.36K  --.-KB/s    in 0.04s

2021-03-08 08:45:44 (358 KB/s) - 'git_pull.sh' saved [14707]

bash: /opt/jd/git_pull.sh: No such file or directory
 +------------------------ 更 新 成 功 ------------------------+
 |                                                             |
 | 特别提示：后续使用遇到问题请访问本人项目页寻求帮助          |
 |                                                             |
 |           我不是活动脚本的开发者，所有活动问题与我无关      |
 |                                                             |
 | 项目地址：https://github.com/SuperManito/JD-FreeFuck        |
 |           https://gitee.com/SuperManito/JD-FreeFuck         |
 |                                                             |
 +-------------------------------------------------------------+
root@jd:/jd $ cd /opt/
root@jd:/opt $ ls
yarn-v1.22.5
root@jd:/opt $ cd /jd
root@jd:/jd $ ls
config  docker  export_sharecodes.sh  git_pull.sh  jd.sh  log  panel  rm_log.sh  run-all.sh  sample  scripts  update.js
root@jd:/jd $ cd /opt
root@jd:/opt $ mk jd
bash: mk: command not found
root@jd:/opt $ mkdir jd
root@jd:/opt $ ls
jd  yarn-v1.22.5
root@jd:/opt $ cd /j
bash: cd: /j: No such file or directory
root@jd:/opt $ cd /jd
root@jd:/jd $ bash <(curl -sSL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)
--2021-03-08 08:48:26--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh                                      [ <=>                                                                                        ]  14.36K  --.-KB/s    in 0.04s

2021-03-08 08:48:26 (357 KB/s) - 'git_pull.sh' saved [14707]

bash: /opt/jd/git_pull.sh: No such file or directory
 +------------------------ 更 新 成 功 ------------------------+
 |                                                             |
 | 特别提示：后续使用遇到问题请访问本人项目页寻求帮助          |
 |                                                             |
 |           我不是活动脚本的开发者，所有活动问题与我无关      |
 |                                                             |
 | 项目地址：https://github.com/SuperManito/JD-FreeFuck        |
 |           https://gitee.com/SuperManito/JD-FreeFuck         |
 |                                                             |
 +-------------------------------------------------------------+
root@jd:/jd $ cd /opt
root@jd:/opt $ ls
jd  yarn-v1.22.5
root@jd:/opt $ cd jd
root@jd:/opt/jd $ wget https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
--2021-03-08 08:49:16--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh                                      [ <=>                                                                                        ]  14.36K  --.-KB/s    in 0.04s

2021-03-08 08:49:16 (354 KB/s) - 'git_pull.sh' saved [14707]

root@jd:/opt/jd $ ls
git_pull.sh
root@jd:/opt/jd $ cd /jd
root@jd:/jd $ wget https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
--2021-03-08 08:49:45--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh.1'

git_pull.sh.1                                    [ <=>                                                                                        ]  14.36K  --.-KB/s    in 0.04s

2021-03-08 08:49:45 (364 KB/s) - 'git_pull.sh.1' saved [14707]

root@jd:/jd $ ls /opt/jd
git_pull.sh
root@jd:/jd $ bash <(curl -sSL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)
--2021-03-08 08:50:35--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh                                      [ <=>                                                                                        ]  14.36K  --.-KB/s    in 0.04s

2021-03-08 08:50:35 (376 KB/s) - 'git_pull.sh' saved [14707]

-----------------------------------------------

        当前系统时间：2021-03-08 08:50

        活动脚本目录：/jd/scripts

-----------------------------------------------

更新 JD-FreeFuck 项目脚本：

Fetching origin
HEAD is now at cc458e9 Update jd.sh

更新 lxk0301 活动脚本：

Fetching origin
HEAD is now at 88143d5 签到文件添加进.gitignore

-----------------------------------------------

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
自定义 DIY 脚本同步失败......

开始下载 i-chenzhe 的脚本
https://raw.sevencdn.com/i-chenzhe/qx/main/jd_entertainment.js
jd_entertainment.js
更新 jd_entertainment.js 完成...

https://raw.sevencdn.com/i-chenzhe/qx/main/jd_jump_jump.js
jd_jump_jump.js
更新 jd_jump_jump.js 完成...

https://raw.sevencdn.com/i-chenzhe/qx/main/jd_shake.js
jd_shake.js
更新 jd_shake.js 完成...

https://raw.sevencdn.com/i-chenzhe/qx/main/jd_shakeBean.js
jd_shakeBean.js
更新 jd_shakeBean.js 完成...

开始下载 JDMyself 的脚本
https://raw.sevencdn.com/573462273/JDMyself/main/scripts/jd_axc.js
jd_axc.js
更新 jd_axc.js 完成...

https://raw.sevencdn.com/573462273/JDMyself/main/scripts/jd_xxl_gh.js
jd_xxl_gh.js
更新 jd_xxl_gh.js 完成...

开始下载 whyour 的脚本
https://raw.sevencdn.com/whyour/hundun/master/quanx/jx_factory_component.js
jx_factory_component.js
更新 jx_factory_component.js 完成...

活动脚本更新完成......

 +------------------------ 更 新 成 功 ------------------------+
 |                                                             |
 | 特别提示：后续使用遇到问题请访问本人项目页寻求帮助          |
 |                                                             |
 |           我不是活动脚本的开发者，所有活动问题与我无关      |
 |                                                             |
 | 项目地址：https://github.com/SuperManito/JD-FreeFuck        |
 |           https://gitee.com/SuperManito/JD-FreeFuck         |
 |                                                             |
 +-------------------------------------------------------------+

**Comment by kinggkl** [comment]
仔细核对配置文件有新变量
EnableExtraShellURL="https://gitee.com/SuperManito/JD-FreeFuck/raw/main/diy/diy.sh"
添加后更新DIY脚本顺利更新

**Comment by SuperManito** [comment]
谁让你执行update升级修复脚本了？你没看通知是让Linux版执行吗？我真服了

**Comment by SuperManito** [comment]
root@jd:/jd $ wget https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
--2021-03-08 08:49:45-- https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh.1'

git_pull.sh.1 [ <=> ] 14.36K --.-KB/s in 0.04s

2021-03-08 08:49:45 (364 KB/s) - 'git_pull.sh.1' saved [14707]

**Comment by SuperManito** [comment]
我使用教程更新命令是这么写的？？？

**Comment by kinggkl** [comment]
我是用容器版本。这是按照你的更新操作执行的结果
root@jd:/jd $ bash <(curl -sSL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)
--2021-03-08 08:45:43-- https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh [ <=> ] 14.36K --.-KB/s in 0.04s

2021-03-08 08:45:44 (358 KB/s) - 'git_pull.sh' saved [14707]

bash: /opt/jd/git_pull.sh: No such file or directory

找不到git_pull文件所以我只好去看update代码。根据代码自行下载执行


还有冷静点我手动解决了这个问题，但是这会对没能力手动解决的人有影响感觉至少反馈分享下。

**Comment by kinggkl** [comment]
> 我使用教程更新命令是这么写的？？？

我是用容器版本。这是按照你的更新操作执行的结果
root@jd:/jd $ bash <(curl -sSL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)
--2021-03-08 08:45:43-- https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 212.64.62.183
Connecting to gitee.com|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'

git_pull.sh [ <=> ] 14.36K --.-KB/s in 0.04s

2021-03-08 08:45:44 (358 KB/s) - 'git_pull.sh' saved [14707]

bash: /opt/jd/git_pull.sh: No such file or directory

找不到git_pull文件所以我只好去看update代码。根据代码自行下载执行

还有冷静点我手动解决了这个问题，但是这会对没能力手动解决的人有影响感觉至少反馈分享下。

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110272666-aff20e00-8005-11eb-8be0-abfafdc3827e.png)
我让Docker版本的用户更新了？？？？？？？？
