### ISSUE TITLE
之前直装的要怎么更新呢？

### ISSUE THREAD

**Issue by snow61520** [SuperManito/JD-FreeFuck#14]
现在都是自己手动替换，比较麻烦

**Comment by SuperManito** [comment]
什么是手动替换？之前直装的跟现在的Docker没有任何关系，直接重新一键部署就好了，之前的把/home/myid整个目录删了即可

**Comment by snow61520** [comment]
> 什么是手动替换？之前直装的跟现在的Docker没有任何关系，直接重新一键部署就好了，之前的把/ home / myid整个目录删除了即可

好的，我试试 我就在gitee把更新的js文件复制替换，手动弄的

**Comment by SuperManito** [comment]
> 的，我试试 我就在gitee把更新的js文件复制替换，手动弄的

你手动换的能用？我没试过

**Comment by snow61520** [comment]
> > 的，我试试 我就在gitee把更新的js文件复制替换，手动弄的
> 
> 你手动换的能用？我没试过

Digest: sha256:c6cbcf326319f85b25c77c0f7bb2f4abe9b12cbe936d0d6af17a97de622013da
Status: Downloaded newer image for evinedeng/jd:gitee
docker.io/evinedeng/jd:gitee
24317d7039c32a0795ac4265207978b1bafba58fdaef788259696a1bbd5bb148
大佬，我好像卡这了，要咋弄呢

**Comment by SuperManito** [comment]
> > > 的，我试试 我就在gitee把更新的js文件复制替换，手动弄的
> > 
> > 
> > 你手动换的能用？我没试过
> 
> Digest: sha256:c6cbcf326319f85b25c77c0f7bb2f4abe9b12cbe936d0d6af17a97de622013da
> Status: Downloaded newer image for evinedeng/jd:gitee
> docker.io/evinedeng/jd:gitee
> 24317d7039c32a0795ac4265207978b1bafba58fdaef788259696a1bbd5bb148
> 大佬，我好像卡这了，要咋弄呢

回车或者等一会儿就好了

**Comment by snow61520** [comment]
> > > > 的，我试试 我就在gitee把更新的js文件复制替换，手动弄的
> > > 
> > > 
> > > 你手动换的能用？我没试过
> > 
> > 
> > Digest: sha256:c6cbcf326319f85b25c77c0f7bb2f4abe9b12cbe936d0d6af17a97de622013da
> > Status: Downloaded newer image for evinedeng/jd:gitee
> > docker.io/evinedeng/jd:gitee
> > 24317d7039c32a0795ac4265207978b1bafba58fdaef788259696a1bbd5bb148
> > 大佬，我好像卡这了，要咋弄呢
> 
> 回车或者等一会儿就好了

我这估计有一个小时没动了，回车也没反应

**Comment by SuperManito** [comment]
> > > > > 的，我试试 我就在gitee把更新的js文件复制替换，手动弄的
> > > > 
> > > > 
> > > > 你手动换的能用？我没试过
> > > 
> > > 
> > > Digest: sha256:c6cbcf326319f85b25c77c0f7bb2f4abe9b12cbe936d0d6af17a97de622013da
> > > Status: Downloaded newer image for evinedeng/jd:gitee
> > > docker.io/evinedeng/jd:gitee
> > > 24317d7039c32a0795ac4265207978b1bafba58fdaef788259696a1bbd5bb148
> > > 大佬，我好像卡这了，要咋弄呢
> > 
> > 
> > 回车或者等一会儿就好了
> 
> 我这估计有一个小时没动了，回车也没反应

这是卡在创建容器上了，你看有没有创建成功（docker ps -a）创建成功了就删掉重新一键部署，没成功直接重新一键部署

**Comment by SuperManito** [comment]
删除命令 docker rm -f  24317d7039c3
然后重新部署

**Comment by SuperManito** [comment]
感谢兄弟

**Comment by snow61520** [comment]
> 感谢兄弟

老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
/jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
/jd/config/config.sh: line 705: syntax error: unexpected end of file

**Comment by SuperManito** [comment]
> > 感谢兄弟
> 
> 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> /jd/config/config.sh: line 705: syntax error: unexpected end of file

你的config.sh配置文件自己改出问题了吧

**Comment by snow61520** [comment]
> > > 感谢兄弟
> > 
> > 
> > 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> > /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> > /jd/config/config.sh: line 705: syntax error: unexpected end of file
> 
> 你的config.sh配置文件自己改出问题了吧

这次docker部署我就复制了cookies这些，其他的也没动。  之前ubuntu直装的就没出现过问题，docker安装的问题吗？ 我现在有的脚本跑着又是正常的

**Comment by SuperManito** [comment]
> > > > 感谢兄弟
> > > 
> > > 
> > > 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> > > /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> > > /jd/config/config.sh: line 705: syntax error: unexpected end of file
> > 
> > 
> > 你的config.sh配置文件自己改出问题了吧
> 
> 这次docker部署我就复制了cookies这些，其他的也没动。 之前ubuntu直装的就没出现过问题，docker安装的问题吗？ 我现在有的脚本跑着又是正常的

你用的什么系统啊

**Comment by snow61520** [comment]
> > > > > 感谢兄弟
> > > > 
> > > > 
> > > > 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> > > > /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> > > > /jd/config/config.sh: line 705: syntax error: unexpected end of file
> > > 
> > > 
> > > 你的config.sh配置文件自己改出问题了吧
> > 
> > 
> > 这次docker部署我就复制了cookies这些，其他的也没动。 之前ubuntu直装的就没出现过问题，docker安装的问题吗？ 我现在有的脚本跑着又是正常的
> 
> 你用的什么系统啊

现在用的ubuntu，用的你那个一键部署

**Comment by SuperManito** [comment]
> > > > > > 感谢兄弟
> > > > > 
> > > > > 
> > > > > 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> > > > > /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> > > > > /jd/config/config.sh: line 705: syntax error: unexpected end of file
> > > > 
> > > > 
> > > > 你的config.sh配置文件自己改出问题了吧
> > > 
> > > 
> > > 这次docker部署我就复制了cookies这些，其他的也没动。 之前ubuntu直装的就没出现过问题，docker安装的问题吗？ 我现在有的脚本跑着又是正常的
> > 
> > 
> > 你用的什么系统啊
> 
> 现在用的ubuntu，用的你那个一键部署

那不应该有问题的 肯定是你配置文件配错了 你想想你有没有改什么东西

**Comment by snow61520** [comment]
> > > > > > > 感谢兄弟
> > > > > > 
> > > > > > 
> > > > > > 老哥，我这有时候显示这个是咋回事呀，还会卡主，之前直装的没出现过这种，是哪里有问题？
> > > > > > /jd/config/config.sh: line 704: unexpected EOF while looking for matching `"'
> > > > > > /jd/config/config.sh: line 705: syntax error: unexpected end of file
> > > > > 
> > > > > 
> > > > > 你的config.sh配置文件自己改出问题了吧
> > > > 
> > > > 
> > > > 这次docker部署我就复制了cookies这些，其他的也没动。 之前ubuntu直装的就没出现过问题，docker安装的问题吗？ 我现在有的脚本跑着又是正常的
> > > 
> > > 
> > > 你用的什么系统啊
> > 
> > 
> > 现在用的ubuntu，用的你那个一键部署
> 
> 那不应该有问题的 肯定是你配置文件配错了 你想想你有没有改什么东西

其他没动，我重新弄个ubuntu系统再试试，找下原因

**Comment by snow61520** [comment]
下列【新】软件包将被安装：
  dos2unix
升级了 0 个软件包，新安装了 1 个软件包，要卸载 0 个软件包，有 375 个软件包未被升级。
需要下载 351 kB 的归档。
解压缩后会消耗 1,267 kB 的额外空间。
获取:1 https://mirrors.ustc.edu.cn/ubuntu bionic/universe amd64 dos2unix amd64 7.3.4-3 [351 kB]
已下载 351 kB，耗时 1秒 (607 kB/s)
正在选中未选择的软件包 dos2unix。
(正在读取数据库 ... 系统当前共安装有 129981 个文件和目录。)
正准备解包 .../dos2unix_7.3.4-3_amd64.deb  ...
正在解包 dos2unix (7.3.4-3) ...
正在设置 dos2unix (7.3.4-3) ...
正在处理用于 man-db (2.8.3-2ubuntu0.1) 的触发器 ...
dos2unix: /opt/jd/run-all.sh: 没有那个文件或目录
dos2unix: 跳过 /opt/jd/run-all.sh，不是一个普通文件。
dos2unix: /opt/jd/manual-update.sh: 没有那个文件或目录
dos2unix: 跳过 /opt/jd/manual-update.sh，不是一个普通文件。
bash: /opt/jd/manual-update.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
sed: 无法读取 /opt/jd/config/config.sh: 没有那个文件或目录
 -------------- 一键部署失败 --------------
之前那个还是有问题，我就填了个cookies，然后有的脚本还是卡主不动。  我重新在虚拟机上部署就出现这个，新系统部署了几次，还是同样的问题。  我在那些群里看到那个docker镜像要被删了，后面是不是不好弄了

**Comment by snow61520** [comment]
我又买个ubuntu服务器也是跟我虚拟机一样，报的同样的错

**Comment by SuperManito** [comment]
evine的容器没了，拉不到镜像，我也不知道发生了什么，不是我脚本的问题，等等看吧 https://hub.docker.com/r/evinedeng/jd
