### ISSUE TITLE
最新的脚本在config.sh中配置DIY模块为true后，再次运行gitpull.sh ，新的DIY任务将不会同步到crontab.list中。

### ISSUE THREAD

**Issue by jikkyfu** [SuperManito/JD-FreeFuck#141]
环境：LINUX 最新的脚本
问题：在config.sh中配置DIY模块为true后，再次运行gitpull.sh ，新的DIY任务将不会同步到crontab.list中。

建议：新增加一个DIY任务的版本号，在gitpull脚本中进行检测，当发现更新就同步，并同步更新crontab.list文件。

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110278040-77583180-8011-11eb-96d5-62ed4c4d5df8.png)
没有任何问题，刚搭的
