### ISSUE TITLE
更新不到新面板。。。不知道是不是步骤错了。。

### ISSUE THREAD

**Issue by miwensheng** [SuperManito/JD-FreeFuck#144]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x ] 是
- [ ] 否

## 2. 安装版本

- [x ] Linux
- [ ] Docker

## 3. 安装平台

- [x ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [x ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x ] 使用问题

### (1) 具体问题
A：是不是先 git_pull 更新脚本，在执行修复与升级，最后在重启控制面板完成更新？
我的面板还是3.30.1。。。在线对比工具也是3.30.1。。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by feitxue** [comment]
奇怪,我也更新不到.

**Comment by bytepoem** [comment]
先执行修复与升级

**Comment by miwensheng** [comment]
我重新部署了- -完全解决了。。。

**Comment by SuperManito** [comment]
> 奇怪,我也更新不到.
> 执行了2021/3/05 19:00 修复 2021/3/05 21:20 修复两个标题里面的命令.
> 然后z执行git_pull.sh
> 尝试pm2 restart 还是旧面板,
> 最后手动stop,手动start面板还是旧的
> 最后我把panel路径下 node_modules 删除了.重新执行npm install server.js
> 还是访问的旧的控制面板

**Comment by SuperManito** [comment]
仔细去看通知要求，没什么问题
