### ISSUE TITLE
取关商品 店铺不生效

### ISSUE THREAD

**Issue by xxstudy** [SuperManito/JD-FreeFuck#145]
bash /opt/jd/jd.sh jd_unsubscribe 无法执行 或者执行出错

**Comment by bytepoem** [comment]
你这样提问作者不会理你的，人家不是给了个模板吗

**Comment by SuperManito** [comment]
> 你这样提问作者不会理你的，人家不是给了个模板吗

👍，我已经习惯了，总有很多小白不按规矩来，Github的模板是最严格的，我真奇了怪了
