### ISSUE TITLE
设置财富岛不推送通知，但是还是会收到通知

### ISSUE THREAD

**Issue by baiye233** [SuperManito/JD-FreeFuck#146]
在config.sh设置财富岛推送通知为不推送，export CFD_NOTIFY_CONTROL="false"，但是还是会推送

**Comment by miwensheng** [comment]
我设置的推送，但是我收不到，我现在知道了。应该设置false

**Comment by baiye233** [comment]
反着来的吗

**Comment by miwensheng** [comment]
应该是，我刚刚看了我的config，我选择默认，但是从来没有收到过推送。

**Comment by SuperManito** [comment]
这个在之前的配置文件中我确实写反了，前两个版本我已经改了，以最新的配置文件为准
