### ISSUE TITLE
3月7日-9日这两个版本，centos7下部署，执行bash run_all.sh会卡住,cpu超高占用率

### ISSUE THREAD

**Issue by airs777** [SuperManito/JD-FreeFuck#147]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x]是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：3月7日-9日这两个版本，centos7下部署，执行bash run_all.sh会卡住,。CTRL+C结束之后，重新执行依旧，按回车跳过也没反应。cpu超高占用率。之前某个版本出现过这种情况，后来作者修复了。目前该情况再次出现

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by miwensheng** [comment]
你咋解决的啊？我卡在签到了。。

**Comment by SuperManito** [comment]
换最新的系统，nodejs的问题，我也确定不了原因

**Comment by airs777** [comment]
重新部署了几次，莫名其妙的就过去了。centos7都是快照直接还原然后重新部署的。虽然初次运行的时候也会卡一会，不过一会就过去了。我也不知道为啥突然就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aiioMi"<notifications@github.com&gt;; 
发送时间: 2021年3月9日(星期二) 中午1:38
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "."<2033699440@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 问题已经处理。不知道怎么删除这个 (#147)





 
你咋解决的啊？我卡在签到了。。
