### ISSUE TITLE
为什么一直不停的请求m.jingxi.com

### ISSUE THREAD

**Issue by thinktip** [SuperManito/JD-FreeFuck#148]
开了Adguard Home看到，一天十几万的请求，是什么原因？

**Comment by SuperManito** [comment]
> 开了Adguard Home看到，一天十几万的请求，是什么原因？

活动脚本就是从各个活动里做任务，点链接、视频、广告，这种奇葩问题为什么要问我，你开去广告我怎么知道会出现什么问题
