### ISSUE TITLE
BARK 提供多个设备码进行多用户消息推送

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#149]
![image](https://user-images.githubusercontent.com/48577796/110455871-e1e99a00-8103-11eb-9ca3-7082da7d30c6.png)

刚刚看到了推送加的一对多服务准备停了，希望在 BARK_PUSH 能支持输入多个设备码，从而达到多用户推送。

**Comment by SuperManito** [comment]
我没用过这个，所有内容以 lxk 定义的变量为准 https://gitee.com/lxk0301/jd_docker/blob/master/githubAction.md
