### ISSUE TITLE
建议提供 crontab 支持

### ISSUE THREAD

**Issue by OiCkilL** [SuperManito/JD-FreeFuck#15]
目前用 run-all.sh 的话很容易黑号而且有不少脚本是需要循环运行的，例如 jd_crazy_joy 和 jd_immortal_answer 等

**Comment by SuperManito** [comment]
黑号是什么意思，我用我一键脚本一个多月了没出现什么问题，遇到挂机脚本直接Ctrl+Z/C跳过就好，定时的话自己去研究，我看作者都写好写进系统了，每个人使用环境不一样
