### ISSUE TITLE
运行东东农场报错

### ISSUE THREAD

**Issue by 457992195** [SuperManito/JD-FreeFuck#150]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x ] 是
- [ ] 否

## 2. 安装版本

- [x ] Linux
- [ ] Docker

## 3. 安装平台

- [x ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：运行东东农场报错

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：东东农场: API查询请求失败 ‼️‼️
"read ECONNRESET"

❗️东东农场, 错误!

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read property 'code' of undefined
    at duck (/opt/jd/scripts/jd_fruit.js:917:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async jdFruit (/opt/jd/scripts/jd_fruit.js:118:7)
    at async /opt/jd/scripts/jd_fruit.js:71:7

**Comment by SuperManito** [comment]
黑号
