### ISSUE TITLE
无法屏蔽某个账号的某个脚本

### ISSUE THREAD

**Issue by yanyudalao** [SuperManito/JD-FreeFuck#152]
## 如果只是想要屏蔽某个账号不玩某些小游戏，可以参考下面 case 这个命令的例子来控制，脚本名称请去掉后缀 “.js”
 case $1 in
   jd_bookshop)
     TempBlockCookie="1"      # 账号5不玩东东农场
     ;;
   jd_dreamFactory | jd_jdfactory)
     TempBlockCookie="2"      # 账号2不玩京喜工厂和东东工厂
     ;;
   jd_jdzz | jd_joy)
     TempBlockCookie="3 6"    # 账号3、账号6不玩京东赚赚和宠汪汪
     ;;
  esac
TempBlockCookie=""
###########################################################################################
按照以上写法。。 手动运行脚本时，还是直接继续运行。 _(:з」∠)_

**Comment by SuperManito** [comment]
那不清楚，自学shell编程吧

**Comment by yanyudalao** [comment]
大佬，不是这个意思。。。

以上那段代码，即使只是解除了注释，也不会跳过指定账号的指定脚本，还是全部运行。
粘贴出来的那段，只是把注释解除和换了第一个脚本名称。

以上那段代码应该是没有错误的，但是没有运行程序，可能问题出在别的地方？
