### ISSUE TITLE
docker版git_pull.log日志显示更新失败

### ISSUE THREAD

**Issue by leic4u** [SuperManito/JD-FreeFuck#153]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：centos 7

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：docker版 在控制面板中查看日志，其中git_pull.log的内容显示，每小时的git_pull.sh活动脚本更新都失败了，只成功了项目脚本的更新。看了下日志，是同时连接数过多导致的，实测修改git_pull.sh的cron时间可以解决这个问题。建议docker的git_pull.sh的运行时间处加个注释，让大家手动修改一下。（或者看有没有办法加个随机数？）
另外就是，手动运行的git_pull.sh，好像没有生成日志到git_pull.log中，手动运行了很多次，都没有在git_pull.log里找到日志。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
```-----------------------------------------------

        当前系统时间：2021-03-10 08:55

        活动脚本目录：/jd/scripts

-----------------------------------------------

更新 JD-FreeFuck 项目脚本：

Fetching origin
HEAD is now at c9b3392 Update run.html

更新 lxk0301 活动脚本：

Fetching origin
Handshake: [31mRepository more than 5 connections.[0m
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at c972864 update

-----------------------------------------------

活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......


-----------------------------------------------

        当前系统时间：2021-03-10 09:55

        活动脚本目录：/jd/scripts

-----------------------------------------------

更新 JD-FreeFuck 项目脚本：

Fetching origin
From https://github.com/SuperManito/JD-FreeFuck
   c9b3392..949aac9  source     -> origin/source
HEAD is now at 949aac9 bugfix

更新 lxk0301 活动脚本：

Fetching origin
Handshake: [31mRepository more than 5 connections.[0m
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
HEAD is now at c972864 update

-----------------------------------------------

活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......


-----------------------------------------------

        当前系统时间：2021-03-10 10:21

        活动脚本目录：/jd/scripts

-----------------------------------------------

更新 JD-FreeFuck 项目脚本：

Fetching origin
HEAD is now at 949aac9 bugfix

更新 lxk0301 活动脚本：

Fetching origin
From gitee.com:lxk0301/jd_scripts
   c972864..5bde466  master     -> origin/master
HEAD is now at 5bde466 docker单容器多账号自动助力

-----------------------------------------------

自定义 DIY 脚本同步完成......

开始下载 i-chenzhe 的脚本
https://raw.sevencdn.com/i-chenzhe/qx/main/jd_entertainment.js
jd_entertainment.js
更新 jd_entertainment.js 完成...

https://raw.sevencdn.com/i-chenzhe/qx/main/jd_shake.js
jd_shake.js
更新 jd_shake.js 完成...

https://raw.sevencdn.com/i-chenzhe/qx/main/jd_shakeBean.js
jd_shakeBean.js
更新 jd_shakeBean.js 完成...

开始下载 JDMyself 的脚本
https://raw.sevencdn.com/573462273/JDMyself/main/scripts/jd_axc.js
jd_axc.js
更新 jd_axc.js 完成...

https://raw.sevencdn.com/573462273/JDMyself/main/scripts/jd_xxl_gh.js
jd_xxl_gh.js
更新 jd_xxl_gh.js 完成...

开始下载 whyour 的脚本
https://raw.sevencdn.com/whyour/hundun/master/quanx/jx_factory_component.js
jx_factory_component.js
更新 jx_factory_component.js 完成...

活动脚本更新完成......
```

**Comment by SuperManito** [comment]
去读常见问题与帮助第二条

**Comment by leic4u** [comment]
> 你为什么勾选了 已仔细阅读了《常见问题与帮助》 ？

不是部署过程中的问题，是使用过程中的问题，每次的自动更新都是提示这个。
相当于**自动更新活动脚本**这个功能是**无效**的，只能自动更新项目脚本，想要更新**活动脚本**必须**手动执行**。

另外还有个问题是手动执行的git_pull.sh没有产生日志。

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110587321-7ad4ef80-81ae-11eb-8285-81a8e0f2dbd5.png)

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110587398-95a76400-81ae-11eb-935a-871f25c4d788.png)

**Comment by leic4u** [comment]
![image](https://user-images.githubusercontent.com/68613938/110587321-7ad4ef80-81ae-11eb-8285-81a8e0f2dbd5.png)
建议这个不要写到 **二、项目部署** 里面，容易让人误会是部署过程中可能产生的问题，可以写到Wiki[Linux版使用与更新](https://github.com/SuperManito/JD-FreeFuck/wiki/Linux-Use-And-Update-Tutorial)和[Docker版使用与更新](https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Use-And-Update-Tutorial)中，而且可以建议用户自己改下cron时间，不要使用默认的55分，这样可以避免定时任务老是失败的问题。

![image](https://user-images.githubusercontent.com/68613938/110587398-95a76400-81ae-11eb-935a-871f25c4d788.png)
这个是你手动执行的吗，我的还是不行，我的git_pull.log只记录了定时执行的日志 ![image](https://pic4.zhimg.com/80/v2-7f4085b523f8020102e4343a62916e57_720w.png)

**Comment by SuperManito** [comment]
而且不需要写进什么教程里，本来就是给小白看的

**Comment by leic4u** [comment]
> > ![image](https://user-images.githubusercontent.com/68613938/110587321-7ad4ef80-81ae-11eb-8285-81a8e0f2dbd5.png)
> > 建议这个不要写到 **二、项目部署** 里面，容易让人误会是部署过程中可能产生的问题，可以写到Wiki[Linux版使用与更新](https://github.com/SuperManito/JD-FreeFuck/wiki/Linux-Use-And-Update-Tutorial)和[Docker版使用与更新](https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Use-And-Update-Tutorial)中，而且可以建议用户自己改下cron时间，不要使用默认的55分，这样可以避免定时任务老是失败的问题。
> > ![image](https://user-images.githubusercontent.com/68613938/110587398-95a76400-81ae-11eb-935a-871f25c4d788.png)
> > 这个是我修改了git_pull.sh的cron时间后，定时执行的日志，不是手动执行的日志哈。
> 
> 所以手动执行和定时执行有区别吗？？？理解不了这个报错是吗

我还没说清楚？手动执行，没有，生成，日志。

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/110640579-eee1b880-81eb-11eb-9d4f-73e6adcf3eaa.png)

**Comment by leic4u** [comment]
算了，这两个问题反正也不影响使用，可以不用处理，还是感谢开发者大佬的辛苦付出。
