### ISSUE TITLE
cpu占用一直100%

### ISSUE THREAD

**Issue by KevinZjYang** [SuperManito/JD-FreeFuck#156]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.3

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：3.9号更新后，今天发现没有运行，重新部署，发现cpu占用一直100%。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
node的问题，换最新的系统

**Comment by KevinZjYang** [comment]
昨天下午应为重置没更新系统，更新系统到了7.9版本后，当时CPU占用下来了。刚才我发现控制面板无法登陆了。去后台发现从昨天晚上23:10分开始到现在，cpu占用一直100%。
![image](https://user-images.githubusercontent.com/31529584/110719291-93ddaf00-8247-11eb-9d29-d938a09bafc3.png)
