### ISSUE TITLE
控制面板突然打不开了

### ISSUE THREAD

**Issue by lfscqk67** [SuperManito/JD-FreeFuck#158]
## 2. 安装版本
Docker

## 3. 安装平台
软路由

## 4. 安装平台架构
arm/v8

## 5. 安装环境
Docker

## 7. 问题类型
使用问题

### (1) 具体问题
A：控制面板突然打不开了

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list...

检测到package.json有变化，运行 npm install...

检测到本机安装了 yarn，使用 yarn 替代 npm...

yarn install v1.22.5

info No lockfile found.

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

[1/4] Resolving packages...

warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

warning request > har-validator@5.1.5: this library is no longer supported

info There appears to be trouble with your network connection. Retrying...

[2/4] Fetching packages...

[] 0/204[] 4/204[] 6/204[] 7/204[] 9/204[] 13/204[] 14/204[] 15/204[] 16/204[] 19/204[] 20/204[] 22/204[] 25/204[] 26/204[] 29/204[] 32/204[] 34/204[] 37/204[] 42/204[] 44/204[] 45/204[] 49/204[] 50/204[] 52/204[] 53/204[] 55/204[] 56/204[] 58/204[] 60/204[] 62/204[] 64/204[] 66/204[] 67/204[] 70/204[] 72/204[] 73/204[] 74/204[] 77/204[] 79/204[] 81/204[] 82/204[] 85/204[] 88/204[] 89/204[] 93/204[] 95/204[] 96/204[] 98/204[] 100/204[] 105/204[] 107/204[] 109/204[] 111/204[] 112/204[] 113/204[] 114/204[] 116/204[] 118/204[] 119/204[] 122/204[] 124/204[] 125/204[] 127/204[] 128/204[] 130/204[] 131/204[] 132/204[] 133/204[] 134/204[] 136/204[] 138/204[] 140/204[] 142/204[] 143/204[] 144/204[] 145/204[] 147/204[] 148/204[] 149/204[] 151/204[] 152/204[] 153/204[] 154/204[] 156/204[] 158/204[] 160/204[] 161/204[] 164/204[] 165/204[] 166/204[] 168/204[] 169/204[] 170/204[] 172/204[] 174/204[] 175/204[] 177/204[] 178/204[] 179/204[] 180/204[] 182/204[] 184/204[] 185/204[] 187/204[] 188/204[] 190/204[] 191/204[] 192/204[] 193/204[] 195/204[] 196/204[] 197/204[] 198/204[] 199/204[] 200/204[] 201/204[] 202/204[] 203/204[3/4] Linking dependencies...

[] 204/204[] 0/209[] 0/2918[] 128/2918[] 223/2918[] 256/2918[] 380/2918[] 384/2918[] 473/2918[] 512/2918[] 635/2918[] 640/2918[] 760/2918[] 768/2918[] 884/2918[] 896/2918[] 1012/2918[] 1024/2918[] 1138/2918[] 1152/2918[] 1266/2918[] 1280/2918[] 1394/2918[] 1408/2918[] 1522/2918[] 1536/2918[] 1647/2918[] 1664/2918[] 1775/2918[] 1792/2918[] 1896/2918[] 1920/2918[] 2026/2918[] 2048/2918[] 2152/2918[] 2173/2918[] 2250/2918[] 2300/2918[] 2378/2918[] 2416/2918[] 2504/2918[] 2556/2918[] 2649/2918[] 2681/2918[] 2748/2918[] 2809/2918[] 2918/2918[] 0/385[] 212/385[] 385/385[4/4] Building fresh packages...

success Saved lockfile.

Done in 44.81s.

活动脚本更新完成......

========================2. 检测配置文件========================

检测到config配置目录下不存在crontab.list或存在但文件为空，从示例文件复制一份用于初始化...

'/jd/sample/docker.list.sample' -> '/jd/config/crontab.list'

成功添加定时任务...

检测到config配置目录下不存在config.sh，从示例文件复制一份用于初始化...

'/jd/sample/config.sh.sample' -> '/jd/config/config.sh'

检测到config配置目录下不存在auth.json，从示例文件复制一份用于初始化...

'/jd/sample/auth.json' -> '/jd/config/auth.json'

========================3. 启动挂机程序========================

config.sh中还未填入有效的Cookie，可能是首次部署容器，因此不启动挂机程序...

========================4. 启动控制面板========================

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____

 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___

  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__

   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___

    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____

     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________

      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________

       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_

        _\///______________\///______________\///__\///////////////__

                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications

                     with a built-in Load Balancer.

                Start and Daemonize any application:

                $ pm2 start app.js

                Load Balance 4 instances of api.js:

                $ pm2 start api.js -i 4

                Monitor in production:

                $ pm2 monitor

                Make pm2 auto-boot at server restart:

                $ pm2 startup

                To go further checkout:

                http://pm2.io/

                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2

[PM2] PM2 Successfully daemonized

[PM2] Starting /jd/panel/server.js in fork_mode (1 instance)

[PM2] Done.

┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐

│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤

│ 0   │ server    │ default     │ 1.0.0   │ fork    │ 488      │ 0s     │ 0    │ online    │ 0%       │ 32.2mb   │ root     │ enabled  │

└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

控制面板启动成功...

如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito

请访问 http://<ip>:5678 登陆并修改配置...

容器启动成功......

Welcome to Node.js v14.16.0.

Type ".help" for more information.

![image](https://user-images.githubusercontent.com/37235589/110607572-4c630e80-81c6-11eb-88de-34bfe66c5413.png)
![image](https://user-images.githubusercontent.com/37235589/110607587-4f5dff00-81c6-11eb-9bbf-b752db1d42ce.png)

**Comment by WriteMemory** [comment]
启用gzip压缩之后导致的问题

**Comment by WriteMemory** [comment]
我是进入docker内的 /jd/panel 目录下执行 `yarn --install` 解决的

**Comment by mjyhj** [comment]
> 这很明显是你的网络问题，如果两者之间能连通chrome提示的内容是"访问被拒绝"，如果不能就会提示无法访问 恋上你的温柔℡ hangezhishang@vip.qq.com
> […](#)
> ---原始邮件--- 发件人: "lfscqk67"<notifications@github.com&gt; 发送时间: 2021年3月10日(周三) 下午5:31 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [SuperManito/JD-FreeFuck] 控制面板突然打不开了 (#158) 2. 安装版本 Docker 3. 安装平台 软路由 4. 安装平台架构 arm/v8 5. 安装环境 Docker 7. 问题类型 使用问题 8. 详细叙述您的问题 (1) 具体问题 A：控制面板突然打不开了 (2) 详细的系统日志 注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！ A：/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list... 检测到package.json有变化，运行 npm install... 检测到本机安装了 yarn，使用 yarn 替代 npm... yarn install v1.22.5 info No lockfile found. warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... warning request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142) warning request &gt; har-validator@5.1.5: this library is no longer supported info There appears to be trouble with your network connection. Retrying... [2/4] Fetching packages... [] 0/204[] 4/204[] 6/204[] 7/204[] 9/204[] 13/204[] 14/204[] 15/204[] 16/204[] 19/204[] 20/204[] 22/204[] 25/204[] 26/204[] 29/204[] 32/204[] 34/204[] 37/204[] 42/204[] 44/204[] 45/204[] 49/204[] 50/204[] 52/204[] 53/204[] 55/204[] 56/204[] 58/204[] 60/204[] 62/204[] 64/204[] 66/204[] 67/204[] 70/204[] 72/204[] 73/204[] 74/204[] 77/204[] 79/204[] 81/204[] 82/204[] 85/204[] 88/204[] 89/204[] 93/204[] 95/204[] 96/204[] 98/204[] 100/204[] 105/204[] 107/204[] 109/204[] 111/204[] 112/204[] 113/204[] 114/204[] 116/204[] 118/204[] 119/204[] 122/204[] 124/204[] 125/204[] 127/204[] 128/204[] 130/204[] 131/204[] 132/204[] 133/204[] 134/204[] 136/204[] 138/204[] 140/204[] 142/204[] 143/204[] 144/204[] 145/204[] 147/204[] 148/204[] 149/204[] 151/204[] 152/204[] 153/204[] 154/204[] 156/204[] 158/204[] 160/204[] 161/204[] 164/204[] 165/204[] 166/204[] 168/204[] 169/204[] 170/204[] 172/204[] 174/204[] 175/204[] 177/204[] 178/204[] 179/204[] 180/204[] 182/204[] 184/204[] 185/204[] 187/204[] 188/204[] 190/204[] 191/204[] 192/204[] 193/204[] 195/204[] 196/204[] 197/204[] 198/204[] 199/204[] 200/204[] 201/204[] 202/204[] 203/204[3/4] Linking dependencies... [] 204/204[] 0/209[] 0/2918[] 128/2918[] 223/2918[] 256/2918[] 380/2918[] 384/2918[] 473/2918[] 512/2918[] 635/2918[] 640/2918[] 760/2918[] 768/2918[] 884/2918[] 896/2918[] 1012/2918[] 1024/2918[] 1138/2918[] 1152/2918[] 1266/2918[] 1280/2918[] 1394/2918[] 1408/2918[] 1522/2918[] 1536/2918[] 1647/2918[] 1664/2918[] 1775/2918[] 1792/2918[] 1896/2918[] 1920/2918[] 2026/2918[] 2048/2918[] 2152/2918[] 2173/2918[] 2250/2918[] 2300/2918[] 2378/2918[] 2416/2918[] 2504/2918[] 2556/2918[] 2649/2918[] 2681/2918[] 2748/2918[] 2809/2918[] 2918/2918[] 0/385[] 212/385[] 385/385[4/4] Building fresh packages... success Saved lockfile. Done in 44.81s. 活动脚本更新完成...... ========================2. 检测配置文件======================== 检测到config配置目录下不存在crontab.list或存在但文件为空，从示例文件复制一份用于初始化... '/jd/sample/docker.list.sample' -&gt; '/jd/config/crontab.list' 成功添加定时任务... 检测到config配置目录下不存在config.sh，从示例文件复制一份用于初始化... '/jd/sample/config.sh.sample' -&gt; '/jd/config/config.sh' 检测到config配置目录下不存在auth.json，从示例文件复制一份用于初始化... '/jd/sample/auth.json' -&gt; '/jd/config/auth.json' ========================3. 启动挂机程序======================== config.sh中还未填入有效的Cookie，可能是首次部署容器，因此不启动挂机程序... ========================4. 启动控制面板======================== ------------- /\\\\\\_/\\___/\\/\\\\_ _/\/////////\_/\\\____/\\\/\///////\_ /\_/\_/\//\_/\//\_///___//\_ /\\\\\\/__/\\///\/\//\________/\/ _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____ _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________ _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________ _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_ _\///______________\///______________\///__\///////////////__ Runtime Edition PM2 is a Production Process Manager for Node.js applications with a built-in Load Balancer. Start and Daemonize any application: $ pm2 start app.js Load Balance 4 instances of api.js: $ pm2 start api.js -i 4 Monitor in production: $ pm2 monitor Make pm2 auto-boot at server restart: $ pm2 startup To go further checkout: http://pm2.io/ ------------- [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2 [PM2] PM2 Successfully daemonized [PM2] Starting /jd/panel/server.js in fork_mode (1 instance) [PM2] Done. ┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐ │ id │ name │ namespace │ version │ mode │ pid │ uptime │ ↺ │ status │ cpu │ mem │ user │ watching │ ├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤ │ 0 │ server │ default │ 1.0.0 │ fork │ 488 │ 0s │ 0 │ online │ 0% │ 32.2mb │ root │ enabled │ └─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘ 控制面板启动成功... 如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito 请访问 http://:5678 登陆并修改配置... 容器启动成功...... Welcome to Node.js v14.16.0. Type ".help" for more information. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大量用户下午gitpull后，web就进不去

**Comment by WriteMemory** [comment]
> > 这很明显是你的网络问题，如果两者之间能连通chrome提示的内容是"访问被拒绝"，如果不能就会提示无法访问 恋上你的温柔℡ [hangezhishang@vip.qq.com](mailto:hangezhishang@vip.qq.com)
> > […](#)
> > ---原始邮件--- 发件人: "lfscqk67"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2021年3月10日(周三) 下午5:31 收件人: "SuperManito/JD-FreeFuck"<[JD-FreeFuck@noreply.github.com](mailto:JD-FreeFuck@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [SuperManito/JD-FreeFuck] 控制面板突然打不开了 (#158) 2. 安装版本 Docker 3. 安装平台 软路由 4. 安装平台架构 arm/v8 5. 安装环境 Docker 7. 问题类型 使用问题 8. 详细叙述您的问题 (1) 具体问题 A：控制面板突然打不开了 (2) 详细的系统日志 注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！ A：/jd/config/crontab.list 文件不存在，请先定义您自己的crontab.list... 检测到package.json有变化，运行 npm install... 检测到本机安装了 yarn，使用 yarn 替代 npm... yarn install v1.22.5 info No lockfile found. warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... warning request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142) warning request > har-validator@5.1.5: this library is no longer supported info There appears to be trouble with your network connection. Retrying... [2/4] Fetching packages... [] 0/204[] 4/204[] 6/204[] 7/204[] 9/204[] 13/204[] 14/204[] 15/204[] 16/204[] 19/204[] 20/204[] 22/204[] 25/204[] 26/204[] 29/204[] 32/204[] 34/204[] 37/204[] 42/204[] 44/204[] 45/204[] 49/204[] 50/204[] 52/204[] 53/204[] 55/204[] 56/204[] 58/204[] 60/204[] 62/204[] 64/204[] 66/204[] 67/204[] 70/204[] 72/204[] 73/204[] 74/204[] 77/204[] 79/204[] 81/204[] 82/204[] 85/204[] 88/204[] 89/204[] 93/204[] 95/204[] 96/204[] 98/204[] 100/204[] 105/204[] 107/204[] 109/204[] 111/204[] 112/204[] 113/204[] 114/204[] 116/204[] 118/204[] 119/204[] 122/204[] 124/204[] 125/204[] 127/204[] 128/204[] 130/204[] 131/204[] 132/204[] 133/204[] 134/204[] 136/204[] 138/204[] 140/204[] 142/204[] 143/204[] 144/204[] 145/204[] 147/204[] 148/204[] 149/204[] 151/204[] 152/204[] 153/204[] 154/204[] 156/204[] 158/204[] 160/204[] 161/204[] 164/204[] 165/204[] 166/204[] 168/204[] 169/204[] 170/204[] 172/204[] 174/204[] 175/204[] 177/204[] 178/204[] 179/204[] 180/204[] 182/204[] 184/204[] 185/204[] 187/204[] 188/204[] 190/204[] 191/204[] 192/204[] 193/204[] 195/204[] 196/204[] 197/204[] 198/204[] 199/204[] 200/204[] 201/204[] 202/204[] 203/204[3/4] Linking dependencies... [] 204/204[] 0/209[] 0/2918[] 128/2918[] 223/2918[] 256/2918[] 380/2918[] 384/2918[] 473/2918[] 512/2918[] 635/2918[] 640/2918[] 760/2918[] 768/2918[] 884/2918[] 896/2918[] 1012/2918[] 1024/2918[] 1138/2918[] 1152/2918[] 1266/2918[] 1280/2918[] 1394/2918[] 1408/2918[] 1522/2918[] 1536/2918[] 1647/2918[] 1664/2918[] 1775/2918[] 1792/2918[] 1896/2918[] 1920/2918[] 2026/2918[] 2048/2918[] 2152/2918[] 2173/2918[] 2250/2918[] 2300/2918[] 2378/2918[] 2416/2918[] 2504/2918[] 2556/2918[] 2649/2918[] 2681/2918[] 2748/2918[] 2809/2918[] 2918/2918[] 0/385[] 212/385[] 385/385[4/4] Building fresh packages... success Saved lockfile. Done in 44.81s. 活动脚本更新完成...... ========================2. 检测配置文件======================== 检测到config配置目录下不存在crontab.list或存在但文件为空，从示例文件复制一份用于初始化... '/jd/sample/docker.list.sample' -> '/jd/config/crontab.list' 成功添加定时任务... 检测到config配置目录下不存在config.sh，从示例文件复制一份用于初始化... '/jd/sample/config.sh.sample' -> '/jd/config/config.sh' 检测到config配置目录下不存在auth.json，从示例文件复制一份用于初始化... '/jd/sample/auth.json' -> '/jd/config/auth.json' ========================3. 启动挂机程序======================== config.sh中还未填入有效的Cookie，可能是首次部署容器，因此不启动挂机程序... ========================4. 启动控制面板======================== ------------- /\\\_/\___/\/\\_ _//////////_/\____/\////////_ /_/_///_///_///_**//_ /\\\/**/\//////__**__**// _/\/////////_**_/\__///\/**_/\__******/\//_____ _/\__******___**/\_**_///_****/\_____/\//****____ _/\___**********/\_**********__/\___/\/___________ _/\___**********/\_**********__/\__/\\\\\\\_ _///**************///**************///**///////////////** Runtime Edition PM2 is a Production Process Manager for Node.js applications with a built-in Load Balancer. Start and Daemonize any application: $ pm2 start app.js Load Balance 4 instances of api.js: $ pm2 start api.js -i 4 Monitor in production: $ pm2 monitor Make pm2 auto-boot at server restart: $ pm2 startup To go further checkout: http://pm2.io/ ------------- [PM2] Spawning PM2 daemon with pm2_home=/root/.pm2 [PM2] PM2 Successfully daemonized [PM2] Starting /jd/panel/server.js in fork_mode (1 instance) [PM2] Done. ┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐ │ id │ name │ namespace │ version │ mode │ pid │ uptime │ ↺ │ status │ cpu │ mem │ user │ watching │ ├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤ │ 0 │ server │ default │ 1.0.0 │ fork │ 488 │ 0s │ 0 │ online │ 0% │ 32.2mb │ root │ enabled │ └─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘ 控制面板启动成功... 如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito 请访问 http://:5678 登陆并修改配置... 容器启动成功...... Welcome to Node.js v14.16.0. Type ".help" for more information. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 大量用户下午gitpull后，web就进不去
docker用户只需要执行一下`sudo docker exec jd yarn --cwd /jd/panel --install`命令即可
