### ISSUE TITLE
大佬脚本不能用了

### ISSUE THREAD

**Issue by mohanfeng3** [SuperManito/JD-FreeFuck#16]
已安装:
  dos2unix.x86_64 0:6.0.3-7.el7

完毕！
dos2unix: /opt/jd/run-all.sh: 没有那个文件或目录
dos2unix: Skipping /opt/jd/run-all.sh, not a regular file.
dos2unix: /opt/jd/manual-update.sh: 没有那个文件或目录
dos2unix: Skipping /opt/jd/manual-update.sh, not a regular file.
bash: /opt/jd/manual-update.sh: 没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
sed：无法读取 /opt/jd/config/config.sh：没有那个文件或目录
 -------------- 一键部署失败 --------------

**Comment by mohanfeng3** [comment]
中间有这个报错，小白看不懂
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/61/617279a5c63ccbb630afe061961d70f3cb80ca8c558636affc1e55c7b84dfdcb/data?verify=1612173383-EULKJ5ie3lPOiFKBZ90x3zoeaG8%3D: net/http: TLS handshake timeout
Unable to find image 'evinedeng/jd:gitee' locally
gitee: Pulling from evinedeng/jd
0a6724ff3fcd: Pulling fs layer
7ceedf9dd120: Pulling fs layer

**Comment by SuperManito** [comment]
> 中间有这个报错，小白看不懂
> error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/61/617279a5c63ccbb630afe061961d70f3cb80ca8c558636affc1e55c7b84dfdcb/data?verify=1612173383-EULKJ5ie3lPOiFKBZ90x3zoeaG8%3D: net/http: TLS handshake timeout
> Unable to find image 'evinedeng/jd:gitee' locally
> gitee: Pulling from evinedeng/jd
> 0a6724ff3fcd: Pulling fs layer
> 7ceedf9dd120: Pulling fs layer

这不是我的脚本不能用了，这是原作者的镜像没下载成功，你再部署一次试试

**Comment by SuperManito** [comment]
> 中间有这个报错，小白看不懂
> error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/61/617279a5c63ccbb630afe061961d70f3cb80ca8c558636affc1e55c7b84dfdcb/data?verify=1612173383-EULKJ5ie3lPOiFKBZ90x3zoeaG8%3D: net/http: TLS handshake timeout
> Unable to find image 'evinedeng/jd:gitee' locally
> gitee: Pulling from evinedeng/jd
> 0a6724ff3fcd: Pulling fs layer
> 7ceedf9dd120: Pulling fs layer

而且你这个报错不对啊，我脚边里配置了阿里云加速，你这个docker仓库用的是Cloudflare的啊，没用我的脚本？

**Comment by xy364515640** [comment]
https://mirrors.bfsu.edu.cn/help/docker-ce/  建议删除你的docker，用这个再重新部署，拉取满速

**Comment by mohanfeng3** [comment]
我的系统是centos7，昨天还是前天你刚更新完用着很正常，今个部署就出问题了，用的你的脚本照着步骤一步步来的，我现在再下载centos8.3试试

**Comment by SuperManito** [comment]
> 我的系统是centos7，昨天还是前天你刚更新完用着很正常，今个部署就出问题了，用的你的脚本照着步骤一步步来的，我现在再下载centos8.3试试

CentOS7容器装完用不了，我测试过，但不是你这个下载问题，原因未知，我早就在支持的系统那里改了

**Comment by mohanfeng3** [comment]
好的，我装好centos8之后试试，昨天centos7确实可以，我手欠不知道改了啥，今个就一直装不上了，我等下装好8之后试试

**Comment by SuperManito** [comment]
> https://mirrors.bfsu.edu.cn/help/docker-ce/ 建议删除你的docker，用这个再重新部署，拉取满速

你这个是Docker-CE，他下报错对应的是DockerHub源，国内镜像仓库加速不是所有都能用，我之前测试了中科大的，那个更快，但是下载的是旧版本，用其它国内镜像仓库加速下载完注意看一下容器创建时间，对照[evinedeng/jd](https://hub.docker.com/r/evinedeng/jd)，他这个下载报错用的CloudFlare的镜像仓库

**Comment by SuperManito** [comment]
> 好的，我装好centos8之后试试，昨天centos7确实可以，我手欠不知道改了啥，今个就一直装不上了，我等下装好8之后试试

他说的不对，你这个是DockerHub的问题，我在脚本里配置了国内镜像仓库加速（阿里云），我不知道你到底有没有用我的一键部署脚本，在daemon.json那个文件换成阿里云的

**Comment by mohanfeng3** [comment]
装好系统就做了以下几步
第一步
echo "199.232.96.133 raw.githubusercontent.com" >> /etc/hosts
echo "151.101.88.133 raw.githubusercontent.com" >> /etc/hosts
第二步
bash <(curl -sL https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
回车后过会要选个源，我试过第一个，第二个，第三个，好像是中科大，阿里云
然后就各种下载了，中间就有这些错误，最后提示部署失败

**Comment by SuperManito** [comment]
> 装好系统就做了以下几步
> 第一步
> echo "199.232.96.133 raw.githubusercontent.com" >> /etc/hosts
> echo "151.101.88.133 raw.githubusercontent.com" >> /etc/hosts
> 第二步
> bash <(curl -sL https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
> 回车后过会要选个源，我试过第一个，第二个，第三个，好像是中科大，阿里云
> 然后就各种下载了，中间就有这些错误，最后提示部署失败

那个是Linux的更新源，跟docker的不是一回事

**Comment by sd462355991111** [comment]
可能是网络的问题，我刚才也是怎么装都不行，装了几遍成功了

**Comment by SuperManito** [comment]
> 可能是网络的问题，我刚才也是怎么装都不行，装了几遍成功了

本来就是下载镜像出现了问题，我的脚本没有问题的，该换的国内源都换了

**Comment by mohanfeng3** [comment]
多谢大佬，已经搞定了，应该是网络问题，我仔细观察了一下，前几次报错是这一步的时候第1，4，5文件下载不下来，现在已经好了，多谢大佬
gitee: Pulling from evinedeng/jd
0a6724ff3fcd: Pull complete
7ceedf9dd120: Pull complete
ce91790a06ab: Pull complete
15917197957b: Pull complete
826049a1d480: Pull complete
