### ISSUE TITLE
东东农场: API查询请求失败

### ISSUE THREAD

**Issue by 457992195** [SuperManito/JD-FreeFuck#160]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：centos 8.3

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：东东农场: API查询请求失败

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

🔔东东农场, 开始!
开始获取配置文件

您的cookie选择的是用&隔开

====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/3/10 下午6:05:19=====================

您的东东农场互助码选择的是用&隔开

共3个京东账号

您提供了3个账号的农场助力码

开始【京东账号1】122292195-513519

随机取个20码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["f7949e009c9042eeb8bfddc957e123e2","0005030858d94da1957b489bef3bb5b9","fd0d45e3e00a4ad6a16ba5c3fe218185","3b4ec87e1c3846409d98beb970d24953","0216cac6f18b42a68808990420767bd6","fb0e309813c543c38ead8c9d0df13685","f4f3453fde674b14be234bdce7f9a461","dd8b8158db764898a33361a0979ac382","ceaeb825818343ce96ece24df39f7dd4","a1bc1602151a42d68fb8cf0ee93cc43d","8929d5a2b9ba479a85c750743485ae21","0f790f847da34e4ebfcd402816914a7c","a6b6fc3da5734f969142d0e435bb313d","ec221d0496104d6f9044ef58334dfd84","47a5b8a73f0d47e993ee80b800cdc865","4c874bf340144cd486044dd670e80776","e2344a64091c41efb8d40078ecc68951","d2ba8aede0cd495d93f8bfde6eaf70cf","c557c7086d8b42b5b3a9ae6015f24621","be17cffb51b7479a92d633e843731039","d1774087b1c94bddae0069b219f822fa","df235e3315ed4d61819485f7b58d5b34"]

东东农场: API查询请求失败 ‼️‼️
"read ECONNRESET"

❗️东东农场, 错误!

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read property 'farmUserPro' of undefined
    at jdFruit (/opt/jd/scripts/jd_fruit.js:88:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/jd/scripts/jd_fruit.js:71:7

==============📣系统通知📣==============
东东农场
【京东账号1】122292195-513519
任务执行异常，请检查执行日志 ‼️‼️

开始【京东账号2】xuwei89757

随机取个20码放到您固定的互助码后面(不影响已有固定互助)
第2个京东账号将要助力的好友["84685910a767417fb789e5cfc06bb91d","0005030858d94da1957b489bef3bb5b9","b55d2089d4d64a348a9ade167d8e88dc","879f1300f8c848d484189f277ffa4b42","3b150505f6594dceb02429240818711b","8e8e57611f6d435da3a6c6c7b178e772","5163a7f53aed491794f07ef215d4bf03","0ed6bf52dc6c4a2eb5a00bbaae3d68a8","9884a82b5f114b12bb5e3e4d451c672b","5173f97595cd43cc91df8a1056753af9","5aaa81b0868d4cbf9e4c851164837337","bf50fd10bf5649bdad5d778e9a118640","8fd0df716c2e46a89dafda600fc3384d","f7234848650a4a4287909209c182a6c9","3a8edead147f4cd2babf6b0eddb6e2e5","8c368d9077984775a2e0b94c67cb85de","14fc12445c1b4bb2bbdb67a121f8ebe3","52c882f3c2de48018be9e610a745ea57","2751cea2029b488790b98cae9d8a8485","133016d829c34789a512454c6ed6e16e","f1d55287c56247be8111c9350285add0","c842b2c8368840c5ba7c8da72740e981"]

东东农场: API查询请求失败 ‼️‼️
"read ECONNRESET"

❗️东东农场, 错误!

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read property 'farmUserPro' of undefined
    at jdFruit (/opt/jd/scripts/jd_fruit.js:88:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/jd/scripts/jd_fruit.js:71:7

==============📣系统通知📣==============
东东农场
【京东账号2】xuwei89757
任务执行异常，请检查执行日志 ‼️‼️

开始【京东账号3】西北犊狼

第3个京东账号将要助力的好友["84685910a767417fb789e5cfc06bb91d","f7949e009c9042eeb8bfddc957e123e2"]

【京东账号3（西北犊狼）的东东农场好友互助码】0005030858d94da1957b489bef3bb5b9

【已成功兑换水果】2次

开始助力好友
格式化后的助力码::["84685910a767417fb789e5cfc06bb91d","f7949e009c9042eeb8bfddc957e123e2"]

开始助力京东账号3 - 西北犊狼的好友: 84685910a767417fb789e5cfc06bb91d
随机取个20码放到您固定的互助码后面(不影响已有固定互助)
【助力好友结果】: 之前给【境界上的地平线】助力过了
【今日助力次数还剩】1次

开始助力京东账号3 - 西北犊狼的好友: f7949e009c9042eeb8bfddc957e123e2
【助力好友结果】: 之前给【jd_xj815】助力过了
【今日助力次数还剩】1次

助力好友结束，即将开始领取额外水滴奖励

3盒龙虾尾种植中...

初始化任务列表
开始签到
今天已签到,连续签到5,下次签到可得25g

被水滴砸中： 否
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

【定时领水】获得12g💧

今日已邀请好友0个 / 每日邀请上限4个
开始删除1个好友,可拿每天的邀请奖励

开始删除好友 [04719d98f6cb4b1299e81d62f894df56]

东东农场: API查询请求失败 ‼️‼️
"read ECONNRESET"
function_id:deleteFriendForFarm

❗️东东农场, 错误!

接收邀请成为好友结果失败,对方已是您的好友
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
领券的ID9801453995
venderCouponStep1--结果{"followState":"F0402","code":"0","couponInfo":{"couponId":"156451812149","batchId":773725934,"type":1,"style":0,"beginTime":1614873600000,"endTime":1617206399000,"discount":15,"quota":31},"todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"sysTime":1615370755478,"couponResultCode":200,"message":null,"limitStr":"仅可购买十月稻田部分商品"}
venderCouponStep2--结果{"amount":2,"code":"0","todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"sysTime":1615370756635,"message":null}
从十月稻田京东自营旗舰店领券，获得水滴2g
开始打卡领水活动（签到，关注，领券）结束

水滴雨任务，每天两次，最多可得10g水滴
两次水滴雨任务是否全部完成：否
开始水滴雨任务,这是第1次，剩余1次
水滴雨waterRain
水滴雨任务执行成功，获得水滴：10g
【第1次水滴雨】获得10g水滴

助力好友未达到5个

京东昵称【境界上的地平线】 在 2021-3-10 6:9:9 给您助过力

京东昵称【jd_xj815】 在 2021-3-10 6:10:10 给您助过力

领取额外奖励水滴结束

是否到了领取免费赠送的抽奖机会----false
免费赠送的抽奖机会未到时间
开始浏览天天抽奖的第1个逛会场任务
浏览爆品会场
第1个逛会场任务完成，开始领取水滴奖励

天天抽奖浏览任务领取水滴
第1个逛会场任务领取水滴奖励完成

开始天天抽奖--好友助力--每人每天只有三次助力机会.
天天抽奖-助力境界上的地平线成功

天天抽奖-助力jd_xj815成功

---天天抽奖次数remainLotteryTimes----4次
开始抽奖
等待了2秒
第1次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1615370772316,"addWater":10,"message":null,"type":"water1","remainLotteryTimes":3}
lotteryRes.typewater1
等待了2秒
第2次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1615370778707,"message":null,"type":"thanks","remainLotteryTimes":2}
lotteryRes.typethanks
等待了2秒
第3次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1615370785055,"addWater":10,"message":null,"type":"water1","remainLotteryTimes":1}
lotteryRes.typewater1
等待了2秒
第4次抽奖结果{"code":"0","statisticsTimes":null,"sysTime":1615370788229,"addWater":10,"message":null,"type":"water1","remainLotteryTimes":0}
lotteryRes.typewater1
【天天抽奖】水滴10g，谢谢参与，水滴10g，水滴10g

今日已完成10次浇水任务

初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
领取给2个好友浇水后的奖励水滴::{"code":"0","statisticsTimes":null,"sysTime":1615370794138,"addWater":25,"message":null}
【给2好友浇水】奖励25g水滴

东东农场: API查询请求失败 ‼️‼️
"read ECONNRESET"

❗️东东农场, 错误!

任务执行异常，请检查执行日志 ‼️‼️

❗️东东农场, 错误!
TypeError: Cannot read property 'code' of undefined
    at duck (/opt/jd/scripts/jd_fruit.js:917:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async jdFruit (/opt/jd/scripts/jd_fruit.js:118:7)
    at async /opt/jd/scripts/jd_fruit.js:71:7

==============📣系统通知📣==============
东东农场
【京东账号3】西北犊狼
任务执行异常，请检查执行日志 ‼️‼️
您未提供server酱的SCKEY，取消微信推送消息通知

push+发送一对多通知消息完成。

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知

您未提供企业微信机器人推送所需的QYWX_KEY，取消企业微信推送消息通知

您未提供企业微信应用消息推送所需的QYWX_AM，取消企业微信应用消息推送消息通知

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

🔔东东农场, 结束! 🕛 75.103 秒

**Comment by SuperManito** [comment]
如果你在APP里进不去这个活动的话那就是黑号了
