### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by KevinZjYang** [SuperManito/JD-FreeFuck#161]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.9

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：无法更新”git_pull.sh",阿里云香港服务器，不应该啊。尝试了多次。
![image](https://user-images.githubusercontent.com/31529584/110640993-6d3e5a80-81ec-11eb-9152-b2ca7f34e5b9.png)

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
你试试你在浏览器能访问码云吗

**Comment by KevinZjYang** [comment]
> 你试试你在浏览器能访问码云吗

可以，这个服务器在香港，和我本地没关系吧。

**Comment by SuperManito** [comment]
> > 你试试你在浏览器能访问码云吗
> 
> 可以，这个服务器在香港，和我本地没关系吧。

当然没有关系

**Comment by KevinZjYang** [comment]
> > > 你试试你在浏览器能访问码云吗
> > 
> > 
> > 可以，这个服务器在香港，和我本地没关系吧。
> 
> 当然没有关系

今天我重装的时候就部署了很多次才成功，每次拉取代码就很慢。

**Comment by SuperManito** [comment]
拉我的项目还是拉lxk的活动脚本都是走的gitee，如果你访问不了Gitee那就自己解决吧

**Comment by KevinZjYang** [comment]
明白了，服务器确实丢包严重
