### ISSUE TITLE
为什么定时功能没有运行？

### ISSUE THREAD

**Issue by haowen2000** [SuperManito/JD-FreeFuck#163]
昨天早上开始挂机，全部脚本自动运行完后，就开始crayjoy挂机，

今天早上来看log，并没有定时运行其他脚本，一直在挂机，

是需要还修改什么地方吗？

**Comment by leic4u** [comment]
用一键全部运行的脚本是前台挂机，会一直占用资源，运行到挂机脚本的时候要`ctrl+c`结束一下前台挂机，要一直挂机的话需要执行一下专门的后台挂机脚本
docker版用 `docker exec -it jd bash jd.sh hangup`
linux版用 `bash jd.sh hangup`

**Comment by SuperManito** [comment]
> 昨天早上开始挂机，全部脚本自动运行完后，就开始crayjoy挂机，
> 
> 今天早上来看log，并没有定时运行其他脚本，一直在挂机，
> 
> 是需要还修改什么地方吗？



> 昨天早上开始挂机，全部脚本自动运行完后，就开始crayjoy挂机，
> 
> 今天早上来看log，并没有定时运行其他脚本，一直在挂机，
> 
> 是需要还修改什么地方吗？

定时没有问题，去读《使用须知》

**Comment by qin369** [comment]
> 昨天早上开始挂机，全部脚本自动运行完后，就开始crayjoy挂机，
> 
> 今天早上来看log，并没有定时运行其他脚本，一直在挂机，
> 
> 是需要还修改什么地方吗？

你好，请问你解决了吗？我这边也是脚本不会定时运行。
