### ISSUE TITLE
扫码后不会自动填cookie

### ISSUE THREAD

**Issue by ywcd** [SuperManito/JD-FreeFuck#164]
rt  刚刚今天早上拉取的新镜像

**Comment by ericli911** [comment]
这提示我也看到了，原来也不会自动填吧？发自我的华为手机-------- 原始邮件 --------发件人： OxO <notifications@github.com>日期： 2021年3月11日周四 11:40收件人： SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [SuperManito/JD-FreeFuck] 扫码后不会自动填cookie (#164)

rt  刚刚今天早上拉取的新镜像

**Comment by SuperManito** [comment]
此功能还在开发中
