### ISSUE TITLE
docker命令

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#166]
启动容器：
docker run -dit \
-v /opt/jd/scripts:/jd/scripts `# 设置活动脚本的主机挂载目录为/opt/jd/scripts` \
-v /opt/jd/config:/jd/config `# 设置配置文件的主机挂载目录为/opt/jd/config` \
-v /opt/jd/log:/jd/log `# 设置日志的主机挂载目录为/opt/jd/log` \
-p 5678:5678 `# 设置端口映射，格式为 "主机端口:容器端口"，主机端口号可自定义` \
-e ENABLE_HANGUP=true `# 启用挂机功能` \
-e ENABLE_WEB_PANEL=true `# 启用控制面板功能` \
--name jd `# 设置容器名为jd` \
--network bridge `# 设置网络为桥接，直连主机` \
--hostname jd `# 设置主机名为jd` \
--restart always `# 设置容器开机自启` \
registry.cn-hangzhou.aliyuncs.com/supermanito/jd

哪些指令需要？
比如-v /opt/jd/scripts:/jd/scripts `   是要的？

井符号设置活动脚本的主机挂载目录为/opt/jd/scripts` \   不要
理解没错吧！

**Comment by SuperManito** [comment]
你为什么要自作聪明呢？
