### ISSUE TITLE
如果能支持termux就好了

### ISSUE THREAD

**Issue by zzgpku** [SuperManito/JD-FreeFuck#167]
termux不让用root，如果能支持termux就好了，没有vps，用电脑也不太方便

**Comment by SuperManito** [comment]
我都不知道那是个啥。。项目里一直留有它的配置文件和变量

**Comment by hacken156026692** [comment]
> 我都不知道那是个啥。。项目里一直留有它的配置文件和变量

就是个安卓的终端执行器（以前Evinedeng几个办法里有安卓本地的教程），我一直也用termux，想用您的脚本，结果一方面是root问题（还好我有，能tsu），另一方面安装文件路径不一样，我把/root/ssh的安装路径都改成了termux的/home的，还是不行。

**Comment by SuperManito** [comment]
不会去开发那个平台，维护不过来

**Comment by kingsleyzhnlanf** [comment]
> 我都不知道那是个啥。。项目里一直留有它的配置文件和变量

安卓的linux软件

**Comment by SuperManito** [comment]
> > 我都不知道那是个啥。。项目里一直留有它的配置文件和变量
> 
> 安卓的linux软件

后来知道了，没精力去适配
