### ISSUE TITLE
DIY脚本"jd_entertainment.js"获取错误

### ISSUE THREAD

**Issue by WriteMemory** [SuperManito/JD-FreeFuck#168]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：Docker version 20.10.5, build 55c4c88966

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
[https://gitee.com/SuperManito/scripts/raw/master/jd_entertainment.js](https://gitee.com/SuperManito/scripts/raw/master/jd_entertainment.js)
[https://gitee.com/SuperManito/scripts/blob/master/jd_entertainment.js](https://gitee.com/SuperManito/scripts/blob/master/jd_entertainment.js)
该脚本无法从gitee的web页获取，返回：
`根据相关法律政策,该内容无法显示`
已手动将仓库手动clone下来进行替换

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
N/A

**Comment by WriteMemory** [comment]
> 这么快就有人发现了。。。明天就好了，我传上去的时候码云的客服下班了

我这是第一次打开DIY脚本就挂了

**Comment by SuperManito** [comment]
明天就好了，不用管。。。
