### ISSUE TITLE
可能存在的偶现异常高占用BUG，RAM达900MB

### ISSUE THREAD

**Issue by luoli8** [SuperManito/JD-FreeFuck#169]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [x] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：最新版本

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：3月12的凌晨12:20左右发生
未发生操作，群晖内独JD-FreeFuckRAM占用900MB左右
机器为群晖，1G内存条，双核四线程
[https://i.loli.net/2021/03/12/o1xwkFteX7qZiAN.png](https://i.loli.net/2021/03/12/o1xwkFteX7qZiAN.png)
[https://i.loli.net/2021/03/12/ahBdMklImNAWPJT.png](https://i.loli.net/2021/03/12/ahBdMklImNAWPJT.png)
[https://i.loli.net/2021/03/12/KYJcRB6eIkSp3fx.png](https://i.loli.net/2021/03/12/KYJcRB6eIkSp3fx.png)
容器为当天删除配置从新部署的，查看日志未见任何异常日志，凌晨12：36分机器自行恢复正常
这个时间段正好是多合一什么的脚本运行阶段！
那大概率是正常运行所需的内存，不过那也太高了，影响其他任务了，如果是看来我需要增加一根内存条了。
如果不是，那就有可能是我机器内存运行错误导致，也可能是代码存在问题（其他人不存在就是我个人机器问题了）。
### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
[https://i.loli.net/2021/03/12/I6RZmrUNwFycOV5.png](https://i.loli.net/2021/03/12/I6RZmrUNwFycOV5.png)

**Comment by SuperManito** [comment]
不清楚，你手动跑一下那个脚本看一下占用不就知道了

**Comment by luoli8** [comment]
> 不清楚，你手动跑一下那个脚本看一下占用不就知道了

这个是原作者的一些脚本问题估计joy，不是你的这个镜像的问题，算了我也不去反馈了，省着碰一鼻子灰

**Comment by SuperManito** [comment]
> > 不清楚，你手动跑一下那个脚本看一下占用不就知道了
> 
> 这个是原作者的一些脚本问题估计joy，不是你的这个镜像的问题，算了我也不去反馈了，省着碰一鼻子灰

lxk发通知了
