### ISSUE TITLE
新版本活动可以更新吗？

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#17]
因为我在用老版本，
新版本活动可以更新吗？要是可以，我就弄新的？
望告知，谢谢

**Comment by SuperManito** [comment]
> 因为我在用老版本，
> 新版本活动可以更新吗？要是可以，我就弄新的？
> 望告知，谢谢

肯定可以啊，原作者在维护的，基于Docker，不然我为什么换呢

**Comment by sd462355991111** [comment]
> > 因为我在用老版本，
> > 新版本活动可以更新吗？要是可以，我就弄新的？
> > 望告知，谢谢
> 
> 肯定可以啊，原作者在维护的，基于Docker，不然我为什么换呢

喔，谢谢
