### ISSUE TITLE
无法关闭挂机程序

### ISSUE THREAD

**Issue by baiye233** [SuperManito/JD-FreeFuck#171]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [x] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：Debian 9 x86_64

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：在控制面板中，手动执行“ 运行挂机活动”后，无法关闭挂机程序，后台会一直在运行，最后重启VPS才关闭。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
不看教程的么?控制面板也有功能键啊












恋上你的温柔℡
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日(周五) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SuperManito/JD-FreeFuck] 无法关闭挂机程序 (#171)




 
1. 关于您要提交的问题
 
Q：是否阅读并已接受《特别声明》与《项目声明》
  
 是 

 否 
 
Q：是否仔细阅读了《前言》
  
 是 

 否 
 
Q：是否仔细阅读了《部署前需知与准备工作》
  
 是 

 否 
 
Q：是否仔细阅读了《常见问题与帮助》
  
 是 

 否 
 
Q：是否仔细阅读了《使用需知》
  
 是 

 否 
 
2. 安装版本
  
 Linux 

 Docker 
 
3. 安装平台
  
 PC 

 VPS 

 软路由 

 NAS 

 Other 
 
4. 安装平台架构
  
 amd64 x86-64 x86-32 

 arm64 aarch64 arm/v8 arm/v7 arm/v6 

 ppc64le s390x 

 Other 
 
5. 安装环境
  
 Ubuntu 

 Debian 

 CentOS 

 Fedora 

 Docker 

 Other 
 
6. 安装环境版本
 
A：Debian 9 x86_64
 
7. 问题类型
  
 部署问题 

 使用问题 
 
8. 详细叙述您的问题
 
(1) 具体问题
 
A：在控制面板中，手动执行“ 运行挂机活动”后，无法关闭挂机程序，后台会一直在运行，最后重启VPS才关闭。
 
(2) 详细的系统日志
 
注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！
 
A：

**Comment by baiye233** [comment]
“启动/重启后台挂机程序”  “ 停止后台挂机程序”  这2个试过了，关闭不了。
还有哪个按键能关闭的吗，请大佬指教一下

**Comment by baiye233** [comment]
我在面板开启的不是后台挂机程序，是运行挂机活动
