### ISSUE TITLE
更新了11号的版本，重启面板后，控制面板进不了

### ISSUE THREAD

**Issue by binhe-cpu** [SuperManito/JD-FreeFuck#172]
更新了11号的版本，重启面板后，控制面板进不了

**Comment by baiye233** [comment]
我之前也是这样，后来关闭面板后更新就没用这个问题了

**Comment by binhe-cpu** [comment]
好的，我试试

**Comment by binhe-cpu** [comment]
> 我之前也是这样，后来关闭面板后更新就没用这个问题了

按你的方法，正常了，谢谢了

**Comment by zwd2zwd** [comment]
怎么关闭面板，是重新安装吗？

**Comment by ericli911** [comment]
可以参考作者写的教程，写的很详细

**Comment by haowen2000** [comment]
控制面版的安装脚本有问题

**Comment by SuperManito** [comment]
@zwd2zwd @ericli911 @baiye233 @haowen2000 @binhe-cpu 哪来这么多问题啊，控制面板没问题，不好好看通知也不好好看教程用不了怪谁啊
