### ISSUE TITLE
Linux版卸载命令错误

### ISSUE THREAD

**Issue by KevinZjYang** [SuperManito/JD-FreeFuck#176]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.9

## 7. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：
Linux 版本
停止控制面板与后台挂机程序的运行：

pm2 stop /opt/jd/panel/ecosystem.config.js
pm2 stop crazy_joy_coin

应该是“pm2 stop jd_crazy_joy_coin”

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
ok
