### ISSUE TITLE
总不能更新脚本，为什么？单臂路由，N1，F大固件

### ISSUE THREAD

**Issue by shenzt68** [SuperManito/JD-FreeFuck#178]
更新 JD-FreeFuck 项目脚本：

Fetching origin
fatal: unable to access 'https://gitee.com/SuperManito/JD-FreeFuck.git/': Failed to connect to gitee.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at af2f208 Update run.html

克隆 lxk0301 活动脚本：

Cloning into '/jd/scripts'...
ssh: connect to host gitee.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by SuperManito** [comment]
未按模板发 Issues 一律关闭
