### ISSUE TITLE
关于爱快的Docker怎么安装？

### ISSUE THREAD

**Issue by bzlzm** [SuperManito/JD-FreeFuck#181]
大神好，爱快出了个Docker，我摘取镜像启动后一会就关闭了，也进不了控制台，提示

没有映射config配置目录给本容器，请先按教程映射config配置目录...

上哪儿找这个配置文件呢，另外我看您说明里说安装在/opt/jd目录下，没有还要新建，可爱快的Docker根本就SSH不了啊，请指教，谢谢！

**Comment by SuperManito** [comment]
容器启动必须挂载config配置文件目录，否则会导致容器初始化失败进而报错无法启动容器，如果没有/opt/jd这个目录随便任何一个目录都可以

**Comment by bzlzm** [comment]
大佬，要怎么挂载呢，爱快Docker下面倒是有挂载目录的设置
我是设置成
            源路径                                    目标路径
/OS/Docker/backups/JD/            /opt/jd/config

还是无效启动不起来啊

**Comment by bzlzm** [comment]
谢谢大神，我研究出来了，我先在VM的ubuntu里安装了一次，找到config位置了   /jd/config  这样安快也可以安装了

/OS/Docker/backups/JD/      ==>     /jd/config

**Comment by SuperManito** [comment]
本来就是修改启动容器的挂载目录，后面不能动的，你随便指定一个存在的目录即可，为什么启动失败是因为/opt目录不存在
![image](https://user-images.githubusercontent.com/68613938/111032139-c6ed9180-8445-11eb-8868-e7b620fabef3.png)
