### ISSUE TITLE
pushplus推送失败

### ISSUE THREAD

**Issue by ccyykk0330** [SuperManito/JD-FreeFuck#184]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：v3.32.6

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：pushplus推送失败，提示：push+发送一对一通知消息失败：用户信息状态不合法
检查sendNotify.js文件发现，pushplus推送链接错误，脚本内链接为url: `http://www.pushplus.plus/send`,，实际应为http://pushplus.hxtrip.com/send

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：push+发送一对一通知消息失败：用户信息状态不合法

**Comment by SuperManito** [comment]
https://gitee.com/lxk0301/jd_docker/issues/I3AOGW
