### ISSUE TITLE
服务器拒绝访问，不能更新脚本

### ISSUE THREAD

**Issue by zlsf9** [SuperManito/JD-FreeFuck#185]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [x] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：Version: v3.32.4    Date: 2021-3-10

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A： N1 路由器 49+o , ARMv8 Processor rev 4 (v8l) x 4  ,OpenWrt R20.10.20 / LuCI Master (git-20.256.12360-1a54222), 已安装docker 并部署成功
       使用 更新一键更新脚本： docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh -O git_pull.sh  时报错
       使用  一键更新脚本：docker exec -it jd bash git_pull.sh 也报错

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
root@OpenWrt:~# docker exec -it jd bash git_pull.sh
----------------------------------------------------------------------
当前系统时间  2021-03-13 22:22
活动脚本目录  /jd/scripts
---------------------------------------------------------------------
更新 JD-FreeFuck 项目脚本：
Fetching origin
fatal: unable to access 'https://gitee.com/SuperManito/JD-FreeFuck.git/': Failed to connect to gitee.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at af2f208 Update run.html
克隆 lxk0301 活动脚本：
Cloning into '/jd/scripts'...
ssh: connect to host gitee.com port 22: Connection refused
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
------------------------------------------------------------------
活动脚本更新失败，请检查原因或再次运行 git_pull.sh......

root@OpenWrt:~# docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh -O git_pull.sh
--2021-03-14 08:23:55--  https://gitee.com/SuperManito/JD-FreeFuck/raw/source/git_pull.sh
Resolving gitee.com... 180.97.125.228
Connecting to gitee.com|180.97.125.228|:443... failed: Connection refused.

**Comment by haowen2000** [comment]
收到同样的提示

fatal: unable to access 'https://gitee.com/SuperManito/JD-FreeFuck.git/': Failed to connect to gitee.com port 443: Connection refused
error: Could not fetch origin
HEAD is now at af2f208 Update run.html

**Comment by Flat1986** [comment]
一样

**Comment by SuperManito** [comment]
@zlsf9 @Flat1986 为什么要勾选`已仔细阅读了《常见问题与帮助》`？
