### ISSUE TITLE
Liunx 问题:控制面板无法启动,ecosystem.config.js not found

### ISSUE THREAD

**Issue by winsonhet** [SuperManito/JD-FreeFuck#187]
# cd /opt/jd
# pm2 start panel/ecosystem.config.js
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] File panel/ecosystem.config.js not found

**Comment by SuperManito** [comment]
不更新新版本肯定没有，你的版本停留在3月7号以前

**Comment by winsonhet** [comment]
好的，谢谢
