### ISSUE TITLE
在线修改脚本文件

### ISSUE THREAD

**Issue by yiyule10** [SuperManito/JD-FreeFuck#188]
我发现蓝币兑换京东的脚本，默认不兑换京豆，能不能在线进行修改？

**Comment by ericli911** [comment]
控制面板，首页里就可以修改

**Comment by yiyule10** [comment]
@ericli911 jd_blueCoin.js我想要修改这个脚本，让这个脚本兑换京豆。
控制面板里面不支持修改这个脚本

**Comment by yiyule10** [comment]
@ericli911 谢谢您的提醒，我找到了
