### ISSUE TITLE
bash: run-all.sh: No such file or directory

### ISSUE THREAD

**Issue by jackli201** [SuperManito/JD-FreeFuck#19]
bash: run-all.sh: No such file or directory
老大，这个怎么解决？

**Comment by LQ2002** [comment]
![image](https://user-images.githubusercontent.com/50812010/106836084-71e68f00-66d3-11eb-8239-2e6a7d0dea72.png)
要进入文件目录才能执行脚本的，检查一下你在没在相应的文件夹里执行操作

**Comment by SuperManito** [comment]
> ![image](https://user-images.githubusercontent.com/50812010/106836084-71e68f00-66d3-11eb-8239-2e6a7d0dea72.png)
> 要进入文件目录才能执行脚本的，检查一下你在没在相应的文件夹里执行操作

......新版本在 /opt/jd

**Comment by SuperManito** [comment]
> bash: run-all.sh: No such file or directory
> 老大，这个怎么解决？

    cd /opt/jd
