### ISSUE TITLE
钉钉消息推送失败

### ISSUE THREAD

**Issue by hengwuming** [SuperManito/JD-FreeFuck#190]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：钉钉消息推送失败，似乎是钉钉升级了

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：invalid timestamp, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq]

**Comment by SuperManito** [comment]
去问lxk

**Comment by hengwuming** [comment]
> 去问lxk

我找不到他的项目地址了，指条路呗。

**Comment by ericli911** [comment]
gitee.com/lxk0301发自我的华为手机

**Comment by hengwuming** [comment]
> gitee.com/lxk0301

感谢

**Comment by SuperManito** [comment]
> > gitee.com/lxk0301
> 
> 感谢

去这里发Issues
https://gitee.com/lxk0301/jd_docker

**Comment by hengwuming** [comment]
> > > gitee.com/lxk0301
> > 
> > 
> > 感谢
> 
> 去这里发Issues
> https://gitee.com/lxk0301/jd_docker

好的，谢谢
