### ISSUE TITLE
run_all.sh和run-all.sh

### ISSUE THREAD

**Issue by alexallen1** [SuperManito/JD-FreeFuck#193]
感谢你做了这个自动脚本，在教程那里，发现一个小问题：
![image](https://user-images.githubusercontent.com/79105799/111188043-95b0c500-85ef-11eb-903e-fb64abc4984a.png)

vps cd /opt/jd里的是run-all.sh

**Comment by alexallen1** [comment]
已解决。
初次安装是3月4日。可能那时候还是run-all.sh。不过，执行过bash git_pull.sh还是run-all.sh
rm -rf重装解决

**Comment by SuperManito** [comment]
如果你更新了3月7号的版本就不会出现这个问题
