### ISSUE TITLE
域名解析

### ISSUE THREAD

**Issue by wangwei8828** [SuperManito/JD-FreeFuck#196]
小白建议加上控制面板的域名解析和HTTPS的教学。

**Comment by nxcjs** [comment]
这个项目，需要什么域名解析和https啊发送自我的盖乐世
-------- 原始信息 --------发件人： wangwei8828 ***@***.***> 日期: 2021/3/17  下午12:01  (GMT+08:00) 收件人： SuperManito/JD-FreeFuck ***@***.***> 抄送： Subscribed ***@***.***> 主题： [SuperManito/JD-FreeFuck] 域名解析 (#196) 

小白建议加上控制面板的域名解析和HTTPS的教学。

**Comment by SuperManito** [comment]
@wangwei8828 还域名解析，给你们再配个ssl证书得了呗
