### ISSUE TITLE
消息推送

### ISSUE THREAD

**Issue by HiLittleFriend** [SuperManito/JD-FreeFuck#2]
请问这个一键脚本是不是没有消息推送功能，我没找到原脚本env文件夹里的all文件

**Comment by SuperManito** [comment]
如果您看的懂代码的话可以去看一下，我这个脚本就是搭建个环境，然后创建两个一键执行的脚本，其它原作者的东西一概没动，我的脚本属于二次使用，我不负责这个项目的开发，任何使用相关的问题去咨询EvineDeng和lxk0301大佬，与我无关，消息推送功能在config.sh文件里，自己配置
sed -i '70c export PUSH_KEY=""' /home/myid/jd/config/config.sh
这是配置server酱微信推送的命令格式
