### ISSUE TITLE
docker版无法pull

### ISSUE THREAD

**Issue by BlueSpiderGIGI** [SuperManito/JD-FreeFuck#20]
docker版无法pull

**Comment by SuperManito** [comment]
> docker版无法pull

evine的容器没了，拉不到镜像，我也不知道发生了什么，不是我脚本的问题，等等看吧 https://hub.docker.com/r/evinedeng/jd

**Comment by SuperManito** [comment]
> docker版无法pull

新版已发布，请重新部署
