### ISSUE TITLE
centos7重启后控制面板无法重启

### ISSUE THREAD

**Issue by hapighm** [SuperManito/JD-FreeFuck#201]
在对虚拟机centos7重启后，控制面板无法打开，手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？

**Comment by SuperManito** [comment]
多久没更新了？重装新版本

**Comment by hapighm** [comment]
前几天刚重装的，上次重装是因为服务器断电，开机后面板打不开，重装面板也不行…不过我关机的时候不是先关面板再关系统，是直接关的系统，跟这个有关系吗？难道只有重装一一条路吗？T_T发自我的华为手机-------- 原始邮件 --------发件人： SuperManito ***@***.***>日期： 2021年3月18日周四 18:56收件人： SuperManito/JD-FreeFuck ***@***.***>抄送： hapighm ***@***.***>, Author ***@***.***>主    题： Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)

多久没更新了？重装新版本

**Comment by SuperManito** [comment]
手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？

要么你没进项目目录执行命令，要么就是3月7号的版本你没更新

**Comment by hapighm** [comment]
肯定是3月7日后重装的…我在jd目录下执行命令就行吧？发自我的华为手机-------- 原始邮件 --------发件人： SuperManito ***@***.***>日期： 2021年3月18日周四 21:00收件人： SuperManito/JD-FreeFuck ***@***.***>抄送： hapighm ***@***.***>, Author ***@***.***>主    题： Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)

手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？

要么你没进项目目录执行命令，要么就是3月7号的版本你没更新

**Comment by hapighm** [comment]
项目目录下启动报错如图






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperManito/JD-FreeFuck"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)





 
手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？
 
要么你没进项目目录执行命令，要么就是3月7号的版本你没更新

**Comment by hapighm** [comment]
pannel目录下启动报错如图，但是目录下都有文件啊...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperManito/JD-FreeFuck"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)





 
手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？
 
要么你没进项目目录执行命令，要么就是3月7号的版本你没更新

**Comment by SuperManito** [comment]
> pannel目录下启动报错如图，但是目录下都有文件啊...
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito/JD-FreeFuck" ***@***.***&gt;; 发送时间:&nbsp;2021年3月18日(星期四) 晚上9:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201) 手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？ 要么你没进项目目录执行命令，要么就是3月7号的版本你没更新 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

去重装去吧

**Comment by hapighm** [comment]
重新安装面板后可以启动了…发自我的华为手机-------- 原始邮件 --------发件人： SuperManito ***@***.***>日期： 2021年3月18日周四 21:00收件人： SuperManito/JD-FreeFuck ***@***.***>抄送： hapighm ***@***.***>, Author ***@***.***>主    题： Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)

手动启动控制面板提示 File panel/ecosystem.config.js not found 请问该怎么解决？

要么你没进项目目录执行命令，要么就是3月7号的版本你没更新

**Comment by SuperManito** [comment]
嗯

**Comment by hapighm** [comment]
谢谢大佬～发自我的华为手机-------- 原始邮件 --------发件人： SuperManito ***@***.***>日期： 2021年3月18日周四 22:25收件人： SuperManito/JD-FreeFuck ***@***.***>抄送： hapighm ***@***.***>, Author ***@***.***>主    题： Re: [SuperManito/JD-FreeFuck] centos7重启后控制面板无法重启 (#201)

嗯
