### ISSUE TITLE
京东现金是怎么用的？

### ISSUE THREAD

**Issue by mohanfeng3** [SuperManito/JD-FreeFuck#206]
谁会了都可以说下哈，大佬估计比较忙，我看通知消息里有京东现金，十几元，但是在京东 京喜 京东急速都找不到这个钱在哪，不会用

**Comment by SuperManito** [comment]
那不写着分类呢么，打到你钱包里边去了

**Comment by mohanfeng3** [comment]
> 那不写着分类呢么，打到你钱包里边去了

钱包里是0，所以才好奇。。

**Comment by ericli911** [comment]
凑足一定金额后自己提现，10几块肯定可以提现了。位置在京东app首页，跟领京豆免费水果在一块

**Comment by mohanfeng3** [comment]
> 几块肯定可以提现了。位置在京东app首页，跟
没有找到，挨个点进去看了都没有啊，可以具体点不

**Comment by mohanfeng3** [comment]
> 凑足一定金额后自己提现，10几块肯定可以提现了。位置在京东app首页，跟领京豆免费水果在一块

找到了，谢谢
