### ISSUE TITLE
作者下午通知删除了，把源码留下来了

### ISSUE THREAD

**Issue by xy364515640** [SuperManito/JD-FreeFuck#21]
![QQ图片20210204225844](https://user-images.githubusercontent.com/29057248/106911461-22d54400-673d-11eb-83e2-ee36840f0ffa.png)
[dj.tar.gz](https://github.com/SuperManito/JD-FreeFuck/files/5926550/dj.tar.gz)
是否有用呢

**Comment by SuperManito** [comment]
唉，原作者提供的Docker-Compose太难了，部署难使用更难，门槛有点高了，我不在这个群，兄弟有给个TG链接我加一下，我看看

**Comment by xy364515640** [comment]
> ，原作者提供的Docker-Compose太难了，部署难使用更难，门云有点高了，我不在这个群，兄弟有给个TG链接我加一下，我看看

我也进不去，只有频道，群私有了，只出不进。。。或者你挂个说明，谁有群，私聊下你。

**Comment by SuperManito** [comment]
我太难了。。。本来我也不懂node，唉，明天LOL就开放无限乱斗了，我现在还要研究这个东西从而继续薅羊毛

**Comment by xy364515640** [comment]
> 本来我也不懂node，唉，明天LOL就开放无限乱斗了，我现在还要研究这个东西从而继续薅羊毛

不急，暂时也没什么新活动，0301大佬都没怎么更新了，这些暂时都没啥需要维护的。

**Comment by xy364515640** [comment]
> 本来我也不懂node，唉，明天LOL就开放无限乱斗了，我现在还要研究这个东西从而继续薅羊毛

不急，暂时也没什么新活动，0301大佬都没怎么更新了，这些暂时都没啥需要维护的。

**Comment by SuperManito** [comment]
> > 本来我也不懂node，唉，明天LOL就开放无限乱斗了，我现在还要研究这个东西从而继续薅羊毛
> 
> 不急，暂时也没什么新活动，0301大佬都没怎么更新了，这些暂时都没啥需要维护的。

我还没看懂它的原理是什么，我刚把0301大佬的docker-compose看懂了，也是构建一个基于alpine Linux的容器，跟evine的镜像一样

**Comment by SuperManito** [comment]
门槛太高劝退小白啊。。。

**Comment by xy364515640** [comment]
> 门情报太高劝退小白啊。。。

其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充

**Comment by SuperManito** [comment]
> > 门情报太高劝退小白啊。。。
> 
> 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充

我根本就没用过，也不会用，咋用啊兄弟，教教我

**Comment by SuperManito** [comment]
> > 门情报太高劝退小白啊。。。
> 
> 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充

他的项目页怎么用教程都没写，我看好像就是`node + 活动脚本`

**Comment by xy364515640** [comment]
> > > 门情报太高劝退小白啊。。。
> > 
> > 
> > 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充
> 
> 他的项目页怎么用教程都没写，我看好像就是`node + 活动脚本`

他的docker-compose，默认配置就写了一部分，都只是举了例子。怎么补我也不会，这是他默认配置写的东西https://gitee.com/lxk0301/jd_scripts/blob/master/docker/example/default.yml

**Comment by SuperManito** [comment]
> > > > 门情报太高劝退小白啊。。。
> > > 
> > > 
> > > 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充
> > 
> > 
> > 他的项目页怎么用教程都没写，我看好像就是`node + 活动脚本`
> 
> 他的docker-compose，默认配置就写了一部分，都只是举了例子。怎么补我也不会，这是他默认配置写的东西https://gitee.com/lxk0301/jd_scripts/blob/master/docker/example/default.yml

我刚才看到了

**Comment by xy364515640** [comment]
> > > > > 门情报太高劝退小白啊。。。
> > > > 
> > > > 
> > > > 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充
> > > 
> > > 
> > > 他的项目页怎么用教程都没写，我看好像就是`node + 活动脚本`
> > 
> > 
> > 他的docker-compose，默认配置就写了一部分，都只是举了例子。怎么补我也不会，这是他默认配置写的东西https://gitee.com/lxk0301/jd_scripts/blob/master/docker/example/default.yml
> 
> 我刚才看到了

抽时间研究研究这个，其实不用互助码，这个也够用了

**Comment by SuperManito** [comment]
> > > > > > 门情报太高劝退小白啊。。。
> > > > > 
> > > > > 
> > > > > 其实我觉得能不能把0301大佬的能不能修补下，补充完整也能用，他那个太简陋了，啥都要自己补充
> > > > 
> > > > 
> > > > 他的项目页怎么用教程都没写，我看好像就是`node + 活动脚本`
> > > 
> > > 
> > > 他的docker-compose，默认配置就写了一部分，都只是举了例子。怎么补我也不会，这是他默认配置写的东西https://gitee.com/lxk0301/jd_scripts/blob/master/docker/example/default.yml
> > 
> > 
> > 我刚才看到了
> 
> 抽时间研究研究这个，其实不用互助码，这个也够用了

我已经找到了解决办法，重回系统直装的怀抱，基于evine的源码，明天就能看到我的脚本了，通宵制作中

**Comment by SuperManito** [comment]
新版已发布，请重新部署

**Comment by xy364515640** [comment]
> 新版已发布，请重新部署

辛苦了，这是一晚上没睡吗，大佬牛逼

**Comment by SuperManito** [comment]
> > 新版已发布，请重新部署
> 
> 辛苦了，这是一晚上没睡吗，大佬牛逼

嗯

**Comment by Luxuslaerm** [comment]
大佬能不能指点一下怎么用源码本地部署docker呢，用的是N1盒子，感觉还是docker好用些，或者自己注册个docker hub也行，不知道要用哪些命令呢，或者提供个教程链接吧，谢谢啦

**Comment by SuperManito** [comment]
> 大佬能不能指点一下怎么用源码本地部署docker呢，用的是N1盒子，感觉还是docker好用些，或者自己注册个docker hub也行，不知道要用哪些命令呢，或者提供个教程链接吧，谢谢啦

你有备份的新镜像吗，Evine退隐前发的，有的话我就给开发，但是不是适配软路由，是适配docker方法

**Comment by Luxuslaerm** [comment]
> > 大佬能不能指点一下怎么用源码本地部署docker呢，用的是N1盒子，感觉还是docker好用些，或者自己注册个docker hub也行，不知道要用哪些命令呢，或者提供个教程链接吧，谢谢啦
> 
> 你有备份的新镜像吗，Evine退隐前发的，有的话我就给开发，但是不是适配软路由，是适配docker方法

不是最新的，昨天晚上忙完evine已经删库了，没有拉取最后一版镜像。刚研究了一下docker好像是通过alpine用dockerfile构建？还想着是不是能简单改改把源码部署进去，然后看了看evine的脚本，劝退了，流下了没有技术的眼泪

**Comment by SuperManito** [comment]
> > > 大佬能不能指点一下怎么用源码本地部署docker呢，用的是N1盒子，感觉还是docker好用些，或者自己注册个docker hub也行，不知道要用哪些命令呢，或者提供个教程链接吧，谢谢啦
> > 
> > 
> > 你有备份的新镜像吗，Evine退隐前发的，有的话我就给开发，但是不是适配软路由，是适配docker方法
> 
> 不是最新的，昨天晚上忙完evine已经删库了，没有拉取最后一版镜像。刚研究了一下docker好像是通过alpine用dockerfile构建？还想着是不是能简单改改把源码部署进去，然后看了看evine的脚本，劝退了，流下了没有技术的眼泪

我要是能看懂docker-compose我直接用lxk0301的方法了，太难了，变量看不懂，它那个也是构建alpine的镜像
