### ISSUE TITLE
活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......

### ISSUE THREAD

**Issue by yaj6835669** [SuperManito/JD-FreeFuck#210]
Docker最近执行一键更新提示“活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......”是什么情况

**Comment by yaj6835669** [comment]
root@OpenWrt:/opt/jd# docker exec -it jd bash git_pull.sh

+----------------- 开 始 执 行 更 新 脚 本 -----------------+

   活动脚本目录：/jd/scripts

   当前系统时间：2021-03-20 21:15

+-----------------------------------------------------------+

更新 JD-FreeFuck 项目脚本：

Fetching origin
HEAD is now at a702b6a 新增 "城城领现金" 互助码类与控制脚本功能环境变量(14)(33)，修正部分注释内容

更新 lxk0301 活动脚本：

error: object file .git/objects/92/9567b68727e1f0e8dcd29deb6f0655f491e435 is empty
fatal: loose object 929567b68727e1f0e8dcd29deb6f0655f491e435 (stored in .git/objects/92/9567b68727e1f0e8dcd29deb6f0655f491e435) is corrupt
error: object file .git/objects/92/9567b68727e1f0e8dcd29deb6f0655f491e435 is empty
error: object file .git/objects/92/9567b68727e1f0e8dcd29deb6f0655f491e435 is empty
fatal: loose object 929567b68727e1f0e8dcd29deb6f0655f491e435 (stored in .git/objects/92/9567b68727e1f0e8dcd29deb6f0655f491e435) is corrupt

+----------------------- 郑 重 提 醒 -----------------------+

  本项目开源免费使用，并且不可分享在国内的任何媒体与网站上！

  如果在其它地方发现以付费的形式传播与使用请举报并向我反馈！

  近期发现有人通过本项目和活动脚本非法牟利，已收集相关证据！

  请停止你的违法行为，立即从咸鱼等国内平台上下架，好自为之！

+-----------------------------------------------------------+

活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......

**Comment by SuperManito** [comment]
不清楚
