### ISSUE TITLE
是不是应该有个全局的是否参与助力开关

### ISSUE THREAD

**Issue by dariner** [SuperManito/JD-FreeFuck#211]
如果不想使用助力功能 该怎么设置 ，仅仅完成每日签到即可
我仔细设置了一下  发现除了停止执行任务以外  没有办法不去参与助力

**Comment by SuperManito** [comment]
单靠本地账户往往是不能助力完的，所以作者设计了一个用户库用来助力，如果你提交上去你也会被助力
