### ISSUE TITLE
执行脚本报错

### ISSUE THREAD

**Issue by beenewtree** [SuperManito/JD-FreeFuck#212]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [x] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [ ] `amd64` `x86-64` `x86-32`
- [x] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：可以更新脚本列表，但是不能执行具体的脚本

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：==================脚本执行- 北京时间(UTC+8)：2021/3/21 下午9:12:32=====================

(node:4528) UnhandledPromiseRejectionWarning: Error: Cannot find module '/jd/scripts/node_modules/got/dist/source'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.initGotEnv (/jd/scripts/jd_moneyTree.js:691:3742)
    at Object.post (/jd/scripts/jd_moneyTree.js:691:5658)
    at /jd/scripts/jd_moneyTree.js:607:7
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
sed: no previous regexp

**Comment by SuperManito** [comment]
不清楚

**Comment by SuperManito** [comment]
重装尝试
