### ISSUE TITLE
linux版可以后台执行吗？

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#213]
linux版可以后台执行吗？
vps服务器部署，windows电脑通过ssh执行，
这样要2台电脑，有点浪费资源，
可以不通过ssh，直接在vps后台执行吗，这样只要一台电脑就行。

**Comment by SuperManito** [comment]
> linux版可以后台执行吗？
> vps服务器部署，windows电脑通过ssh执行，
> 这样要2台电脑，有点浪费资源，
> 可以不通过ssh，直接在vps后台执行吗，这样只要一台电脑就行。

本来就有定时，为什么要后台呢？
