### ISSUE TITLE
大佬控制面板主题怎么替换呢

### ISSUE THREAD

**Issue by Golee520** [SuperManito/JD-FreeFuck#214]
我看大佬给弄了个好看的flash背景主题，挺棒的！
问题我的破电脑flash运行就卡的不行，现在控制面板根本没法编辑了。
请问大佬主题在哪替换，我想换回原来的静态页面

**Comment by SuperManito** [comment]
> 我看大佬给弄了个好看的flash背景主题，挺棒的！
> 问题我的破电脑flash运行就卡的不行，现在控制面板根本没法编辑了。
> 请问大佬主题在哪替换，我想换回原来的静态页面

很卡？不会吧，啥电脑啊

**Comment by SuperManito** [comment]
我这里流畅的很

**Comment by piaoyun** [comment]
我这里也感觉卡呢，amd 3600x的CPU。16G的内存呢，用的是chrome浏览器呢

**Comment by SuperManito** [comment]
> 我这里也感觉卡呢，amd 3600x的CPU。16G的内存呢，用的是chrome浏览器呢

我这里很流畅啊，用的Chrome最新版，8700K，32G内存，3080

**Comment by cdle** [comment]
华丽丽的感觉
