### ISSUE TITLE
Linux教程有误

### ISSUE THREAD

**Issue by KevinZjYang** [SuperManito/JD-FreeFuck#218]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：7.9

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
> 三、控制面板教程
> 1. 手动启用控制面板：
> pm2 start panel/ecosystem.config.js

上述命令默认是在jd目录下运行，但是运行后会提示找不到/opt/jd/server.js。
建议修改教程为 进入panel目录后，再运行控制面板的相关命令。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/111940033-b786dc00-8b08-11eb-92e8-538dbeace4ee.png)

**Comment by KevinZjYang** [comment]
我已经在jd目录了，你自己去试一下就知道了。。。
