### ISSUE TITLE
第一次安装之后  再也打不开控制面板了

### ISSUE THREAD

**Issue by sun2589886503** [SuperManito/JD-FreeFuck#219]
按照教程完成了控制面板的安装  之后用127.0.0.1:5678的本地连接进控制面板  进不去了    新手求指导

**Comment by KevinZjYang** [comment]
pm2 list 看看控制面板在不在运行。

**Comment by SuperManito** [comment]
> 按照教程完成了控制面板的安装 之后用127.0.0.1:5678的本地连接进控制面板 进不去了 新手求指导

不按模板一律关闭

**Comment by sun2589886503** [comment]
谢谢大佬  可以了
