### ISSUE TITLE
能否增加openwrt的部署方法

### ISSUE THREAD

**Issue by dxh8497** [SuperManito/JD-FreeFuck#22]
谢谢了，arm版本，跟 x86版本

**Comment by SuperManito** [comment]
我看看吧，软路由我只能退出来方法，但是软件包需要自己去装，我不懂软路由

**Comment by SuperManito** [comment]
https://github.com/SuperManito/JD-FreeFuck/wiki/%E5%9F%BA%E4%BA%8E-Docker-%E7%9A%84%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95%EF%BC%88-%E8%BD%AF%E8%B7%AF%E7%94%B1%E3%80%81NAS-%EF%BC%89

**Comment by zhaojie199512** [comment]
感谢大佬，按您的教程已经成功在alpine系统里的docker上部署成功！！！试用下看下效果如何，先给大佬赞助5元买瓶快乐水喝

**Comment by SuperManito** [comment]
> 感谢大佬，按您的教程已经成功在alpine系统里的docker上部署成功！！！试用下看下效果如何，先给大佬赞助5元买瓶快乐水喝

谢谢老板，他们说我这个镜像是x86架构的

**Comment by tom315187917** [comment]
大佬，为啥我执行docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
提示连接被拒绝。麻烦看下，谢谢

**Comment by SuperManito** [comment]
> 大佬，为啥我执行docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
> 提示连接被拒绝。麻烦看下，谢谢

你确定你容器联网了？这是Gitee的链接不需要科学上网

**Comment by tom315187917** [comment]
> > 大佬，为啥我执行docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
> > 提示连接被拒绝。麻烦看下，谢谢
> 
> 你确定你容器联网了？这是Gitee的链接不需要科学上网

我开科学上网只代理非大陆ip，并非全局，只有这一个无法下载。我到容器里面执行wget 也是一样提示连接被拒绝连接，我看到都已经解析出ip地址。说明容器已经联网的。而不是提示找不到主机。因为这个文件我用浏览器是可以下载。或者您告知我把这个文件放在哪个位置也行。

**Comment by tom315187917** [comment]
> > 大佬，为啥我执行docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
> > 提示连接被拒绝。麻烦看下，谢谢
> 
> 你确定你容器联网了？这是Gitee的链接不需要科学上网

这个问题我解决的，就是openwrt的固件回流问题，我换了一个固件就好了

**Comment by SuperManito** [comment]
> > > 大佬，为啥我执行docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
> > > 提示连接被拒绝。麻烦看下，谢谢
> > 
> > 
> > 你确定你容器联网了？这是Gitee的链接不需要科学上网
> 
> 这个问题我解决的，就是openwrt的固件回流问题，我换了一个固件就好了

本来链接就没问题，你自己的问题，能不能访问在外面浏览器试一下不就知道了
