### ISSUE TITLE
Bark APP发送通知调用API失败

### ISSUE THREAD

**Issue by TheSaltwaterRoom** [SuperManito/JD-FreeFuck#220]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [] 是
- [x] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 6. 安装环境版本

A：

## 7. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：我填写了BARKapp提供的设备码，但是没推送过来

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by TheSaltwaterRoom** [comment]
> ## 1. 关于您要提交的问题
> Q：是否阅读并已接受《特别声明》与《项目声明》
> 
> * [] 是
> * [x]  否
> 
> Q：是否仔细阅读了《前言》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《部署前需知与准备工作》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《常见问题与帮助》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《使用需知》
> 
> * [x]  是
> * [ ]  否
> 
> ## 2. 安装版本
> * [ ]  Linux
> * [x]  Docker
> 
> ## 3. 安装平台
> * [ ]  PC
> * [ ]  VPS
> * [ ]  软路由
> * [ ]  NAS
> * [ ]  Other
> 
> ## 4. 安装平台架构
> * [x]  `amd64` `x86-64` `x86-32`
> * [ ]  `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
> * [ ]  `ppc64le` `s390x`
> * [ ]  `Other`
> 
> ## 5. 安装环境
> * [ ]  Ubuntu
> * [ ]  Debian
> * [x]  CentOS
> * [ ]  Fedora
> * [x]  Docker
> * [ ]  Other
> 
> ## 6. 安装环境版本
> A：
> 
> ## 7. 问题类型
> * [ ]  部署问题
> * [ ]  使用问题
> 
> ## 8. 详细叙述您的问题
> ### (1) 具体问题
> A：我填写了BARKapp提供的设备码，但是没推送过来
> 
> ### (2) 详细的系统日志
> _注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_
> 
HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1616409101321,
    socket: 1616409101322,
    lookup: 1616409101324,
    connect: 1616409101399,
    secureConnect: 1616409101552,
    upload: 1616409101552,
    response: 1616409101662,
    end: 1616409101663,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 75,
      tls: 153,
      request: 0,
      firstByte: 110,
      download: 1,
      total: 342
    }
  }
}
> A：

**Comment by SuperManito** [comment]
去问lxk
