### ISSUE TITLE
格式化导出助力码 京喜农场互助码出错

### ISSUE THREAD

**Issue by qiuzhongqiang** [SuperManito/JD-FreeFuck#222]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [ x] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x ] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [x ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x ] Docker
- [ ] Other

## 6. 安装环境版本

A：lean的源码编译的软路由的固件openwrt x86 OpenWrt R21.2.1。
      docker 版本
root@OpenWrt:~# docker version
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.16
 Git commit:        48a66213fe
 Built:             Sat Mar  6 16:43:17 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.16
  Git commit:       48a66213fe
  Built:            Fri Mar  5 16:29:04 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit: 

## 7. 问题类型

- [ ] 部署问题
- [x ] 使用问题

### (1) 具体问题
A：格式化导出助力码 京喜农场互助码出错
京喜农场：
MyJxnc1='{"smp":"10bd7b804e8b2ec80fe5f5c795df1844","active":"jdnc_1_2yuanhamigua210315_2","joinnum":1}'
MyJxnc2='{"smp":"b7d90113a97de640b52c45152c280674","active":"jdnc_1_liulianbing210305_2","joinnum":1}'
MyJxnc3='{"smp":"b8ea9622127e9ac1a238a54c3723df72","active":"jdnc_1_liulianbing210305_2","joinnum":1}'
MyJxnc4=''
MyJxnc5=''

ForOtherJxnc1="${MyJxnc2}@${MyJxnc3}"
ForOtherJxnc2="${MyJxnc1}@${MyJxnc3}"
ForOtherJxnc3="${MyJxnc1}@${MyJxnc2}"
ForOtherJxnc4="${MyJxnc1}@${MyJxnc2}@${MyJxnc3}"
ForOtherJxnc5="${MyJxnc1}@${MyJxnc2}@${MyJxnc3}"

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
这个活动不用考虑了，没人用，而且现在脚本API接口有问题应该跑不了
