### ISSUE TITLE
大佬，运行git_pull.sh报错帮忙看看是啥情况

### ISSUE THREAD

**Issue by simaxuan** [SuperManito/JD-FreeFuck#224]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：Centos8

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：运行bash git_pull.sh报错

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
[root@serverbt jd]# bash git_pull.sh

+----------------- 开 始 执 行 更 新 脚 本 -----------------+

   活动脚本目录：/opt/jd/scripts

   当前系统时间：2021-03-23 09:31

+-----------------------------------------------------------+

更新 JD-FreeFuck 项目脚本：

正在获取 origin
error: RPC failed; result=22, HTTP code = 502
fatal: The remote end hung up unexpectedly
error: 不能获取 origin
HEAD 现在位于 3edac1c 全新UI

更新 lxk0301 活动脚本：

正在获取 origin
Handshake: Repository more than 5 connections.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: 不能获取 origin
HEAD 现在位于 0f0c2a9 lxk0301.boxjs.json update

+----------------------- 郑 重 提 醒 -----------------------+

  本项目开源免费使用，并且不可分享在国内的任何媒体与网站上！

  如果在其它地方发现以付费的形式传播与使用请举报并向我反馈！

  近期发现有人通过本项目和活动脚本非法牟利，已收集相关证据！

  请停止你的违法行为，立即从咸鱼等国内平台上下架，好自为之！

+-----------------------------------------------------------+

活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......

**Comment by ericli911** [comment]
这种情况通常换个时间、等等就好了

simaxuan ***@***.***> 于2021年3月23日周二 上午9:35写道：

**Comment by banxiu** [comment]
想问问如何自动定时后台执行任务，因为要用服务器学习其他的，或者在执行期间可以建立其他连接操作服务器么

**Comment by SuperManito** [comment]
> 想问问如何自动定时后台执行任务，因为要用服务器学习其他的，或者在执行期间可以建立其他连接操作服务器么

不明白你在说什么

**Comment by SuperManito** [comment]
> ## 1. 关于您要提交的问题
> Q：是否阅读并已接受《特别声明》与《项目声明》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《前言》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《部署前需知与准备工作》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《常见问题与帮助》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《使用需知》
> 
> * [x]  是
> * [ ]  否
> 
> ## 2. 安装版本
> * [x]  Linux
> * [ ]  Docker
> 
> ## 3. 安装平台
> * [x]  PC
> * [ ]  VPS
> * [ ]  软路由
> * [ ]  NAS
> * [ ]  Other
> 
> ## 4. 安装平台架构
> * [x]  `amd64` `x86-64` `x86-32`
> * [ ]  `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
> * [ ]  `ppc64le` `s390x`
> * [ ]  `Other`
> 
> ## 5. 安装环境
> * [ ]  Ubuntu
> * [ ]  Debian
> * [x]  CentOS
> * [ ]  Fedora
> * [ ]  Docker
> * [ ]  Other
> 
> ## 6. 安装环境版本
> A：Centos8
> 
> ## 7. 问题类型
> * [ ]  部署问题
> * [x]  使用问题
> 
> ## 8. 详细叙述您的问题
> ### (1) 具体问题
> A：运行bash git_pull.sh报错
> 
> ### (2) 详细的系统日志
> _注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_
> 
> A：
> [root@serverbt jd]# bash git_pull.sh
> 
> +----------------- 开 始 执 行 更 新 脚 本 -----------------+
> 
> 活动脚本目录：/opt/jd/scripts
> 
> 当前系统时间：2021-03-23 09:31
> 
> +-----------------------------------------------------------+
> 
> 更新 JD-FreeFuck 项目脚本：
> 
> 正在获取 origin
> error: RPC failed; result=22, HTTP code = 502
> fatal: The remote end hung up unexpectedly
> error: 不能获取 origin
> HEAD 现在位于 [3edac1c](https://github.com/SuperManito/JD-FreeFuck/commit/3edac1ca9202fb1925776c99fbed618d8e6d39b9) 全新UI
> 
> 更新 lxk0301 活动脚本：
> 
> 正在获取 origin
> Handshake: Repository more than 5 connections.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> error: 不能获取 origin
> HEAD 现在位于 0f0c2a9 lxk0301.boxjs.json update
> 
> +----------------------- 郑 重 提 醒 -----------------------+
> 
> 本项目开源免费使用，并且不可分享在国内的任何媒体与网站上！
> 
> 如果在其它地方发现以付费的形式传播与使用请举报并向我反馈！
> 
> 近期发现有人通过本项目和活动脚本非法牟利，已收集相关证据！
> 
> 请停止你的违法行为，立即从咸鱼等国内平台上下架，好自为之！
> 
> +-----------------------------------------------------------+
> 
> 活动脚本更新失败，请检查原因或再次运行 git_pull.sh ......

为什么勾选了已阅读《常见问题与帮助》？
