### ISSUE TITLE
手动执行的脚本怎么可以挂机自动执行

### ISSUE THREAD

**Issue by kennylee60** [SuperManito/JD-FreeFuck#225]
每次自动执行只有获取了互助码那几个脚本，其他脚本都需要手动才能运行

**Comment by SuperManito** [comment]
？

**Comment by pasu0607** [comment]
不是把，我看crontab里边那么多定时任务，应该自动都运行把，但实际有的活动确实好像没有运行哦

**Comment by SuperManito** [comment]
> 不是把，我看crontab里边那么多定时任务，应该自动都运行把，但实际有的活动确实好像没有运行哦

如果有的活动执行了那说明定时没问题，自行查看定时任务帮助文档
