### ISSUE TITLE
关于扫码自动填写cookie到配置文件

### ISSUE THREAD

**Issue by 794329041** [SuperManito/JD-FreeFuck#226]
手机党 浏览器进控制面板更新ck很难受 粘贴ck太费劲了 可以把这个功能加回来吗？

**Comment by SuperManito** [comment]
> 手机党 浏览器进控制面板更新ck很难受 粘贴ck太费劲了 可以把这个功能加回来吗？

那个功能之前能用？好像不能用吧，所以我才删了的

**Comment by 794329041** [comment]
> > 奇特 · 科比特 · 多克 · 多克 · 斯多克 · 斯多克 · 斯多克 · 克特克 · 克特克 · 克多克 · 克多利特 · 多利特 · 多特 · 多特 · 克特 · 多克 · 克特 · 多克 · 克
> 
> 那个功能之前能用？好像不能用吧，所以我才删了的

能用啊 用了几次挺方便的 今天ck到期了 发现没这个功能了

**Comment by SuperManito** [comment]
> > > 奇特 · 科比特 · 多克 · 多克 · 斯多克 · 斯多克 · 斯多克 · 克特克 · 克特克 · 克多克 · 克多利特 · 多利特 · 多特 · 多特 · 克特 · 多克 · 克特 · 多克 · 克
> > 
> > 
> > 那个功能之前能用？好像不能用吧，所以我才删了的
> 
> 能用啊 用了几次挺方便的 今天ck到期了 发现没这个功能了

具体怎么个用法？是有Cookie变量空位就直接填写进去了吗？我之前都没用过

**Comment by 794329041** [comment]
> > > > 奇特 · 科比特 · 多克 · 多克 · 斯多克 · 斯多克 · 斯多克 · 克特克 · 克特克 · 克多克 · 克多利特 · 多利特 · 多特 · 多特 · 克特 · 多克 · 克特 · 多克 · 克
> > > 
> > > 
> > > 那个功能之前能用？好像不能用吧，所以我才删了的
> > 
> > 
> > 能用啊 用了几次挺方便的 今天ck到期了 发现没这个功能了
> 
> 具体怎么个用法？是有Cookie变量空位就直接填写进去了吗？我之前都没用过

我只用过更新ck  ck到期后 进去控制面板  扫码获取ck就行了 更新过的ck自动填入对应的ck里面并保存  特别方便

**Comment by SuperManito** [comment]
我再加回去

**Comment by 794329041** [comment]
> 我再加回去

感谢大佬

**Comment by SuperManito** [comment]
> > 我再加回去
> 
> 感谢大佬

已经加回去了，帮忙测试一下

**Comment by 794329041** [comment]
> > > 我再加回去
> > 
> > 
> > 感谢大佬
> 
> 已经加回去了，帮忙测试一下

替换老ck功能正常 添加新ck未测试

**Comment by SuperManito** [comment]
> > > > 我再加回去
> > > 
> > > 
> > > 感谢大佬
> > 
> > 
> > 已经加回去了，帮忙测试一下
> 
> 替换老ck功能正常 添加新ck未测试

ok
