### ISSUE TITLE
访问不了管理页面

### ISSUE THREAD

**Issue by hengwuming** [SuperManito/JD-FreeFuck#23]
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
sed：无法读取 /opt/jd/config/config.sh：No such file or directory
bash: /opt/jd/jd.sh: No such file or directory
bash: /opt/jd/jd.sh: No such file or directory
用的Centos8 azure的虚拟机 香港机房

**Comment by hengwuming** [comment]
忘了先升到root账户

**Comment by SuperManito** [comment]
QAQ

**Comment by hengwuming** [comment]
> QAQ

这个会定时执行吗？

**Comment by SuperManito** [comment]
> > QAQ
> 
> 这个会定时执行吗？我看日志好像不会定时执行

定时的话自己去研究，我不懂
