### ISSUE TITLE
活动火爆！

### ISSUE THREAD

**Issue by czxinshui** [SuperManito/JD-FreeFuck#230]
今天发现京东的活动都显示“活动火爆”无法参与！被那些UP主和电商卖家害死了，最终大家都可能被封活动！

**Comment by ericli911** [comment]
账号原因吧？

czxinshui ***@***.***> 于2021年3月25日周四 上午9:54写道：

**Comment by SuperManito** [comment]
> 今天发现京东的活动都显示“活动火爆”无法参与！被那些UP主和电商卖家害死了，最终大家都可能被封活动！

不信谣不传谣！
