### ISSUE TITLE
自动任务执行不生效问题。

### ISSUE THREAD

**Issue by kuangcuifeng** [SuperManito/JD-FreeFuck#231]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x] 是
- [ ] 否

## 2. 安装版本

- [x] Linux
- [ ] Docker

## 3. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 4. 安装平台架构

- [x] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 6. 安装环境版本

A：Ubuntu 20.04、Ubuntu 18.04

## 7. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：部署成功，控制面板、手动执行任务都正常使用。但是无法自动执行任务，定时任务失效，尝试多次部署均为解决，求大佬指教。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
我不知道你说怎么验证定时任务没有生效的问题，定时没问题

**Comment by kuangcuifeng** [comment]
> 我不知道你是怎么验证定时任务没有体现的，定时没问题

只单指我遇到了这个问题，特像大佬求助。
自动定时没有启动具体判断为：
1、没有任务日志。
2、我设置了消息推送，没有接到消息过。
3、进游戏相关页面，任务都没有做。
以上，我手动执行任务的话都没问题。

**Comment by SuperManito** [comment]
你是不是对定时理解有误啊
https://www.runoob.com/w3cnote/linux-crontab-tasks.html

**Comment by kuangcuifeng** [comment]
> 你是不是对定时理解有误啊
> https://www.runoob.com/w3cnote/linux-crontab-tasks.html

一键部署后定时任务都已经设置好了吧。我怀疑是不是我的win系统相关服务没有开启，导致无法运行自动任务。
![image](https://user-images.githubusercontent.com/75985876/112422617-2152f000-8d6c-11eb-9f8a-87759433ed7c.png)

**Comment by SuperManito** [comment]
不清楚
