### ISSUE TITLE
麻烦把动态背景去掉或者静态图片也可以

### ISSUE THREAD

**Issue by HyhBlazing** [SuperManito/JD-FreeFuck#232]
这个canvas渲染导致浏览器很卡，希望可以去掉或者换成静态图片，禁止刷新则会开启，和没有没啥区别呀。求。

**Comment by HyhBlazing** [comment]
感谢老哥，用的谷歌浏览器，电脑48G内存，I75820K，关闭浏览器硬件加速。

**Comment by SuperManito** [comment]
> 感谢老哥，用的谷歌浏览器，电脑48G内存，I75820K，关闭浏览器硬件加速。

垃圾电脑砸了吧

**Comment by HyhBlazing** [comment]
> > 感谢老哥，用的谷歌浏览器，电脑48G内存，I75820K，关闭浏览器硬件加速。
> 
> 垃圾电脑砸了吧

给老哥赞助一点，感谢啦。

**Comment by SuperManito** [comment]
> > > 感谢老哥，用的谷歌浏览器，电脑48G内存，I75820K，关闭浏览器硬件加速。
> > 
> > 
> > 垃圾电脑砸了吧
> 
> 给老哥赞助一点，感谢啦。

谢谢老板，安排1对1服务
