### ISSUE TITLE
docker 安装使用时由于环境不断重启，希望把重启去掉或者重启时间延长到10分钟以上

### ISSUE THREAD

**Issue by appotry** [SuperManito/JD-FreeFuck#234]
## 1. 关于您要提交的问题
Q：是否阅读并已接受《特别声明》与《项目声明》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《前言》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《部署前需知与准备工作》

- [ x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《使用需知》

- [x ] 是
- [ ] 否

## 2. 安装版本

- [ ] Linux
- [x ] Docker

## 3. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x ] NAS
- [ ] Other

## 4. 安装平台架构

- [x ] `amd64` `x86-64` `x86-32`
- [ ] `arm64` `aarch64` `arm/v8` `arm/v7` `arm/v6`
- [ ] `ppc64le` `s390x`
- [ ] `Other`

## 5. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x ] Docker
- [ ] Other

## 6. 安装环境版本

A：Nas qnap QTS4.5.2

## 7. 问题类型

- [ ] 部署问题
- [x ] 使用问题

### (1) 具体问题
A：docker安装好之后，发现面板启动不了，经查证是pm环境不对，按照wiki重装pm可以启动。
但是重新配置环境的时候，docker不断重启，绝大部分时候，都是还没有配置好环境，就重启了。
希望把docker启动脚本重启时间延长到10分钟以上，以便可以自己配置一些东西。

### (2) 详细的系统日志
_注：部署报错请将从开始执行脚本到结束终端输出的内容完整粘贴至此处！_

A：
`,
+----------------------- 郑 重 提 醒 -----------------------+,
,
  本项目开源免费使用，并且不可分享在国内的任何媒体与网站上！,
,
  如果在其它地方发现以付费的形式传播与使用请举报并向我反馈！,
,
  近期发现有人通过本项目和活动脚本非法牟利，已收集相关证据！,
,
  请停止你的违法行为，立即从咸鱼等国内平台上下架，好自为之！,
,
+-----------------------------------------------------------+,
,
活动脚本更新完成......,
,
,
========================2. 检测配置文件========================,
,
检测到config配置目录下存在crontab.list，自动导入定时任务...,
,
成功添加定时任务...,
,
========================3. 启动挂机程序========================,
,
已设置为不自动启动挂机程序，跳过...,
,
========================4. 启动控制面板========================,
,
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2,
[PM2] PM2 Successfully daemonized,
[PM2][WARN] Applications server not running, starting...,
[PM2] App [server] launched (1 instances),
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐,
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │,
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤,
│ 0   │ server    │ default     │ 1.0.0   │ fork    │ 490      │ 0s     │ 0    │ online    │ 0%       │ 34.6mb   │ root     │ enabled  │,
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘,
控制面板启动成功...,
,
如未修改用户名密码，则初始用户名为：useradmin，初始密码为：supermanito,
,
请访问 http://<ip>:5678 登陆并修改配置...,
,
容器启动成功......,
,
,
========================1. 更新源代码========================,
,
,
+----------------- 开 始 执 行 更 新 脚 本 -----------------+,
,
   活动脚本目录：/jd/scripts,
,
   当前系统时间：2021-03-25 17:17,
,
+-----------------------------------------------------------+,
,
更新 JD-FreeFuck 项目脚本：,
,
Fetching origin,
fatal: Unable to create '/jd/.git/index.lock': File exists.,
,
Another git process seems to be running in this repository, e.g.,
an editor opened by 'git commit'. Please make sure all processes,
are terminated then try again. If it still fails, a git process,
may have crashed in this repository earlier:,
remove the file manually to continue.,
,
更新 lxk0301 活动脚本：,
,
Fetching origin,
HEAD is now at 70fe2ff tgbot通知去掉支持markdown模式,
,
+----------------------- 郑 重 提 醒 -----------------------+,
,
  本项目开源免费使用，并且不可分享在国内的任何媒体与网站上！,
,
  如果在其它地方发现以付费的形式传播与使用请举报并向我反馈！,
,
  近期发现有人通过本项目和活动脚本非法牟利，已收集相关证据！,
,
  请停止你的违法行为，立即从咸鱼等国内平台上下架，好自为之！,
,
+-----------------------------------------------------------+,
,
活动脚本更新完成......,
,
,
========================2. 检测配置文件========================,
,
检测到config配置目录下存在crontab.list，自动导入定时任务...,
,
成功添加定时任务...,
,
========================3. 启动挂机程序========================,
,
已设置为不自动启动挂机程序，跳过...,
,
========================4. 启动控制面板========================,
,`

**Comment by appotry** [comment]
root@jd:/jd $ pm2 restart panel/ecosystem.config.js
[PM2][WARN] Applications server not running, starting...
[PM2][ERROR] Error: Script not found: /jd/server.js
===========

基本上就是为了解决这个报错，重新配置docker环境

**Comment by SuperManito** [comment]
`pm2 restart panel/ecosystem.config.js` 这个命令由于目录的原因适用于在第一次启动成功后才可以使用，另外，如果容器初始化失败会导致容器崩溃无法启动，并不是你所认为的`重启时间`，容器初始化过程会启动控制面板，你应该通过日志好好检查原因

**Comment by SuperManito** [comment]
而且为什么我要求使用终端执行命令就是确保不丢启动参数，只能使用图像界面的话就自己查吧

**Comment by appotry** [comment]
if [ "${1#-}" != "${1}" ] || [ -z "$(command -v "${1}")" ]; then
  set -- node "$@"
fi

pm2 start /jd/panel/ecosystem.config.js

sleep 600
exec "$@"
==================
问题是，初始化就出错了，web控制界面就启动不了

自己加了2行，如上，server.js这回可以启动成功了，在这之前手动重新安装了web控制相关的软件

但发现新问题，exec "$@" 这个一直执行失败，真正导致重启的是这一行shell

**Comment by appotry** [comment]
exec "$@" 执行会导致一直重启

**Comment by SuperManito** [comment]
> exec "$@" 执行会导致一直重启

新版镜像试了吗，我今天推送了新的镜像
