### ISSUE TITLE
刚刚TG号突然退出被封？有谁知道原因

### ISSUE THREAD

**Issue by Batman2020abc** [SuperManito/JD-FreeFuck#235]
加了群后，没说话。tg号突然登出，再登录就提示手机号被封。
有人有同样状况吗？
被人恶意举报封号还是啥原因？

**Comment by SuperManito** [comment]
你ID叫什么？

**Comment by Batman2020abc** [comment]
> 你ID叫什么？

1791203670，名字是ll

**Comment by SuperManito** [comment]
发ID，不要发手机号 @开头的

**Comment by Batman2020abc** [comment]
> 发ID，不要发手机号 @开头的

1，1791203670这个不是手机号，是TG id
悲剧，忘记@开头的这个了。
2，我的google voice是，+1 704 931 3459
可以用这个聊天吗？

**Comment by SuperManito** [comment]
> > 发ID，不要发手机号 @开头的
> 
> 1，1791203670这个不是手机号，是TG id
> 悲剧，忘记@开头的这个了。有办法解禁吗？
> 2，我的google voice是，+1 704 931 3459
> 可以用这个聊天吗？

手机号查不到的

**Comment by Batman2020abc** [comment]
> > > 发ID，不要发手机号 @开头的
> > 
> > 
> > 1，1791203670这个不是手机号，是TG id
> > 悲剧，忘记@开头的这个了。有办法解禁吗？
> > 2，我的google voice是，+1 704 931 3459
> > 可以用这个聊天吗？
> 
> 手机号查不到的

帮我试解禁另一个号(上周被同样情况被禁，群里也有鲁小迅bot)，@JobsT_T 或者@jobsT_T
