### ISSUE TITLE
关于助力

### ISSUE THREAD

**Issue by skyyaman** [SuperManito/JD-FreeFuck#236]
种豆的助力每天一点开就没了，怎么样留着呢。。。

**Comment by SuperManito** [comment]
> 种豆的助力每天一点开就没了，怎么样留着呢。。。

什么意思？

**Comment by skyyaman** [comment]
就是给别人助力了，如果不想助力怎么样弄。。。

**Comment by SuperManito** [comment]
> 就是给别人助力了，如果不想助力怎么样弄。。。

没办法，脚本默认助力，先助力本地账号然后再助力云端lxk的库里的

**Comment by ericli911** [comment]
首页的配置说明里有发自我的华为手机-------- 原始邮件 --------发件人： skyyaman ***@***.***>日期： 2021年3月26日周五 10:14收件人： SuperManito/JD-FreeFuck ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [SuperManito/JD-FreeFuck] 关于助力 (#236)

就是给别人助力了，如果不想助力怎么样弄。。。
