### ISSUE TITLE
兄弟，你着实有点儿不道德了

### ISSUE THREAD

**Issue by caiqy** [SuperManito/JD-FreeFuck#238]
本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
希望你好好反省一下你为人处世的态度

**Comment by SuperManito** [comment]
> 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> 希望你好好反省一下你为人处世的态度

我可没要求，等我发声明奥，少听那个孤儿歪曲事实

**Comment by SuperManito** [comment]
> 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> 希望你好好反省一下你为人处世的态度

而且改名这件事纯粹是为了名字统一，无任何规则可言，我更没有要求人家

**Comment by sensi-ribbed** [comment]
![EC080946-77DB-4251-864A-8388242F1692](https://user-images.githubusercontent.com/69623456/112577218-e8c81a80-8e2e-11eb-859f-135b1a05e196.png)

**Comment by caiqy** [comment]
> > 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> > 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> > 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> > 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> > 希望你好好反省一下你为人处世的态度
> 
> 而且改名这件事纯粹是为了名字统一，无任何规则可言，我更没有要求人家

电报聊天截图我是看了的，你自己说话态度有问题，对别的开发者一副轻蔑的样子，水果群，你的频道，互助群我都在，整个事情的经过我都看到了，几个群的人怼你的原因正是你的态度。你没有改脚本互助（当然可能你不会改），只是在频道发一些拿人头链接，这个我是赞成的，我也点了几次，但是我一看到你在互助群炫耀的那副嘴脸，我就直接退频道了。

**Comment by sensi-ribbed** [comment]
柘改脚本前缀是给lxk和e的容器适配
然而只有你要求改回jd好适配你“辛苦开发”的项目

还有，这才是接手Evine的docker项目的作者e大
![FD9B20E6-E126-476A-8C41-7F70E91D72B1](https://user-images.githubusercontent.com/69623456/112578374-9d167080-8e30-11eb-9857-a4cd58552f99.jpeg)

你的主流项目从哪里来的也没看你有明示

**Comment by ericli911** [comment]
这种事情大家私下沟通就好了

在 2021年3月26日星期五，sensi_ribbed ***@***.***> 写道：

**Comment by SuperManito** [comment]
@sensi-ribbed 3月初我刚把源码整明白，so，这叫求他？

**Comment by SuperManito** [comment]
> > > 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> > > 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> > > 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> > > 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> > > 希望你好好反省一下你为人处世的态度
> > 
> > 
> > 而且改名这件事纯粹是为了名字统一，无任何规则可言，我更没有要求人家
> 
> 电报聊天截图我是看了的，你自己说话态度有问题，对别的开发者一副轻蔑的样子，水果群，你的频道，互助群我都在，整个事情的经过我都看到了，几个群的人怼你的原因正是你的态度。你没有改脚本互助（当然可能你不会改），只是在频道发一些拿人头链接，这个我是赞成的，我也点了几次，但是我一看到你在互助群炫耀的那副嘴脸，我就直接退频道了。

你不喜欢我装比就不喜欢呗，没有人请你用我的项目吧，未尝他人苦莫劝他人善！

**Comment by caiqy** [comment]
> > > > 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> > > > 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> > > > 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> > > > 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> > > > 希望你好好反省一下你为人处世的态度
> > > 
> > > 
> > > 而且改名这件事纯粹是为了名字统一，无任何规则可言，我更没有要求人家
> > 
> > 
> > 电报聊天截图我是看了的，你自己说话态度有问题，对别的开发者一副轻蔑的样子，水果群，你的频道，互助群我都在，整个事情的经过我都看到了，几个群的人怼你的原因正是你的态度。你没有改脚本互助（当然可能你不会改），只是在频道发一些拿人头链接，这个我是赞成的，我也点了几次，但是我一看到你在互助群炫耀的那副嘴脸，我就直接退频道了。
> 
> 你不喜欢我装比就不喜欢呗，没有人请你用我的项目吧，未尝他人苦莫劝他人善！

看来你这个逼是装定了啊，好吧，我也不说了。

**Comment by SuperManito** [comment]
> > > > > 本来这个面板作者就不是你，你纯粹只是fork别人代码，简单加了些修改，而且很明显你对shell使用不熟悉
> > > > > 你要引入别的开发者的脚本，结果别人脚本命名不符合面板脚本jd.sh匹配规则，你就上电报要求别人改命名规则，还一副趾高气昂的态度。你既然声称你在开发这个面板，为什么你不自己修改jd.sh的匹配规则呢？无非就两个原因，1.你看不懂jd.sh，2.你太懒，懒得去翻阅脚本，宁愿去打扰别人。
> > > > > 而且从你跟别人交流的态度就能看出你这个人品性很差，电报频道里面通知发得一副正气凛然的样子，然后在互助群掏出从电报频道拉的人头截图，说得那些话，也就随便维护一下，一帮人就帮你助力，多么多么简答，很看不起关注你频道用户的样子。
> > > > > 一晚上搞了个面板背景图，结果搞得有的人手机卡，就提了些意见，很客气的问能不能控制背景图，你呢，很不耐烦，就是不改。结果打赏了几块钱，马上就该，你看看你那屁颠屁颠儿的样子？这是怎样的一副嘴脸？
> > > > > 希望你好好反省一下你为人处世的态度
> > > > 
> > > > 
> > > > 而且改名这件事纯粹是为了名字统一，无任何规则可言，我更没有要求人家
> > > 
> > > 
> > > 电报聊天截图我是看了的，你自己说话态度有问题，对别的开发者一副轻蔑的样子，水果群，你的频道，互助群我都在，整个事情的经过我都看到了，几个群的人怼你的原因正是你的态度。你没有改脚本互助（当然可能你不会改），只是在频道发一些拿人头链接，这个我是赞成的，我也点了几次，但是我一看到你在互助群炫耀的那副嘴脸，我就直接退频道了。
> > 
> > 
> > 你不喜欢我装比就不喜欢呗，没有人请你用我的项目吧，未尝他人苦莫劝他人善！
> 
> 看来你这个逼是装定了啊，好吧，我也不说了。

我之前也是跑脚本，辛辛苦苦跑1个月拉人头2天赚回来了换你你感觉怎样，对吧，而且这个事件我也不想说了，我承认我言语过激脾气也不好，但是是他们不断的在背后攻击、引战，未经他人苦莫劝他人善啊兄弟，没这个事我都不会搞群组的

**Comment by ericli911** [comment]
这种事情大家私下沟通就好了

**Comment by HoHoYee** [comment]
这种事情大家私下沟通就好了，我说句老实话，加的互助群我被踢了
