### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by w900316** [SuperManito/JD-FreeFuck#239]
![QQ截图20210326144104](https://user-images.githubusercontent.com/57336092/112593067-ed49fe80-8e41-11eb-9e4b-ebbb5f6e05bd.jpg)

更新报错

**Comment by KevinZjYang** [comment]
估计是大佬把他拉黑了。。。

**Comment by SuperManito** [comment]
> 估计是大佬把他拉黑了。。。

有人给tm京东客服打电话举报被水果群的人看见了
