### ISSUE TITLE
牛批

### ISSUE THREAD

**Issue by Kevincan** [SuperManito/JD-FreeFuck#240]
当了婊子还要立牌坊是吧，自己收那几个不明所以的赞助钱就使劲舔，起飞？不过是个未经世事乳臭未干的小屁孩罢了

**Comment by SuperManito** [comment]
笑了，你们那作者穷的没钱可收吧，酸了？

**Comment by q123458384** [comment]
数说实在的不道德，剽窃别人的劳动成果还又当又立
