### ISSUE TITLE
ubuntu  部署失败

### ISSUE THREAD

**Issue by andioy** [SuperManito/JD-FreeFuck#25]
/dev/fd/63: line 169: /opt/jd/manual-update.sh: No such file or directory
/dev/fd/63: line 195: node: command not found
/dev/fd/63: line 196: [: -eq: unary operator expected
请问一下这个是什么原因呢
小白一枚

**Comment by SuperManito** [comment]
日志发全一点，这个什么也看不出来，而且出现问题告诉我你使用的环境

**Comment by SuperManito** [comment]
已经修复了，原因是Nodejs官方安装脚本有所变动

**Comment by andioy** [comment]
大佬还是NODEJS安装失败

**Comment by SuperManito** [comment]
> 大佬还是NODEJS安装失败

你用的什么版本的linux，我刚改完代码，正在测试中

**Comment by SuperManito** [comment]
> 大佬还是NODEJS安装失败

我刚刚修复了CentOS脚本的错误
