### ISSUE TITLE
執行失敗

### ISSUE THREAD

**Issue by CATOOILG** [SuperManito/JD-FreeFuck#26]
[root@admin /opt/jd]#  sudo bash manual-update.sh

--------------------------------------------------------------

系统时间：2021-02-05 17:49:00

JS脚本目录：/opt/jd/scripts

--------------------------------------------------------------

git_pull.sh: line 52: git: command not found

js脚本更新失败，请检查原因或再次运行git_pull.sh...

git_pull.sh: line 86: perl: command not found
printf: usage: printf [-v var] format [arguments]
git_pull.sh: line 91: perl: command not found
jd.sh: line 11: cd: /opt/jd/scripts: No such file or directory
jd.sh: line 130: cd: /opt/jd/scripts: No such file or directory
jd.sh: line 11: cd: /opt/jd/scripts: No such file or directory
jd.sh: line 130: cd: /opt/jd/scripts: No such file or directory

> uname -a
Linux 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux(CentOS 8.2 64bit)

**Comment by SuperManito** [comment]
你用的是新版本还是旧版本

**Comment by SuperManito** [comment]
已经修复了，原因是Nodejs官方安装脚本有所变动

**Comment by CATOOILG** [comment]
重新執行安裝依舊

> git_pull.sh: line 52: git: command not found

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by SuperManito** [comment]
> 重新執行安裝依舊
> 
> > git_pull.sh: line 52: git: command not found
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...

重新部署，之前脚本错误，你的nodejs没装上应该，没有部署成功吧
