### ISSUE TITLE
运行run-all.sh一段时间以后，发现部分脚本未被执行

### ISSUE THREAD

**Issue by PwnerZhang** [SuperManito/JD-FreeFuck#27]
**例如：**
疯狂的JOY：
还没有运行过 jd_crazy_joy 脚本，没有产生日志...

京东赚赚：
还没有运行过 jd_jdzz 脚本，没有产生日志...

**Comment by SuperManito** [comment]
mkdir -p /opt/jd/logs 试下

**Comment by SuperManito** [comment]
可能是因为我脚本里没有创建日志目录

**Comment by SuperManito** [comment]
我今天刚写完脚本，还没有完整跑过

**Comment by PwnerZhang** [comment]
run-all.sh中`bash jd.sh jd_crazy_joy_coin now`重复了，建议修改。joy相关的活动比较耗时，建议移动到最后执行方便更好地调试其他脚本。脚本还是挺好用的，感谢！

**Comment by SuperManito** [comment]
> run-all.sh中`bash jd.sh jd_crazy_joy_coin now`重复了，如果有必要的话，建议修改。另外，joy相关的活动比较耗时，建议移动到最后执行方便更好地调试其他脚本。脚本还是挺好用的，感谢！

我是这样写的脚本，把crazy_joy_coin放到最后了，可能有错误，我今天写完了还没完整测试

**Comment by SuperManito** [comment]
> run-all.sh中`bash jd.sh jd_crazy_joy_coin now`重复了，如果有必要的话，建议修改。另外，joy相关的活动比较耗时，建议移动到最后执行方便更好地调试其他脚本。脚本还是挺好用的，感谢！

已经修复，请执行更新命令
