### ISSUE TITLE
Centos7 环境安装失败！

### ISSUE THREAD

**Issue by myseil** [SuperManito/JD-FreeFuck#29]
![image](https://user-images.githubusercontent.com/5617854/107054569-46ff5680-680b-11eb-82f2-a28082a681be.png)
![image](https://user-images.githubusercontent.com/5617854/107054681-68604280-680b-11eb-9857-903c6da4e79e.png)

**Comment by wwfelh** [comment]
需要自己手动装node.js,装最新版本的

**Comment by SuperManito** [comment]
稍等，我刚改完代码，我看一下

**Comment by SuperManito** [comment]
> 需要自己手动装node.js,装最新版本的

现在没问题了，有个小错误，已经修复，抱歉
