### ISSUE TITLE
脚本是否已经进行crontab定时任务

### ISSUE THREAD

**Issue by CATOOILG** [SuperManito/JD-FreeFuck#3]
同时是否可以进行消息推送的介入，将每天跑的jd.sh子脚本执行最终结果告诉[自己](https://sc.ftqq.com/) 如果可以请问如何改造呢？

**Comment by SuperManito** [comment]
我不负责原项目的开发和使用，server酱你不会用吗？？？自己去配置文件里改啊
sed -i '70c export PUSH_KEY=""' /home/myid/jd/config/config.sh
