### ISSUE TITLE
是否可以增加定时任务中文注释

### ISSUE THREAD

**Issue by 457992195** [SuperManito/JD-FreeFuck#33]
例如

# 京东秒秒币
10 7 * * * bash /opt/jd/jd.sh jd_ms
# 闪购盲盒
27 8 * * * bash /opt/jd/jd.sh jd_sgmh
# 删除优惠券(默认注释，如需要自己开启，如有误删，已删除的券可以在回收站中还原，慎用)
20 9 * * 6 bash /opt/jd/jd.sh jd_delCoupon

参照
https://gitee.com/lxk0301/jd_scripts/blob/master/docker/crontab_list.sh

**Comment by SuperManito** [comment]
我不是活动脚本的开发者，我也没有精力去改这些东西

**Comment by 457992195** [comment]
> 它是同步lxk大佬的，虽然没有添加注释，如果需要了解每个脚本对应的活动，去大佬项目页自己查https://gitee.com/lxk0301/jd_scripts

对 我就是看到里面有这个 感觉还不错 看来只能自己加上了
