### ISSUE TITLE
第二种获取cookie的方式，作者能否详细说下

### ISSUE THREAD

**Issue by cctyl** [SuperManito/JD-FreeFuck#34]
就是这段文字 “通过控制面板功能进入浏览器网页手机扫码获取”
通过控制面板怎么进入浏览器呢，没有找到相关的信息

**Comment by cctyl** [comment]
还有一个是，进入浏览器之后的操作方式，是按照第一个 获取 cookie的方式吗，还是其他方式

**Comment by 457992195** [comment]
你安装好后 有提示 ip和端口 进去 输入账号admin密码adminadmin，里面就有扫码登录的按钮，扫码后cookie就在剪贴板里面，然后自己复制到下面放入cookie的位置保存即可

**Comment by SuperManito** [comment]
> 还有一个是，进入浏览器之后的操作方式，是按照第一个 获取 cookie的方式吗，还是其他方式

这有啥难的吗，自己进去看看不就知道了？是我教程写的不够详细吗？

**Comment by cyz0105** [comment]
![image](https://user-images.githubusercontent.com/56500405/107148157-c49ea000-698c-11eb-8bb5-649d9192636b.png)

**Comment by SuperManito** [comment]
那不是写着扫码获取么

**Comment by cyz0105** [comment]
我知道啊,只是给他截了个图而已

**Comment by SuperManito** [comment]
> 我知道啊,只是给他截了个图而已

奥 我还以为你说发这个Issues的人呢
