### ISSUE TITLE
一点小建议  权限问题&报错问题

### ISSUE THREAD

**Issue by cyz0105** [SuperManito/JD-FreeFuck#36]
如果直接以普通用户身份运行
`sudo bash <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/install.sh)`
会提示`bash: /dev/fd/63: No such file or directory`
而我在网上搜索了下[解决方法](https://blog.csdn.net/jiahaoangle/article/details/106475891),将之改为
`sudo bash < <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/install.sh)`
就好了,
以root用户运行没这问题.

![1](https://user-images.githubusercontent.com/56500405/107147077-0e848780-6987-11eb-9bc5-f3817dde27be.png)

但第一次部署时还会遇到一些莫名其妙的报错,
比如`/opt/jd/git_pull.sh: line 171: npm: command not found`:
![image](https://user-images.githubusercontent.com/56500405/107147389-c8302800-6988-11eb-84b1-ca109286a0cf.png)
虽然看到面板提示,但是无法启动面板也无法访问.
![image](https://user-images.githubusercontent.com/56500405/107147452-29f09200-6989-11eb-9b67-069cda1453ea.png)
最后是查看运行git_pull.sh时发现需要用到npm但未安装,于是在git_pull.sh运行之前加上了`apt install npm`面板才得以运行
![image](https://user-images.githubusercontent.com/56500405/107147629-011ccc80-698a-11eb-81af-2cd1e49e41fe.png)
最后一点小建议,建议修改这里的命令
![image](https://user-images.githubusercontent.com/56500405/107147464-3d9bf880-6989-11eb-8683-a12d66255cd5.png)
为 `cd /opt/jd/ && bash run-all.sh` (有些用户可能在home/root目录待着,会提示找不到run-all.sh文件

**Comment by SuperManito** [comment]
去读部署前需知第1条

**Comment by cyz0105** [comment]
> 去读部署前需知第1条

没关系,我已经成功运行起来了,刚刚赞助了10元,脚本开发不易,谢谢

**Comment by SuperManito** [comment]
> > 去读部署前需知第1条
> 
> 没关系,我已经成功运行起来了,刚刚赞助了10元,脚本开发不易,谢谢

谢谢老板
