### ISSUE TITLE
找到ARM镜像  求大佬指导

### ISSUE THREAD

**Issue by m360110075** [SuperManito/JD-FreeFuck#43]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x ] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x ] 是
- [ ] 否

## 2. 安装平台

- [ ] 常规环境
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x ] Other

## 3. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ x] N1 ARM Docker
- [ ] Other

## 4. 安装环境具体版本号
A：
Client:
 Version:           v18.09.2
 API version:       1.39
 Go version:        go1.12.1
 Git commit:        v18.09.2
 Built:             unknown-buildtime
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:
  Built:            Tue Mar 26 00:06:51 CST 2019
  OS/Arch:          linux/arm64
  Experimental:     false

## 5. 问题类型

- [x ] 部署问题
- [x ] 使用问题

## 6. 详细叙述您的问题
找到了ARM的镜像  安装后DK运行   输入地址5678 显示访问的网页出错

### (1) 具体问题
A：
========================1. 更新源代码========================

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin

### (2) 详细的系统日志

A：
========================1. 更新源代码========================

更新shell脚本，原地址：https://gitee.com/evine/jd-base

Fetching origin

**Comment by SuperManito** [comment]
那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh

**Comment by m360110075** [comment]
大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperManito"<notifications@github.com&gt;; 
发送时间: 2021年2月11日(星期四) 凌晨4:23
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





 
那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh

**Comment by SuperManito** [comment]
> 大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:23 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你不看wiki教程过来问我？

**Comment by m360110075** [comment]
4. 替换文件
docker exec -it jd rm -rf git_pull.sh docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh这一步我也做了   在本地路径是在是找不到 半个小白 都是看着代码摸索  看了两天 真的是没搞懂  




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperManito"<notifications@github.com&gt;; 
发送时间: 2021年2月11日(星期四) 凌晨4:31
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





  
大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:23 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你不看wiki教程过来问我？

**Comment by SuperManito** [comment]
> 4. 替换文件 docker exec -it jd rm -rf git_pull.sh docker exec -it jd wget [https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh这一步我也做了](https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh%E8%BF%99%E4%B8%80%E6%AD%A5%E6%88%91%E4%B9%9F%E5%81%9A%E4%BA%86) 在本地路径是在是找不到 半个小白 都是看着代码摸索 看了两天 真的是没搞懂
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:31 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:23 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你不看wiki教程过来问我？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

发日志来，你跟我说也没用，这个命令就是替换文件，如果替换不了遇到报错就发系统日志给我看，而且我不知道你的镜像里面有什么文件

**Comment by m360110075** [comment]
请问日志命令是什么&nbsp; 谢谢&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperManito"<notifications@github.com&gt;; 
发送时间: 2021年2月11日(星期四) 凌晨4:51
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





   
替换文件 docker exec -it jd rm -rf git_pull.sh docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh这一步我也做了 在本地路径是在是找不到 半个小白 都是看着代码摸索 看了两天 真的是没搞懂
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:31 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:23 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你不看wiki教程过来问我？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
发日志来，你跟我说也没用，这个命令就是替换文件，如果替换不了遇到报错就发系统日志给我看，而且我不知道你的镜像里面有什么文件

**Comment by m360110075** [comment]
[root@phicomm-n1:~]# docker exec -it jd rm -rf git_pull.sh
[root@phicomm-n1:~]# docker exec -it jd wget https://gitee.com/SuperManito/JD-Fr
eeFuck/raw/main/git_pull.sh
--2021-02-11 04:53:30--&nbsp; https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh
Resolving gitee.com... 180.97.125.228
Connecting to gitee.com|180.97.125.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'git_pull.sh'


git_pull.sh&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;[ <=&gt;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ]&nbsp; 11.98K&nbsp; --.-KB/s&nbsp; &nbsp; in 0.02s


2021-02-11 04:53:30 (541 KB/s) - 'git_pull.sh' saved [12271]


[root@phicomm-n1:~]#





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperManito/JD-FreeFuck"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月11日(星期四) 凌晨4:51
收件人:&nbsp;"SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;;
抄送:&nbsp;"冰の琥珀"<360110075@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





   
替换文件 docker exec -it jd rm -rf git_pull.sh docker exec -it jd wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/git_pull.sh这一步我也做了 在本地路径是在是找不到 半个小白 都是看着代码摸索 看了两天 真的是没搞懂
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:31 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 大佬&nbsp; 这个git_pull.sh的位置在哪 我实在找不到了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito"<notifications@github.com&gt;; 发送时间: 2021年2月11日(星期四) 凌晨4:23 收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 那你的镜像有问题呗，docker run启动命令都是通用的，更新不了去换git_pull.sh — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你不看wiki教程过来问我？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
   
发日志来，你跟我说也没用，这个命令就是替换文件，如果替换不了遇到报错就发系统日志给我看，而且我不知道你的镜像里面有什么文件

**Comment by SuperManito** [comment]
这不是下载成功了么，你想问什么问题

**Comment by m360110075** [comment]
无法进入控制面板







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperManito"<notifications@github.com&gt;; 
发送时间: 2021年2月11日(星期四) 凌晨4:54
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





 
这不是下载成功了么，你想问什么问题

**Comment by m360110075** [comment]
这是我的镜像&nbsp;&nbsp;大佬有时间可以看下



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperManito/JD-FreeFuck"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月11日(星期四) 凌晨4:54
收件人:&nbsp;"SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;;
抄送:&nbsp;"冰の琥珀"<360110075@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





 
这不是下载成功了么，你想问什么问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

images - 副本.tar (235.78M, 2021年03月13日 05:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7363373034197a95ceb4412512630b4b505504560456085618015351524e0d5604011a52045a0c4907550f5250500c01005607003472390d58025055474314448dd2868e1a175816355e&t=exs_ftn_download&code=5c704c9d

**Comment by SuperManito** [comment]
> 这是我的镜像&nbsp;&nbsp;大佬有时间可以看下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperManito/JD-FreeFuck" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月11日(星期四) 凌晨4:54 收件人:&nbsp;"SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 抄送:&nbsp;"冰の琥珀"<360110075@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [SuperManito/JD-FreeFuck] 找到ARM镜像 求大佬指导 (#43) 这不是下载成功了么，你想问什么问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 从QQ邮箱发来的超大附件 images - 副本.tar (235.78M, 2021年03月13日 05:03 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7363373034197a95ceb4412512630b4b505504560456085618015351524e0d5604011a52045a0c4907550f5250500c01005607003472390d58025055474314448dd2868e1a175816355e&t=exs_ftn_download&code=5c704c9d

你可以试一下启动命令
    docker exec -it jd pm2 start panel/server.js

我没法看你的镜像

**Comment by m360110075** [comment]
可进入面板登录界面&nbsp; &nbsp;点提交无反应

**Comment by SuperManito** [comment]
> 可进入面板登录界面&nbsp; &nbsp;点提交无反应

我也不知道，进入容器手动改吧

**Comment by m360110075** [comment]
好的&nbsp; 麻烦您了&nbsp; 感谢指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SuperManito"<notifications@github.com&gt;; 
发送时间: 2021年2月11日(星期四) 凌晨5:48
收件人: "SuperManito/JD-FreeFuck"<JD-FreeFuck@noreply.github.com&gt;; 
抄送: "冰の琥珀"<360110075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SuperManito/JD-FreeFuck] 找到ARM镜像  求大佬指导 (#43)





  
可进入面板登录界面&nbsp; &nbsp;点提交无反应
  
我也不知道，进入容器手动改吧

**Comment by m360110075** [comment]
大佬&nbsp; 我找朋友要了个镜像&nbsp; &nbsp; 是N1 ARM的&nbsp; 你要公布出来么?

**Comment by SuperManito** [comment]
> 大佬&nbsp; 我找朋友要了个镜像&nbsp; &nbsp; 是N1 ARM的&nbsp; 你要公布出来么?

不用，TG群里很早就有了
