### ISSUE TITLE
部署成功后 win系统下的子系统 怎么找到jd这个文件啊 127.0.0.1：5678打不开啊

### ISSUE THREAD

**Issue by kira0623** [SuperManito/JD-FreeFuck#44]
部署成功后  win系统下的子系统 怎么找到jd这个文件啊 127.0.0.1：5678打不开啊

换局域网IP

**Comment by kira0623** [comment]
我是win10 子系统安装的乌班图系统

**Comment by hacken156026692** [comment]
不开新帖问了，请问一下，config文件夹为何没自动生成，手动新建一个config文件夹的话，config.sh又怎么生成？谢谢

**Comment by SuperManito** [comment]
> 不开新帖问了，请问一下，config文件夹为何没自动生成，手动新建一个config文件夹的话，config.sh又怎么生成？谢谢

不可能的，一键部署脚本都会创建的
    mkdir config
    cp sample/config.sh.sample config/config.sh
    cp sample/computer.list.sample config/crontab.list

**Comment by SuperManito** [comment]
> 部署成功后 win系统下的子系统 怎么找到jd这个文件啊 127.0.0.1：5678打不开啊

换局域网IP
