### ISSUE TITLE
企业微信应用消息推送,media_id咨询

### ISSUE THREAD

**Issue by yyx290799684** [SuperManito/JD-FreeFuck#45]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] 常规环境
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 4. 安装环境具体版本号
A：Version: v3.25.1

## 5. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A： 企业微信应用消息推送，参数填入需要media_id，该值根据文档为上传资源获取，无法预先填入。

### (2) 详细的系统日志

A：
invalid media_id, hint: [1613029828_150_b7a7885dd260d1280d4620371488c969], from ip: xxxxxxxx, more info at https://open.work.weixin.qq.com/devtool/query?e=40007

**Comment by SuperManito** [comment]
不懂，没用过
