### ISSUE TITLE
win10子系统下部署后没有JD文件的问题

### ISSUE THREAD

**Issue by kira0623** [SuperManito/JD-FreeFuck#46]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] 常规环境
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 4. 安装环境具体版本号
A：Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)

## 5. 问题类型

- [x] 部署问题
- [ ] 使用问题

## 6. 详细叙述您的问题
Win10下安装了unbutu的子系统，并且安装了nodejs 然按执行后常规环境：GITEE 部署成功！但是无法打开127.0.0.1：5678 opt目录下没有jd文件夹

### (1) 具体问题
A：环境和依赖都安装好了，能打印出版本，但是部署后没有文件，日志显示部署成功！！！

### (2) 详细的系统日志

A：------------ Permission no enough, please use user ROOT! ------------
+---------------------------------------------------+
|                                                   |
|   =============================================   |
|                                                   |
|      欢迎使用《京东薅羊毛》一键部署 For Linux     |
|                                                   |
|   =============================================   |
|                                                   |
+---------------------------------------------------+

#####################################################

            提供以下国内更新源可供选择：

#####################################################

 *  1)    中科大
 *  2)    华为云
 *  3)    阿里云
 *  4)    网易
 *  4)    搜狐
 *  6)    清华大学
 *  7)    浙江大学
 *  8)    南京大学
 *  9)    重庆大学
 *  10)   兰州大学
 *  11)   上海交通大学
 *  12)   北京交通大学
 *  13)   北京理工大学
 *  14)   南京邮电大学
 *  15)   华中科技大学
 *  16)   哈尔滨工业大学
 *  17)   北京外国语大学

#####################################################

      当前操作系统  Ubuntu 20.04
      当前系统时间  2021-02-12 09:14

#####################################################

请输入您想使用的国内更新源 [ 1~17 ]：
----------输入错误，更新源将默认使用中科大源----------
1
cp: cannot create regular file '/etc/apt/sources.list.bak': Permission denied
已备份原有 source.list 更新源文件......
sed: couldn't open temporary file /etc/apt/sedDmu0va: Permission denied
/dev/fd/63: line 199: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 200: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 201: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 202: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 203: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 204: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 205: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 206: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 207: /etc/apt/sources.list: Permission denied
/dev/fd/63: line 208: /etc/apt/sources.list: Permission denied
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
/dev/fd/63: line 1009: /: Is a directory
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

## Populating apt-get cache...

+ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Error executing command, exiting
sed: couldn't open temporary file /etc/apt/sources.list.d/sed15zhoR: Permission denied
/dev/fd/63: line 1015: /etc/apt/sources.list.d/nodesource.list: Permission denied
/dev/fd/63: line 1016: /etc/apt/sources.list.d/nodesource.list: Permission denied
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
--2021-02-12 09:14:14--  https://gitee.com/SuperManito/JD-FreeFuck/attach_files/610490/download/jd.tar.gz
Resolving gitee.com (gitee.com)... 180.97.125.228
Connecting to gitee.com (gitee.com)|180.97.125.228|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://files.gitee.com/group1/M00/16/CC/CgAAEmAdXpCACtwxAAKXWe_ypjA9610.gz?token=964c9c4dc734f678c69f0c6675d63775&ts=1613092446&attname=jd.tar.gz&disposition=attachment [following]
--2021-02-12 09:14:15--  https://files.gitee.com/group1/M00/16/CC/CgAAEmAdXpCACtwxAAKXWe_ypjA9610.gz?token=964c9c4dc734f678c69f0c6675d63775&ts=1613092446&attname=jd.tar.gz&disposition=attachment
Resolving files.gitee.com (files.gitee.com)... 180.97.125.228
Connecting to files.gitee.com (files.gitee.com)|180.97.125.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 169817 (166K) [application/octet-stream]
/opt/jd.tar.gz: Permission denied

Cannot write to ‘/opt/jd.tar.gz’ (Success).
mkdir: cannot create directory ‘/opt/jd’: Permission denied
tar (child): /opt/jd.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mkdir: cannot create directory ‘/opt/jd/config’: No such file or directory
cp: cannot stat '/opt/jd/sample/config.sh.sample': No such file or directory
cp: cannot stat '/opt/jd/sample/computer.list.sample': No such file or directory
bash: /opt/jd/git_pull.sh: No such file or directory
cp: cannot stat '/opt/jd/sample/auth.json': No such file or directory
/dev/fd/63: line 1071: cd: /opt/jd/panel: No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm WARN saveError EACCES: permission denied, open '/package-lock.json.1140701923'
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#2 No description
npm WARN !invalid#2 No repository field.
npm WARN !invalid#2 No README data
npm WARN !invalid#2 No license field.

up to date in 1.246s
found 0 vulnerabilities

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kira0623/.npm/_logs/2021-02-12T01_14_50_459Z-debug.log
/dev/fd/63: line 1074: pm2: command not found
/dev/fd/63: line 1075: cd: /opt/jd: No such file or directory
sed: can't read /opt/jd/config/crontab.list: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
sed: can't read /opt/jd/config/config.sh: No such file or directory
touch: cannot touch '/opt/jd/run-all.sh': No such file or directory
/dev/fd/63: line 1094: /opt/jd/run-all.sh: No such file or directory
bash: /opt/jd/jd.sh: No such file or directory
/dev/fd/63: line 1095: /opt/jd/run-all.sh: No such file or directory
bash: /opt/jd/jd.sh: No such file or directory
sed: can't read /opt/jd/run-all.sh: No such file or directory
sed: can't read /opt/jd/run-all.sh: No such file or directory
sed: can't read /opt/jd/run-all.sh: No such file or directory
sed: can't read run-all.sh: No such file or directory
sed: can't read run-all.sh: No such file or directory
cat: /opt/jd/run-all.sh: No such file or directory
sed: can't read run-all.sh: No such file or directory
touch: cannot touch '/opt/jd/manual-update.sh': No such file or directory
/dev/fd/63: line 1109: /opt/jd/manual-update.sh: No such file or directory

 +------- 已 启 用 控 制 面 板 功 能 -------+
 |                                          |
 | 本地访问：http://127.0.0.1:5678          |
 |                                          |
 | 外部访问：http://内部或外部IP地址:5678   |
 |                                          |
 | 初始用户名：admin，初始密码：adminadmin  |
 |                                          |
 +------------------------------------------+

 --------------------- 一键部署成功，请执行 bash run-all.sh 命令开始你的薅羊毛行为 ---------------------
 +=====================================================================================================+
 |                                                                                                     |
 | 定义：run-all.sh 为本人编写的一键执行所有活动脚本，manual-update.sh 为本人编写的一键更新脚本        |
 |                                                                                                     |
 |       如果想要单独执行或延迟执行特定活动脚本，请通过命令 bash jd.sh 查看教程                        |
 |                                                                                                     |
 | 注意：1. 本项目文件与一键脚本所在的目录为/opt/jd                                                      |
 |                                                                                                     |
 |       2. 为了保证脚本的正常运行，请不要更改任何组件的位置以避免出现未知的错误                       |
 |                                                                                                     |
 |       3. 手动执行 run-all 脚本后无需守在电脑旁，会自动在最后运行挂机活动脚本                        |
 |                                                                                                     |
 |       4. 执行 run-all 脚本期间如果卡住，可按回车键尝试或通过命令 Ctrl + Z 跳过继续执行剩余活动脚本  |
 |                                                                                                     |
 |       5. 由于京东活动一直变化可能会出现无法参加活动、报错等正常现象，可手动更新活动脚本             |
 |                                                                                                     |
 |       6. 如果需要更新活动脚本，请执行 bash manual-update.sh 命令进行一键更新即可                    |
 |                                                                                                     |
 |       7. 之前填入的 Cookie 部分内容具有一定的时效性，若提示失效请根据教程重新获取并通过命令手动更新 |
 |                                                                                                     |
 |       8. 我不是活动脚本的开发者，但后续使用遇到任何问题都可访问本项目寻求帮助，制作不易，理解万岁   |
 |                                                                                                     |
 +=====================================================================================================+
 --------------------- 更多帮助请访问:  https://github.com/SuperManito/JD-FreeFuck ---------------------

**Comment by SuperManito** [comment]
别再发了，控制面板换WIN10局域网P打开，至于opt下为什么没有目录就不要问我了，自己解决，我脚本没问题，不要质疑
