### ISSUE TITLE
能不能放个国内的下载地址，下载太慢了

### ISSUE THREAD

**Issue by 3136083906** [SuperManito/JD-FreeFuck#47]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [ x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [ x] 是
- [ ] 否

## 2. 安装平台

- [ ] 常规环境
- [ ] VPS
- [ ]x 软路由
- [ ] NAS
- [ ] Other

## 3. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ x] Docker
- [ ] Other

## 4. 安装环境具体版本号
A：

## 5. 问题类型

- [ x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：国内下载太慢了

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
不能，自己用迅雷去加速，Gitee有上传文件限制，最高不超过100M，只能用Github
