### ISSUE TITLE
有没有基于ARM的Armbian能用的镜像

### ISSUE THREAD

**Issue by animal-x** [SuperManito/JD-FreeFuck#49]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] 常规环境
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 3. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [x] Other

## 4. 安装环境具体版本号
A：Armbian 5.88

## 5. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
没有，有我就放上去了
