### ISSUE TITLE
部署后支持面板访问吗？

### ISSUE THREAD

**Issue by wingser** [SuperManito/JD-FreeFuck#5]
部署后支持面板访问吗？对小白友好点。

**Comment by SuperManito** [comment]
暂时不支持，我还没用过这个功能，不知道具体能干什么，感谢你的建议，预计5天内完成适配，目前还在开发对于各个Linux发行版的支持，我这个脚本的适用对象门槛比较低，使用这方面的高级功能我没法教
你可以根据原作者Wiki教程自行安装一下 https://github.com/EvineDeng/jd-base/wiki/Panel

**Comment by wingser** [comment]
谢谢回复

**Comment by SuperManito** [comment]
你要的功能已加

附3. 如果需要使用 控制面板 功能，安装命令如下：

    bash <(curl -L https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install-panel.sh)
注：此功能可用于在浏览器编辑配置文件、配置定时运行脚本、自定义脚本等功能。

**Comment by SuperManito** [comment]
> 部署后支持面板访问吗？对小白友好点。

控制面板已加

附3. 如果需要使用 控制面板 功能，安装命令如下：

    bash <(curl -L https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install-panel.sh)
注：此功能可用于在浏览器编辑配置文件、配置定时运行脚本、自定义脚本等功能。

**Comment by wingser** [comment]
多谢大佬，辛苦辛苦！
