### ISSUE TITLE
jd.sh这个文件路径

### ISSUE THREAD

**Issue by shu0802** [SuperManito/JD-FreeFuck#53]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [x] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志

A：

方法里说的jd.sh文件路径?
![1613395318(1)](https://user-images.githubusercontent.com/43750373/107951932-0aceb180-6fd4-11eb-9751-0f9cae63a66d.jpg)

**Comment by SuperManito** [comment]
什么路径？就在jd.sh那个文件添加一行变量内容

**Comment by shu0802** [comment]
> 什么路径？就在jd.sh那个文件添加一行变量内容
jd.sh的文件在运行后的哪个文件夹里

**Comment by shu0802** [comment]
> 什么路径？就在jd.sh那个文件添加一行变量内容

运行后的路径在哪里？
