### ISSUE TITLE
希望能增加一个卸载脚本

### ISSUE THREAD

**Issue by sw1999** [SuperManito/JD-FreeFuck#54]
安装了发现没有卸载，在vps测试了感觉不错，打算卸载换微型机本地折腾。

删除定时任务，然后删除 /opt/jd 应该也可以了吧？

**Comment by SuperManito** [comment]
。。。不需要什么卸载脚本

**Comment by SuperManito** [comment]
- 执行两条命令就行
    #删除项目文件
    rm -rf /opt/jd
    #卸载软件包
    apt/yum remove -y git perl moreutils nodejs npm

**Comment by sw1999** [comment]
> * 执行两条命令就行
>   ```
>   #删除项目文件
>   rm -rf /opt/jd
>   #卸载软件包
>   apt/yum remove -y git perl moreutils nodejs npm
>   ```

感谢老大回复，我试试
