### ISSUE TITLE
明天都需要重新运行allrun

### ISSUE THREAD

**Issue by Akiyama730** [SuperManito/JD-FreeFuck#55]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x ] 是
- [ ] 否

Q：是否阅读了项目须知？

- [ x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x ] x86_64
- [ ] ARM

## 4. 安装环境

- [x ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：18.04.3

## 6. 问题类型

- [ ] 部署问题
- [x ] 使用问题

## 7. 详细叙述您的问题
运行allrun之后。第二天依旧需要重新运行一遍才生效。
### (1) 具体问题
A：crontab -e命令看了任务，里面也有。从头到尾都是root

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
什么叫“运行allrun之后。第二天依旧需要重新运行一遍才生效”？定时任务跟run-all一键脚本就不是一回事
