### ISSUE TITLE
执行bash manual-update.sh，cookie无法失败

### ISSUE THREAD

**Issue by xy364515640** [SuperManito/JD-FreeFuck#56]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [ x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x ] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x ] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [x ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：debian10

## 6. 问题类型

- [ ] 部署问题
- [x ] 使用问题

### (1) 具体问题
A：TG看到推送了新项目女装盲盒，自己手动bash manual-update.sh
，然后运行显示下面，cookie为0，运行其他项目也不行了，log显示【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取

### (2) 详细的系统日志

A：==============📣系统通知📣==============
女装盲盒抽京豆
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/

🔔女装盲盒抽京豆, 结束! 🕛 0.022 秒

[log.txt](https://github.com/SuperManito/JD-FreeFuck/files/6008196/log.txt)

**Comment by SuperManito** [comment]
人家都提示你了，你自己cookie配的有问题，仔细检查config.sh
