### ISSUE TITLE
提示获取cookie

### ISSUE THREAD

**Issue by master89-2018** [SuperManito/JD-FreeFuck#57]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 3. 安装平台架构

- [ ] x86_64
- [x] ARM

## 4. 安装环境

- [ ] Ubuntu
- [x] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：buster

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

## 7. 详细叙述您的问题
今天中午过后就提示需要获取cookie
### (1) 具体问题
A：cookie  没有失效

### (2) 详细的系统日志

A：
京东快递签到
【提示】请先获取京东账号一cookie
直接使用NobyDa的京东签到获取
https://bean.m.jd.com/bean/signIndex.action

🔔京东快递签到, 结束! 🕛 0.139 秒

root@aml:/opt/jd# bash jd.sh kd now
"/opt/jd/config/crontab.list":111: bad command
errors in crontab file, can't install.

**Comment by SuperManito** [comment]
这啥啊，"errors in crontab file, can't install."，crontab软件包没装，我也不知道你用的什么环境

**Comment by wrxx2019** [comment]
> lxk0301更新完炸了，正在寻找解决办法

现在好像没事了，manual update完了测试几个脚本运行都正常

**Comment by Matear890** [comment]
我的还没解决，群里其他大佬都可以跑么

**Comment by SuperManito** [comment]
> 在好像没事了，manual update完了测试几个脚本运行都正常

真的假的，我的现在还炸着呢

**Comment by SuperManito** [comment]
@Matear890 @wrxx2019 @master89-2018 已解决，原因是因lxk0301大佬更新了package.json，解决办法是重新部署，删除/opt/jd重新用我的脚本一键部署即可
