### ISSUE TITLE
一键更新错误

### ISSUE THREAD

**Issue by musaart** [SuperManito/JD-FreeFuck#58]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志

A：

**Comment by musaart** [comment]
阿里云部署 cetos7.6

**Comment by musaart** [comment]
[root@XXXXX]# bash manual-update.sh

--------------------------------------------------------------

系统时间：2021-02-20 02:22:30

JS脚本目录：/opt/jd/scripts

--------------------------------------------------------------

"/opt/jd/config/crontab.list":111: bad command
errors in crontab file, can't install.
Fetching origin
HEAD is now at 0b3ebfd fix

js脚本更新完成...

**Comment by SuperManito** [comment]
炸了，去看通知
