### ISSUE TITLE
多个账号获取互助码为什么获取不到

### ISSUE THREAD

**Issue by jack-ZG** [SuperManito/JD-FreeFuck#59]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x ] 是
- [ ] 否

Q：是否阅读了项目须知？

- [ x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [ x] 使用问题

### (1) 具体问题
A：多用户获取不完整互助码，在使用format_share_jd_code与jd_get_share_code脚本的时候。例如4个cookies；
只能获取到1，2，3，4会遗漏不显示。如果5个cookies 同样会少显示一个用户的互助码。

### (2) 详细的系统日志

A：====================共有4个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2/20/2021, 1:41:42 PM=====================

注：临时活动的互助码不添加到此处，如有需要请手动运行对应临时活动脚本

======账号1开始======
【账号1（001）东东工厂】x
【账号1（001）京喜工厂】x
【账号1（001）京喜农场】x
【账号1（001）京东萌宠】x
【账号1（001）种豆得豆】x
【账号1（001）京东农场】x
【账号1（001）京东赚赚】x
【账号1（001）crazyJoy】x
【账号1（001）闪购盲盒】x
======账号1结束======

======账号2开始======
【账号2（002）东东工厂】x
【账号2（002）京喜工厂】x==
【账号2（002）京喜农场】x
【账号2（002）种豆得豆】x
【账号2（002）京东农场】x
【账号2（002）京东赚赚】x
【账号2（002）crazyJoy】x==
【账号2（002）闪购盲盒】x
======账号2结束======

======账号4开始======
【账号4（003）东东工厂】x-x
【账号4（003）京喜农场】x
【账号4（003）种豆得豆】x
【账号4（003）京东农场】x
【账号4（003）京东赚赚】x
【账号4（003）crazyJoy】x==
【账号4（003）闪购盲盒】x-x
======账号4结束======

获取互助码, 结束!  4.177 秒

**Comment by SuperManito** [comment]
这个跟我没关系，我说了活动脚本与我无关，你可以用2月11号更新通知里面的脚本，另一个大佬写的，可以用
