### ISSUE TITLE
bug：自动更新脚本会导致通知功能失效

### ISSUE THREAD

**Issue by PwnerZhang** [SuperManito/JD-FreeFuck#6]
如题。具体表现为运行自动更新脚本后会使sendNotify.js被覆盖导致上一次填写的通知工具的密钥丢失。

**Comment by SuperManito** [comment]
不可能，你可以查看一下`manual-update.sh`这个文件的代码，根本就没有涉及配置文件

**Comment by PwnerZhang** [comment]
您好，由于我并非是安找您推荐的配置通知的方式配置的，我是直接在`/myid/jd/scripts`中的`sendNotify.js`配置的，所以运行完`manual-update.sh`确实会被覆盖。如果在`配置文件`中配置，的确不会被覆盖。

**Comment by SuperManito** [comment]
我不是该项目的开发者，我不清楚你的使用方式更不懂你在说什么，我的`manual-update.sh`脚本里只有`bash git_pull.sh`涉及项目文件改动，这是作者给的更新命令，其余都是改的`run-all.sh`一键运行所有活动脚本，这是我自己加的，如果更新会覆盖`sendNotify,js`这个文件，我建议你去问原作者https://github.com/EvineDeng/jd-base/issues
