### ISSUE TITLE
大佬，那么docker版该如何更新到20号的版本呢？

### ISSUE THREAD

**Issue by zhaojie199512** [SuperManito/JD-FreeFuck#60]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [x] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：docketr版本如何更新到20号的新版本，还是执行一键更新脚本，或者是重新部署容器？

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
你的镜像要是现在能正常用换个配置文件就行了，如果用不了了就删除容器重搭

**Comment by zhaojie199512** [comment]
> 你的镜像要是现在能正常用换个配置文件就行了，如果用不了了就删除容器重搭

目前正常使用，那我就从lcx大佬那里找个config.sh拷进去是不是就可以了？

**Comment by zhaojie199512** [comment]
> > 你的镜像要是现在能正常用换个配置文件就行了，如果用不了了就删除容器重搭
> 
> 目前正常使用，那我找个拷进去是不是就可以了？没看到新的配置文件去哪里找。。。

**Comment by SuperManito** [comment]
> > > 你的镜像要是现在能正常用换个配置文件就行了，如果用不了了就删除容器重搭
> > 
> > 
> > 目前正常使用，那我找个拷进去是不是就可以了？没看到新的配置文件去哪里找。。。是不是就是您这个项目里名为config.sh.sample的文件？

嗯，两个教程里都有命令，自己换吧
