### ISSUE TITLE
在PC环境下，用github的方式安装，无反应

### ISSUE THREAD

**Issue by do-not-stop** [SuperManito/JD-FreeFuck#61]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：Ubuntu18.04

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：在PC环境下，用github的方式安装，无反应

### (2) 详细的系统日志

A：
![无反应](https://user-images.githubusercontent.com/50165655/108626629-174b8200-748c-11eb-9115-228ca6bcca13.png)

**Comment by SuperManito** [comment]
你网有问题
