### ISSUE TITLE
升级出错

### ISSUE THREAD

**Issue by boshi116** [SuperManito/JD-FreeFuck#62]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：输入命令  bash <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)

### (2) 详细的系统日志

A：最后提示  正在获取 origin
Username for 'https://gitee.com': 输入用户名和密码显示下面提示
Password for ' 
remote: You do not have permission to pull the repository
fatal: 无法访问 'https://gitee.com/lxk0301/jd_scripts/'：The requested URL returned error: 403
error: 不能获取 origin
HEAD 现在位于 3ad49ab 修改文件名字

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by SuperManito** [comment]
别升级了，我已经删了脚本了，重新部署吧，都升级不了
