### ISSUE TITLE
更新脚本和runall的sh没有见到

### ISSUE THREAD

**Issue by phonezhou** [SuperManito/JD-FreeFuck#63]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [x] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志

A：

**Comment by phonezhou** [comment]
正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的

**Comment by SuperManito** [comment]
> 正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的

你到底是docker还是vps？

**Comment by pppscn** [comment]
> > 正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的
> 
> 你到底是docker还是vps？

https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Install-(-Soft-Router-&-NAS-)

6. 运行一键脚本
docker exec -it jd bash run-all.sh

7. 更新活动脚本
docker exec -it jd bash manual-update.sh

应该是指着两个脚本没有见到

**Comment by SuperManito** [comment]
> > > 正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的
> > 
> > 
> > 你到底是docker还是vps？
> 
> https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Install-(-Soft-Router-&-NAS-)
> 
> 1. 运行一键脚本
>    docker exec -it jd bash run-all.sh
> 2. 更新活动脚本
>    docker exec -it jd bash manual-update.sh
> 
> 应该是指着两个脚本没有见到

你啥时候部署的？

**Comment by SuperManito** [comment]
> > > 正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的
> > 
> > 
> > 你到底是docker还是vps？
> 
> https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Install-(-Soft-Router-&-NAS-)
> 
> 1. 运行一键脚本
>    docker exec -it jd bash run-all.sh
> 2. 更新活动脚本
>    docker exec -it jd bash manual-update.sh
> 
> 应该是指着两个脚本没有见到

我有个地方写错了

**Comment by SuperManito** [comment]
> 正常部署后，manual-update.sh和run_all.sh都没有见到，请问在哪里可以找到。docker的

现在可以了，要么你重新执行一下那个脚本，会重装安装活动脚本，如果你网不好就执行下面的命令
    docker exec -it jd /bin/bash
    touch manual-update.sh
    cat >manual-update.sh <<\EOF
    #!/bin/bash
    ## Author:SuperManito
   ## Modified:2021-2-21
   
   ## 执行更新命令
   bash git_pull.sh
    ## 重新生成一键执行所有活动脚本
    rm -rf run-all.sh
    touch run-all.sh
    bash jd.sh | grep -o 'jd_[a-z].*' >run-all.sh
    bash jd.sh | grep -o 'jx_[a-z].*' >>run-all.sh
    sed -i 's/^/bash jd.sh &/g' run-all.sh
    sed -i 's/.js/ now/g' run-all.sh
    sed -i '1i\#!/bin/bash' run-all.sh
    sed -i "s/bash jd.sh jd_delCoupon now//g" run-all.sh  #不执行京东家庭号任务
    sed -i "s/bash jd.sh jd_family now//g" run-all.sh     #不执行删除优惠券任务
    cat run-all.sh | grep jd_crazy_joy_coin -wq
    if [ $? -eq 0 ];then
      sed -i "s/bash jd.sh jd_crazy_joy_coin now//g" run-all.sh
      echo "bash jd.sh jd_crazy_joy_coin now" >>run-all.sh
    fi
    sed -i '/^\s*$/d' run-all.sh
    ## 配置定时任务
    sed -i "s#/home/myid/jd/##g" config/crontab.list
    EOF
    exit

**Comment by SuperManito** [comment]
抱歉
