### ISSUE TITLE
自动任务问题

### ISSUE THREAD

**Issue by Kafeyun** [SuperManito/JD-FreeFuck#65]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否仔细阅读了部署前须知？

- [x] 是
- [ ] 否

Q：是否仔细阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：Docker version 19.03.6

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：我之前是使用evine的docker2，然后转到这边，按照教程部署并修改config和crontab后，发现没有log输出，手动执行才有

### (2) 详细的系统日志

A：

**Comment by SuperManito** [comment]
我教程里没有修改crontab定时文件啊，你是刚装完就去看log了吗？定时任务的格式应该是这样的：
5 9 * * * bash jd.sh jd_bean_change

**Comment by SuperManito** [comment]
`crontab -l`看一下有没有内容，如果有就没问题已经写入系统了

**Comment by Kafeyun** [comment]
> 我教程里没有修改crontab定时文件啊，你是刚装完就去看log了吗？定时任务的格式应该是这样的：
> 5 9 * * * bash jd.sh jd_bean_change



> 我教程里没有修改crontab定时文件啊，你是刚装完就去看log了吗？定时任务的格式应该是这样的：
> 5 9 * * * bash jd.sh jd_bean_change

谢谢大佬，问题解决了，我是装完就去看发现没log，然后又增加了自己脚本的定时任务，发现定时到了还是没log输出，原来是忘记上传自己的脚本了。。。

**Comment by Kafeyun** [comment]
> `crontab -l`看一下有没有内容，如果有就没问题已经写入系统了

有内容，感谢大佬维护，这样我就不用自己挨个改sh了哈哈，全部去部署你的

**Comment by SuperManito** [comment]
QAQ 不客气，觉得项目不错的话可以打赏，感谢

**Comment by Kafeyun** [comment]
> QAQ 不客气，觉得项目不错的话可以打赏，感谢

没问题

**Comment by shenhui0929** [comment]
大佬我也是docker2转战过来的，`遇到`crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事

**Comment by SuperManito** [comment]
> 大佬我也是docker2转战过来的，`遇到`crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事

能更新吗？什么时候部署的？crontab.list格式对吗

**Comment by shenhui0929** [comment]
大佬我也是docker2转战过来的，`遇到`crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事

**Comment by Kafeyun** [comment]
crontab -l能显示所有脚本，但是刚才发现只有一个脚本自动运行了，其他脚本过了定时还是没运行，包括我自己添加上去的

**Comment by shenhui0929** [comment]
更新没问题 ，下午部署的，crontab.list格式没动过 docker run完自动生成的，我对比过之前evnie大佬的 一样



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SuperManito <notifications@github.com&gt;
发送时间: 2021年2月22日 19:33
收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt;
抄送: shenhui0929 <shen413204402@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65)





  
大佬我也是docker2转战过来的，遇到crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事
  
能更新吗？什么时候部署的？crontab.list格式对吗

**Comment by Kafeyun** [comment]
> 更新没问题 ，下午部署的，crontab.list格式没动过 docker run完自动生成的，我对比过之前evnie大佬的 一样 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: SuperManito <notifications@github.com&gt; 发送时间: 2021年2月22日 19:33 收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt; 抄送: shenhui0929 <shen413204402@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65) 大佬我也是docker2转战过来的，遇到crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事 能更新吗？什么时候部署的？crontab.list格式对吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

试试看重启容器，看看能不能更新进去

**Comment by shenhui0929** [comment]
好的 &nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kafeyun <notifications@github.com&gt;
发送时间: 2021年2月22日 19:51
收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt;
抄送: shenhui0929 <shen413204402@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65)





  
更新没问题 ，下午部署的，crontab.list格式没动过 docker run完自动生成的，我对比过之前evnie大佬的 一样 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: SuperManito <notifications@github.com&gt; 发送时间: 2021年2月22日 19:33 收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt; 抄送: shenhui0929 <shen413204402@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65) 大佬我也是docker2转战过来的，遇到crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事 能更新吗？什么时候部署的？crontab.list格式对吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
试试看重启容器，看看能不能更新进去

**Comment by SuperManito** [comment]
> crontab -l能显示所有脚本，但是刚才发现只有一个脚本自动运行了，其他脚本过了定时还是没运行，包括我自己添加上去的

那我也不知道了。。。你研究研究吧，我不知道你对crontab的定时规则是否理解正确

**Comment by SuperManito** [comment]
> 更新没问题 ，下午部署的，crontab.list格式没动过 docker run完自动生成的，我对比过之前evnie大佬的 一样 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: SuperManito <notifications@github.com&gt; 发送时间: 2021年2月22日 19:33 收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt; 抄送: shenhui0929 <shen413204402@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65) 大佬我也是docker2转战过来的，遇到crontab -l显示没有crontab. List下的所有定时脚本 请问是怎么回事 能更新吗？什么时候部署的？crontab.list格式对吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大家用的镜像都是一样的，如果你严格安装我的教程步骤来应该不会有什么问题。。。

**Comment by Kafeyun** [comment]
> > crontab -l能显示所有脚本，但是刚才发现只有一个脚本自动运行了，其他脚本过了定时还是没运行，包括我自己添加上去的
> 
> 那我也不知道了。。。你研究研究吧，我不知道你对crontab定时规则的理解是否正确

我发现定时任务里面，只有整点执行的任务会自动运行，可能是randomdelay的问题？

**Comment by jackymardt** [comment]
我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里

**Comment by SuperManito** [comment]
我知道了，可能是目录不对

**Comment by Kafeyun** [comment]
> 我知道了，可能是目录不对

但是整点的任务比如jd_global又成功在20点成功自动运行过一次

**Comment by SuperManito** [comment]
你试下这个命令，然后告诉我结果`sed -i "s#bash jd.sh #bash /jd/jd.sh #g" config/crontab.list`

**Comment by Kafeyun** [comment]
> sed -i "s#bash jd.sh #bash /jd/jd.sh #g" config/crontab.list

没有回应
![image](https://user-images.githubusercontent.com/49928274/108713474-411bac00-7553-11eb-87cb-ad4edebf2c75.png)

**Comment by SuperManito** [comment]
> > sed -i "s#bash jd.sh #bash /jd/jd.sh #g" config/crontab.list
> 
> 进入docker执行，没有回应
> ![image](https://user-images.githubusercontent.com/49928274/108713474-411bac00-7553-11eb-87cb-ad4edebf2c75.png)


本来就没有输出信息，你看看日志有没有脚本运行

**Comment by Kafeyun** [comment]
> > > sed -i "s#bash jd.sh #bash /jd/jd.sh #g" config/crontab.list
> > 
> > 
> > 进入docker执行，没有回应
> > ![image](https://user-images.githubusercontent.com/49928274/108713474-411bac00-7553-11eb-87cb-ad4edebf2c75.png)
> 
> 本来就没有输出信息，你看看日志有没有脚本运行

目前没有，我观察观察

**Comment by Kafeyun** [comment]
> 我知道了，可能是目录不对

发现问题所在，把定时任务 bash /jd/jd.sh jd_xxx 改成 bash jd jd_xxx 即可正常自动运行，我记得evine这个是做了重映射的，可能跟你直装的不太一样

**Comment by Kafeyun** [comment]
> 我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里

把定时任务 bash /jd/jd.sh jd_xxx 改成 bash jd jd_xxx 即可正常自动运行，暂时的解决办法

**Comment by SuperManito** [comment]
> > 我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里
> 
> 运行sed -i "s#bash jd.sh #bash jd #g" config/crontab.list并重启容器即可正常自动运行，暂时的解决办法

你是说把jd后面那个.sh去掉就行了是吧

**Comment by Kafeyun** [comment]
> > > 我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里
> > 
> > 
> > 运行sed -i "s#bash jd.sh #bash jd #g" config/crontab.list并重启容器即可正常自动运行，暂时的解决办法
> 
> 你是说把jd后面那个.sh去掉就行了是吧

对的

**Comment by SuperManito** [comment]
> > > > 我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里
> > > 
> > > 
> > > 运行sed -i "s#bash jd.sh #bash jd #g" config/crontab.list并重启容器即可正常自动运行，暂时的解决办法
> > 
> > 
> > 你是说把jd后面那个.sh去掉就行了是吧
> 
> 对的

我更新一下我的脚本就可以了

**Comment by Kafeyun** [comment]
> > > > > 我也是docker2转来的，在群晖和unraid上都试了，遇到和上面类似的问题，crontab -l 能显示所有定时任务，git_pull正常，查看docker日志，显示定时任务在运行，但实际没有运行，也没有输出任务日志到log文件夹，但是所有任务手动是可以运行的，运行后log文件夹会出现相应的日志文件夹。不知道问题出在哪里
> > > > 
> > > > 
> > > > 运行sed -i "s#bash jd.sh #bash jd #g" config/crontab.list并重启容器即可正常自动运行，暂时的解决办法
> > > 
> > > 
> > > 你是说把jd后面那个.sh去掉就行了是吧
> > 
> > 
> > 对的
> 
> 我更新一下我的脚本就可以了

感谢大佬

**Comment by sw1999** [comment]
黑群晖 Docker好像也发现了同样问题，查看日志都没有一个自动运行，明天等老大的脚本更新，重新部署一次测试。

另外顺便提一个意见，Docker安装教程第三步，导入镜像的命令前。增加两行命令：
mkdir /opt/jd/config
mkdir /opt/jd/log

那些不会看命令的，新安装系统的会导入失败。

**Comment by Kafeyun** [comment]
> 黑群晖 Docker好像也发现了同样问题，查看日志都没有一个自动运行，明天等老大的脚本更新，重新部署一次测试。
> 
> 另外顺便提一个意见，Docker安装教程第三步，导入镜像的命令前。增加两行命令：
> mkdir /opt/jd/config
> mkdir /opt/jd/log
> 
> 那些不会看命令的，新安装系统的会导入失败。

目前进入容器运行sed -i "s#bash jd.sh #bash jd #g" config/crontab.list并重启容器即可正常自动运行，暂时的解决办法

**Comment by SuperManito** [comment]
> 黑群晖 Docker好像也发现了同样问题，查看日志都没有一个自动运行，明天等老大的脚本更新，重新部署一次测试。
> 
> 另外顺便提一个意见，Docker安装教程第三步，导入镜像的命令前。增加两行命令：
> mkdir /opt/jd/config
> mkdir /opt/jd/log
> 
> 那些不会看命令的，新安装系统的会导入失败。

不会啊，我测试的时候不创建挂载目录文件夹也可以直接启动容器

**Comment by Kafeyun** [comment]
> > 黑群晖 Docker好像也发现了同样问题，查看日志都没有一个自动运行，明天等老大的脚本更新，重新部署一次测试。
> > 另外顺便提一个意见，Docker安装教程第三步，导入镜像的命令前。增加两行命令：
> > mkdir /opt/jd/config
> > mkdir /opt/jd/log
> > 那些不会看命令的，新安装系统的会导入失败。
> 
> 不会啊，我测试的时候不创建挂载目录文件夹也可以直接启动容器

对啊，不用提前创建的，创建了如果里面有东西有时候出错

**Comment by SuperManito** [comment]
@shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令`docker exec -it jd`进入容器执行下面的命令:

    sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh
    sed -i "s#/home/myid/jd/##g" config/crontab.list
    bash manual-update.sh
然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的`/home/myid`目录，我在源码中找不到相关内容没法改

**Comment by SuperManito** [comment]
因为我根本没测试过定时这个东西，我以为`jd.sh`和`jd`没区别。。。本来就是指的`jd.sh`那个文件

**Comment by shenhui0929** [comment]
好的 感谢大佬这么晚还在奋战



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SuperManito <notifications@github.com&gt;
发送时间: 2021年2月22日 22:22
收件人: SuperManito/JD-FreeFuck <JD-FreeFuck@noreply.github.com&gt;
抄送: shenhui0929 <shen413204402@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[SuperManito/JD-FreeFuck] 自动任务问题 (#65)





 
@shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令docker exec -it jd进入容器执行下面的命令:
 sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh sed -i "s#/home/myid/jd/##g" config/crontab.list bash manual-update.sh  
然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的/home/myid目录，我在源码中找不到相关内容没法改

**Comment by SuperManito** [comment]
> @shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令`docker exec -it jd`进入容器执行下面的命令:
> 
> ```
> sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh
> sed -i "s#/home/myid/jd/##g" config/crontab.list
> bash manual-update.sh
> ```
> 
> 然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的`/home/myid`目录，我在源码中找不到相关内容没法改

你们重新去执行更新命令吧，看项目通知

**Comment by sw1999** [comment]
> > @shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令`docker exec -it jd`进入容器执行下面的命令:
> > ```
> > sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh
> > sed -i "s#/home/myid/jd/##g" config/crontab.list
> > bash manual-update.sh
> > ```
> > 
> > 
> > 然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的`/home/myid`目录，我在源码中找不到相关内容没法改
> 
> 你们重新去执行更新命令吧，看项目通知

root@DiskStation:/opt/jd# docker run -dit \
> -v /opt/jd/scripts:/jd/scripts `# 设置活动脚本的主机挂载目录为/opt/jd/scripts` \
> -v /opt/jd/config:/jd/config `# 设置配置文件的主机挂载目录为/opt/jd/config` \
> -v /opt/jd/log:/jd/log `# 设置日志的主机挂载目录为/opt/jd/log` \
> -p 5678:5678 `# 设置端口映射，格式为 "主机端口:容器端口"，主机端口号可自定义` \
> -e ENABLE_HANGUP=true `# 启用挂机功能` \
> -e ENABLE_WEB_PANEL=true `# 启用控制面板功能` \
> --name jd `# 设置容器名为jd` \
> --network bridge `# 设置网络为桥接，直连主机` \
> --hostname jd `# 设置主机名为jd` \
> --restart always `# 设置容器开机自启` \
> evinedeng/jd:gitee
246f1aa1ecee7b174710cb69c0484888dd66c17d4bc607830d86a11844a339f0
docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.

**Comment by SuperManito** [comment]
> docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.

这不都告诉你报错原因了吗`docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.`可能你的其它容器占用了这个目录

**Comment by sw1999** [comment]
> > @shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令`docker exec -it jd`进入容器执行下面的命令:
> > ```
> > sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh
> > sed -i "s#/home/myid/jd/##g" config/crontab.list
> > bash manual-update.sh
> > ```
> > 
> > 
> > 然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的`/home/myid`目录，我在源码中找不到相关内容没法改
> 
> 你们重新去执行更新命令吧，看项目通知



> > docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.
> 
> 这不都告诉你报错原因了吗`docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.`可能你的其它容器占用了这个目录

我特意删除了opt/jd/scripts文件夹，再创建docker容器就会失败，难道是我的黑群晖问题？另外我这边测试脚本定时任务还是很多脚本没有执行，例如金融的那只提鹅，正在安装Ubuntu，不用docker了

**Comment by SuperManito** [comment]
@shenhui0929 @sw1999 @Kafeyun @jackymardt 下午又更新了一次，这次真没问题了，抱歉

**Comment by SuperManito** [comment]
> > > @shenhui0929 @sw1999 @Kafeyun @jackymardt 你们已经部署的通过命令`docker exec -it jd`进入容器执行下面的命令:
> > > ```
> > > sed -i "s|/home/myid#|/home/myid/jd/jd.sh#jd|g" manual-update.sh
> > > sed -i "s#/home/myid/jd/##g" config/crontab.list
> > > bash manual-update.sh
> > > ```
> > > 
> > > 
> > > 然后以后更新就用我的一键更新脚本，git_pull.sh同步新的定时任务时还会带着错误的`/home/myid`目录，我在源码中找不到相关内容没法改
> > 
> > 
> > 你们重新去执行更新命令吧，看项目通知
> 
> > > docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.
> > 
> > 
> > 这不都告诉你报错原因了吗`docker: Error response from daemon: Bind mount failed: '/opt/jd/scripts' does not exists.`可能你的其它容器占用了这个目录
> 
> 我特意删除了opt/jd/scripts文件夹，再创建docker容器就会失败，难道是我的黑群晖问题？另外我这边测试脚本定时任务还是很多脚本没有执行，例如金融的那只提鹅，正在安装Ubuntu，不用docker了

你之前的容器没删占用目录了吧

**Comment by shenhui0929** [comment]
感谢大佬持之以恒的修复
