### ISSUE TITLE
运行run-all.sh不断出现api调用失败

### ISSUE THREAD

**Issue by phonezhou** [SuperManito/JD-FreeFuck#66]
京豆变动通知 API请求失败，请检查网路重试
第1页: undefined
"Invalid character in header content [\"cookie\"]"
京豆变动通知 API请求失败，请检查网路重试
第1页: undefined

**Comment by phonezhou** [comment]
请问是我部署有问题吗？

**Comment by SuperManito** [comment]
是，不是网络问题就是黑号了
