### ISSUE TITLE
Publickey無法訪問

### ISSUE THREAD

**Issue by hacken156026692** [SuperManito/JD-FreeFuck#68]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x ] 是
- [ ] 否

Q：是否仔细阅读了部署前须知？

- [x ] 是
- [ ] 否

Q：是否仔细阅读了项目须知？

- [x ] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x ] Other

## 3. 安装平台架构

- [ ] x86_64
- [ ] ARM
- [ x] AARCH64

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ x] Other

## 5. 安装环境具体版本号
A：termux 0.108.119

## 6. 问题类型

- [x ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：部署完，運行bash git_pull.sh時出錯

### (2) 详细的系统日志

A：
Cloning into '/data/data/com.termux/files/home/opt/jd/scripts'...
git@gitee.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

js脚本更新失败，请检查原因或再次运行git_pull.sh...

/data/data/com.termux/files/home/opt/jd/config/config.sh: line 3: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 4: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 7: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 20: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 21: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 34: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 35: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 54: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 55: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 63: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 64: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 72: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 73: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 77: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 78: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 84: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 85: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 90: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 91: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 96: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 100: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 104: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 108: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 111: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 116: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 119: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 123: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 124: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 131: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 132: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 136: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 137: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 148: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 155: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 156: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 167: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 174: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 175: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 186: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 193: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 194: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 205: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 212: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 213: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 224: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 231: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 232: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 243: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 250: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 251: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 262: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 269: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 270: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 285: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 292: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 293: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 305: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 306: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 317: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 324: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 325: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 336: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 343: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 344: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 355: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 362: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 363: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 375: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 382: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 383: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 392: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 393: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 397: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 398: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 402: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 403: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 408: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 409: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 413: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 414: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 418: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 419: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 424: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 425: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 430: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 431: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 437: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 438: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 444: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 445: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 449: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 450: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 454: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 455: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 459: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 460: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 467: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 468: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 472: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 473: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 477: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 478: $'\r': command not found
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 486: syntax error near unexpected token `elif'
/data/data/com.termux/files/home/opt/jd/config/config.sh: line 486: `elif [ $(date "+%w") -eq 3 ] && [ $(date "+%H") -ge'9 ] && [ $(date "+%H") -lt 14 ]; then
Can't open /data/data/com.termux/files/home/opt/jd/scripts/jd_joy_run.js: No such file or directory.

**Comment by SuperManito** [comment]
您挺特殊啊，不仅这Linux我没听说过不在我项目的支持范围内，这架构我也不了解。。。日志也没发完整，那些软件包我也不清楚你装没装上，根据报错信息来看是SSH私钥没装上

**Comment by PwnerZhang** [comment]
I have the same problem.The following error is prompted after running the script：
`Cloning into '/opt/jd/scripts'...
ssh: connect to host gitee.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by SuperManito** [comment]
> I have the same problem.The following error is prompted after running the script：
> `Cloning into '/opt/jd/scripts'...
> ssh: connect to host gitee.com port 22: Connection timed out
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.`

Why do you speak English to me？这个报错内容是22端口无法访问，检查您的网络环境是否放行了此端口，连接Gitee私库需要使用此端口

**Comment by hacken156026692** [comment]
实际上我是在安卓termux里运行的。这个私钥问题，大神你是怎么解决的啊？你连上去了？

**Comment by SuperManito** [comment]
> 实际上我是在安卓termux里运行的。这个私钥问题，大神你是怎么解决的啊？你连上去了？

我咋跟你说呢，你用的那linux我完全不了解，你先确认`git wget curl perl moreutils openssh-server`这几个软件包又没有装上吧，私钥就下面的几条命令

    wget -P ~/.ssh https://gitee.com/SuperManito/JD-FreeFuck/raw/main/id_rsa    #下载私钥
    chmod 600 ~/.ssh/id_rsa                                                                                       #赋权
    ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub                                               #生成公钥

**Comment by qaqaqaaaa** [comment]
> 实际上我是在安卓termux里运行的。这个私钥问题，大神你是怎么解决的啊？你连上去了？

请问你如何解决的 我也是gitpull 卡住了

**Comment by SuperManito** [comment]
不客气
