### ISSUE TITLE
账号7不能获取助力

### ISSUE THREAD

**Issue by boshi116** [SuperManito/JD-FreeFuck#69]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [x] 是
- [ ] 否

Q：是否仔细阅读了部署前须知？

- [x] 是
- [ ] 否

Q：是否仔细阅读了项目须知？

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86_64
- [ ] ARM

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：账号为7个的时候  其他账号无法给账号7助力 账号7可以给其他号助力

### (2) 详细的系统日志

A：格式是这样的  是否有错误  
MyFruit1="1"
MyFruit2="2"
MyFruit3="3"
MyFruit4="4"
MyFruit5="5"
MyFruit6="6"
MyFruit7="7"
ForOtherFruit1="${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit2="${MyFruit1}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit3="${MyFruit1}@${MyFruit2}@${MyFruit4}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit4="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit5}@${MyFruit6}@${MyFruit7}"
ForOtherFruit5="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit6}@${MyFruit7}"
ForOtherFruit6="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit7}"
ForOtherFruit7="${MyFruit1}@${MyFruit2}@${MyFruit3}@${MyFruit4}@${MyFruit5}@${MyFruit6}"

**Comment by SuperManito** [comment]
您真是个人才，`MyFruit1="1"`这里面不是让你填序号的，是让你填互助码的，人家配置文件下面都有示范

**Comment by boshi116** [comment]
互助麻为了避嫌 已经用 12 34代替了
