### ISSUE TITLE
有bug啊啊啊，运行不了

### ISSUE THREAD

**Issue by yang137312** [SuperManito/JD-FreeFuck#7]
在/home/myid/jd/scripts、/home/myid/jd/scripts/backUp、/home/myid/jd/config三个目录下均未检测到 31.京东快递签到：jd_kd.js 脚本的存在，请确认...

本脚本的用法为：
1. bash jd.sh xxx      # 如果设置了随机延迟并且当时时间不在0-2、30-31、59分内，将随机延迟一定秒数
2. bash jd.sh xxx now  # 无论是否设置了随机延迟，均立即运行
3. bash jd.sh hangup   # 重启挂机程序
4. bash jd.sh resetpwd # 重置控制面板用户名和密码

**Comment by SuperManito** [comment]
看通知，解决办法已经写完了，正在测试，10分钟后回来执行看通知执行更新命令

**Comment by SuperManito** [comment]
> 在/home/myid/jd/scripts、/home/myid/jd/scripts/backUp、/home/myid/jd/config三个目录下均未检测到 31.京东快递签到：jd_kd.js 脚本的存在，请确认...
> 
> 本脚本的用法为：
> 
> 1. bash jd.sh xxx      # 如果设置了随机延迟并且当时时间不在0-2、30-31、59分内，将随机延迟一定秒数
> 2. bash jd.sh xxx now  # 无论是否设置了随机延迟，均立即运行
> 3. bash jd.sh hangup   # 重启挂机程序
> 4. bash jd.sh resetpwd # 重置控制面板用户名和密码

执行更新命令
      bash <(curl -L https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/manual-update.sh)

**Comment by SuperManito** [comment]
> 在/home/myid/jd/scripts、/home/myid/jd/scripts/backUp、/home/myid/jd/config三个目录下均未检测到 31.京东快递签到：jd_kd.js 脚本的存在，请确认...
> 
> 本脚本的用法为：
> 
> 1. bash jd.sh xxx      # 如果设置了随机延迟并且当时时间不在0-2、30-31、59分内，将随机延迟一定秒数
> 2. bash jd.sh xxx now  # 无论是否设置了随机延迟，均立即运行
> 3. bash jd.sh hangup   # 重启挂机程序
> 4. bash jd.sh resetpwd # 重置控制面板用户名和密码

另外请把你的星星点回来，谢谢，我不是开发者，原作者突然更新我有什么办法

**Comment by yang137312** [comment]
在我这，你的星星不会再灭了
