### ISSUE TITLE
您真是个人才，`MyFruit1="1"`这里面不是让你填序号的，是让你填互助码的，人家配置文件下面都有示范

### ISSUE THREAD

**Issue by boshi116** [SuperManito/JD-FreeFuck#70]
您真是个人才，`MyFruit1="1"`这里面不是让你填序号的，是让你填互助码的，人家配置文件下面都有示范

_Originally posted by @SuperManito in https://github.com/SuperManito/JD-FreeFuck/issues/69#issuecomment-783835907_

7可以给其他账号助力  但是账号7不能得到助力
互助码为了避嫌 特意用 1 2 3 4 5 6 7 代替了  已经说明了 账号

**Comment by SuperManito** [comment]
一个账号只能助力3次，你自己看吧

**Comment by KyonCN** [comment]
你这么🐂🍺 自己开项目维护啊
