### ISSUE TITLE
获取互助码：docker exec -it jd bash jd.sh format_share_jd_code now 出错

### ISSUE THREAD

**Issue by shenhui0929** [SuperManito/JD-FreeFuck#71]
## 1. 关于您要提交的问题
Q：是否仔细阅读了教程？

- [ ] 是
- [ ] 否

Q：是否仔细阅读了部署前须知？

- [ X] 是
- [ ] 否

Q：是否仔细阅读了项目须知？

- [ X] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ X] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ X] x86_64
- [ ] ARM

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ X] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：
CentOS Linux release 7.7.1908 (Core)
## 6. 问题类型

- [ ] 部署问题
- [ X] 使用问题

## 7. 详细叙述您的问题
大佬，我是从evine的docker2部署转到您这的使用您的docker版本部署成功，但用获取互助码：docker exec -it jd bash jd.sh format_share_jd_code now时遇到在/jd/scripts、/jd/scripts/backUp、/jd/config三个目录下均未检测到 format_share_jd_code 脚本的存在，请确认...

### (1) 具体问题
A：
用获取互助码：docker exec -it jd bash jd.sh format_share_jd_code now时遇到在/jd/scripts、/jd/scripts/backUp、/jd/config三个目录下均未检测到 format_share_jd_code [脚本的存在，请确认...]
### (2) 详细的系统日志

A：

**Comment by shenhui0929** [comment]
![微信截图_20210223131701](https://user-images.githubusercontent.com/32407042/108805013-e4af9f80-75d9-11eb-880c-e4531f21d888.png)
![微信截图_20210223131629](https://user-images.githubusercontent.com/32407042/108805019-e5e0cc80-75d9-11eb-9645-6b29124d002d.png)

报错如图，opt/scripts/里有大佬的js脚本

**Comment by shenhui0929** [comment]
![微信截图_20210223132447](https://user-images.githubusercontent.com/32407042/108805218-8931e180-75da-11eb-8e84-71fac1c7e7ac.png)
更新一张报错图，上面那张命令有问题

**Comment by SuperManito** [comment]
你给我整蒙了，你现在到底用的是什么版本？

**Comment by shenhui0929** [comment]
用的Docker Install

**Comment by SuperManito** [comment]
> 用的Docker Install

我粘教程命令的时候目录没改，重新下载一下，没下载到位
