### ISSUE TITLE
docker中的定时任务不执行

### ISSUE THREAD

**Issue by ronghuaxueleng** [SuperManito/JD-FreeFuck#72]
## 1. 关于您要提交的问题
Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了完整教程

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ ] x86-64 / AMD64
- [ ] arm64 / aarch64
- [x] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：docker中的定时任务不执行

### (2) 详细的系统日志

A：docker中的定时任务不执行

**Comment by SuperManito** [comment]
更新一下就OK了，看通知
