### ISSUE TITLE
VPS非docker, 今晚执行manual update之后，crontab.list里所有bash /opt/jd/jd.sh xxx全部被自动替换成了bash /opt/jd/jd xxx, 导致脚本无法被执行

### ISSUE THREAD

**Issue by wrxx2019** [SuperManito/JD-FreeFuck#73]
## 1. 关于您要提交的问题
Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了完整教程

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [x] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：Debian 10.6

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：VPS LINUX系统Debian10 非docker, 今晚执行manual update之后，crontab.list里所有bash /opt/jd/jd.sh xxx全部被自动替换成了bash /opt/jd/jd xxx, 导致脚本无法被执行。

### (2) 详细的系统日志

A：非部署问题

**Comment by SuperManito** [comment]
给我看一下你那个manual-update.sh那个文件

**Comment by SuperManito** [comment]
对照一下内容[SuperManito/JD-FreeFuck/blob/main/manual-update.sh](https://github.com/SuperManito/JD-FreeFuck/blob/main/manual-update.sh)，初步怀疑你执行了更新命令

**Comment by wrxx2019** [comment]
#!/bin/bash
## Author:SuperManito
## Modified:2021-2-22

## 执行更新命令
bash git_pull.sh
## 重新生成一键执行所有活动脚本
rm -rf run-all.sh
touch run-all.sh
bash jd.sh | grep -o 'jd_[a-z].*' >run-all.sh
bash jd.sh | grep -o 'jx_[a-z].*' >>run-all.sh
sed -i 's/^/bash jd.sh &/g' run-all.sh
sed -i 's/.js/ now/g' run-all.sh
sed -i '1i\#!/bin/bash' run-all.sh
sed -i "s/bash jd.sh jd_delCoupon now//g" run-all.sh  #不执行京东家庭号任务
sed -i "s/bash jd.sh jd_family now//g" run-all.sh     #不执行删除优惠券任务
cat run-all.sh | grep jd_crazy_joy_coin -wq
if [ $? -eq 0 ];then
  sed -i "s/bash jd.sh jd_crazy_joy_coin now//g" run-all.sh
  echo "bash jd.sh jd_crazy_joy_coin now" >>run-all.sh
fi
sed -i '/^\s*$/d' run-all.sh
## 配置定时任务
sed -i "s#/home/myid/jd/##g" config/crontab.list
sed -i "s#jd.sh#jd#g" config/crontab.list
sed -i "s/git_pull/manual-update/g" config/crontab.list


我对照了确实不一样，但我尝试过bash <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/update.sh)，运行后也没有自动更新manual-update.sh到最新版，需要什么命令可以更新？

**Comment by wrxx2019** [comment]
> 对照一下内容[SuperManito/JD-FreeFuck/blob/main/manual-update.sh](https://github.com/SuperManito/JD-FreeFuck/blob/main/manual-update.sh)，初步怀疑你执行了更新命令

下载了这个文件, 手动上传覆盖后再运行，就没问题了

**Comment by SuperManito** [comment]
你这就是执行了我想推送给Docker用户使用的更新脚本，以后通知看仔细，执行下面的命令修复你的问题：
    rm -rf /opt/jd/config/crontab.list
    cp /opt/jd/sample/computer.list.sample /opt/jd/config/crontab.list
    wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/manual-update.sh -O /opt/jd/manual-update.sh
