### ISSUE TITLE
大佬好，我是用WIN10安装的Ubuntu 教程，现在能够正常使用跑脚本,怎样打开控制面板？

### ISSUE THREAD

**Issue by xinguang520** [SuperManito/JD-FreeFuck#74]
## 1. 关于您要提交的问题
Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了完整教程

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志

A：

**Comment by xinguang520** [comment]
大佬好，我是用WIN10安装的Ubuntu 教程，现在能够正常使用跑脚本,怎样打开控制面板？

**Comment by nxcjs** [comment]
教程不是写了么仔细看

**Comment by sd4623559911** [comment]
重启控制面板，教程没看清楚

**Comment by slj844909754** [comment]
已经启用控制面板，但是打不开127.0.0.1:5678,我使用win10部署的，游览器输入地址不能访问。

**Comment by xinguang520** [comment]
已经处理好了，梯子全局重新安装控制面板 在打开。已经解决了

**Comment by SuperManito** [comment]
> 已经启用控制面板，但是打不开127.0.0.1:5678,我使用win10部署的，游览器输入地址不能访问。

win10 默认屏蔽本地127这个IP，wsl是基于win10的子系统，所以用不了，用局域网IP

**Comment by ZHANGLIANGzhangliang** [comment]
请问你win10的Ubuntu能自动跑脚本吗，我的手动可以运行，自动不会跑

**Comment by SuperManito** [comment]
> 请问你win10的Ubuntu能自动跑脚本吗，我的手动可以运行，自动不会跑

自动跑`run_all`？

**Comment by ZHANGLIANGzhangliang** [comment]
> > 请问你win10的Ubuntu能自动跑脚本吗，我的手动可以运行，自动不会跑
> 
> 定时没有问题

是要挂着jd.sh才会定时吗

**Comment by SuperManito** [comment]
> > > 请问你win10的Ubuntu能自动跑脚本吗，我的手动可以运行，自动不会跑
> > 
> > 
> > 定时没有问题
> 
> 是要挂着jd.sh才会定时吗

什么意思？
