### ISSUE TITLE
安装脚本不会检测是否已经安装了npm，会导致输出npm安装报错

### ISSUE THREAD

**Issue by nxcjs** [SuperManito/JD-FreeFuck#75]
## 1. 关于您要提交的问题
Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了完整教程

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：
卸载重装，我是自己安装的npm和node，脚本进行的时候报npm install 失败。实际已经存在。node不知道有没有这个问题，清屏了。

### (2) 详细的系统日志

A：
检测到package.json有变化，运行 npm install...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz - [not_found] document not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-24T00_18_13_658Z-debug.log
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz - [not_found] document not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-24T00_18_21_691Z-debug.log

npm install 运行不成功，自动删除 /opt/jd/scripts/node_modules 后再次尝试一遍...

运行 npm install...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz - [not_found] document not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-24T00_18_30_002Z-debug.log
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz - [not_found] document not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@https://registry.npm.taobao.org/@sindresorhus/is/-/is-4.0.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-24T00_18_37_926Z-debug.log

npm install 运行不成功，自动删除 /opt/jd/scripts/node_modules...

请进入 /opt/jd/scripts 目录后按照wiki教程手动运行 npm install...

当 npm install 失败时，如果检测到有新任务或失效任务，只会输出日志，不会自动增加或删除定时任务...

**Comment by nxcjs** [comment]
互助码两个模块也没安装，手动装上好正常了，不知道其他模块装好没有

**Comment by SuperManito** [comment]
为什么会这样。。。你node装上了么，给我看你完整的日志

**Comment by nxcjs** [comment]
> 为什么会这样。。。你node装上了么，给我看你完整的日志

装了已经，我提前装好了最新版的npm和node，好像之前没有这个问题，也可能没有注意。
npm的完整日志嘛，还是其他的

**Comment by nxcjs** [comment]
> 为什么会这样。。。你node装上了么，给我看你完整的日志

我已经正常运行了，但是手动运行all run 的时候，还是会有这个报错，不行就不管了，又不是不能用
就不知道需要什么模块，手动运行一下npm install 就行

**Comment by SuperManito** [comment]
你把你的node和npm全部卸载干净再部署我的项目

**Comment by nxcjs** [comment]
我估计也是环境问题，大佬你的是node和npm是 默认路径嘛

**Comment by SuperManito** [comment]
> 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛

node官方脚本装的，我不清楚

**Comment by SuperManito** [comment]
> 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛

node官方脚本装的，我不清楚

**Comment by sw1999** [comment]
> 互助码两个模块也没安装，手动装上好正常了，不知道其他模块装好没有

互助码兄弟发一下正确的命令吧，方便大家，谢谢你

**Comment by nxcjs** [comment]
> > 互助码两个模块也没安装，手动装上好正常了，不知道其他模块装好没有
> 
> 互助码兄弟发一下正确的命令吧，方便大家，谢谢你

一个是got，还有一个名字 太长了没记住，是cookie什么的，你看一下报错报什么不就好了，少什么装什么，就在第一行

**Comment by nxcjs** [comment]
> > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> 
> node官方脚本装的，我不清楚

那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新

**Comment by SuperManito** [comment]
@sw1999 @nxcjs 什么互助码模块？lxk新加的吗？

**Comment by SuperManito** [comment]
> > > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> > 
> > 
> > node官方脚本装的，我不清楚
> 
> 那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新

yum remove -y nodejs npm

**Comment by nxcjs** [comment]
> > > > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> > > 
> > > 
> > > node官方脚本装的，我不清楚
> > 
> > 
> > 那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新
> 
> yum remove -y nodejs npm

大佬你用的是什么系统。centos还是Ubuntu？

**Comment by nxcjs** [comment]
> @sw1999 @nxcjs 什么互助码模块？lxk新加的吗？
互助码的脚本需要另外两个模块，报错了自己装一下就行。一个got一个cookie什么，美丽研究院少ws，还有一个crypto-js很多都需要，我不知道是我环境导致的问题，还是大佬的脚本忘记安装了

**Comment by SuperManito** [comment]
> > > > > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> > > > 
> > > > 
> > > > node官方脚本装的，我不清楚
> > > 
> > > 
> > > 那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新
> > 
> > 
> > yum remove -y nodejs npm
> 
> 大佬你用的是什么系统。centos还是Ubuntu？

Ubuntu

**Comment by nxcjs** [comment]
> > > > > > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> > > > > 
> > > > > 
> > > > > node官方脚本装的，我不清楚
> > > > 
> > > > 
> > > > 那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新
> > > 
> > > 
> > > yum remove -y nodejs npm
> > 
> > 
> > 大佬你用的是什么系统。centos还是Ubuntu？
> 
> Ubuntu

我用的是ubuntuservice，应该也是一样的啊，怎么玄学问题这么多

**Comment by SuperManito** [comment]
> > > > > > > 我估计也是环境问题，大佬你的是node和npm是 默认路径嘛
> > > > > > 
> > > > > > 
> > > > > > node官方脚本装的，我不清楚
> > > > > 
> > > > > 
> > > > > 那就头痛了，重装node有点麻烦，我是用yum装的，估计就是这个原因，我yum安装然后用n更新
> > > > 
> > > > 
> > > > yum remove -y nodejs npm
> > > 
> > > 
> > > 大佬你用的是什么系统。centos还是Ubuntu？
> > 
> > 
> > Ubuntu
> 
> 我用的是ubuntuservice，应该也是一样的啊，怎么玄学问题这么多

Ubuntu服务器版我还真没测试过，换桌面版吧
