### ISSUE TITLE
根据相关法律政策,该内容无法显示: command not found

### ISSUE THREAD

**Issue by singee77** [SuperManito/JD-FreeFuck#76]
## 2. 安装平台

- [x ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## 6. 问题类型

- [ x] 部署问题

### (1) 具体问题
`bash <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/install.sh)`
/dev/fd/63: line 1: 根据相关法律政策,该内容无法显示: command not found

**Comment by SuperManito** [comment]
什么玩意？没安装curl软件包吧，仔细阅读《一、命令部署》的教程

**Comment by SuperManito** [comment]
刚看了以下，gitee那边库出问题了，被官方封了。。。https://gitee.com/SuperManito/JD-FreeFuck/blob/main/install.sh#only_comment_project

**Comment by SuperManito** [comment]
换github命令部署
