### ISSUE TITLE
大佬可不可以开启定时自动运行呀

### ISSUE THREAD

**Issue by qingsudanya** [SuperManito/JD-FreeFuck#8]

**Comment by SuperManito** [comment]
我研究下

**Comment by qingsudanya** [comment]
> 我研究下

谢谢大佬~~~

**Comment by SuperManito** [comment]
> > 我研究下
> 
> 谢谢大佬~~~

这个定时自动运行涉及linux定时任务，我看它已经自动加入到系统里了，但我不知道有没有执行，我平时用一直都是手动执行，还有bash git_pull.sh更新命令会自动覆盖定时任务配置文件，也就是说如果想自定义的话就得一直改，你是想要什么效果？

**Comment by qingsudanya** [comment]
好，谢谢大佬

**Comment by qingsudanya** [comment]
不用手动run-all.sh ，每天到时间自动运行

**Comment by SuperManito** [comment]
> 不用手动run-all.sh ，每天到时间自动运行

那你直接给run-all设置个定时不就完了

**Comment by qingsudanya** [comment]
> > 不用手动run-all.sh ，每天到时间自动运行
> 
> 那你直接给run-all设置个定时不就完了

哈哈，也是，谢谢大佬

**Comment by SuperManito** [comment]
> > > 不用手动run-all.sh ，每天到时间自动运行
> > 
> > 
> > 那你直接给run-all设置个定时不就完了
> 
> 哈哈，也是，谢谢大佬

你要是设置定时 把run-all中那个挂机活动的命令删了
