### ISSUE TITLE
VPS 一键部署代码须执行两次

### ISSUE THREAD

**Issue by ansonlinh** [SuperManito/JD-FreeFuck#80]
## 1. 关于您要提交的问题
Q：是否仔细阅读了《部署前须知》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了完整教程

- [x ] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x ] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [x ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：
一键部署代码第一次执行无法从远程复制Scripts，但是执行第二次又可以。
今天开始出现的问题。
### (2) 详细的系统日志

A：
Cloning into '/opt/jd/scripts'...
git@gitee.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by SuperManito** [comment]
发完整的日志

**Comment by ansonlinh** [comment]
我是小白，可以告知所需日志的路径么？

**Comment by SuperManito** [comment]
> 我是小白，可以告知所需日志的路径么？

你终端上的输出日志，从开始部署到结束的所有内容
