### ISSUE TITLE
diy脚本

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#81]
1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

 5. 安装环境具体版本号
A：centos7.6

 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

 7. 详细叙述您的问题
 (1) 具体问题
5. 使用diy脚本：
#启用该功能
sed -i 's/EnableExtraShell=""/EnableExtraShell="true"/g' config/config.sh
#导入脚本/更新脚本
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/diy.sh -O config/diy.sh

13. 更新一键更新脚本：
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/manual-update.sh -O manual-update.sh
bash manual-update.sh

这2个有什么关系吗？ 
要想都更新，5执行一遍，然后13执行一遍，会冲突吗？这样更新完，运行一键bash run-all.sh，是会2个脚本都执行？

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

**Comment by sd462355991111** [comment]
问题在这
5. 使用diy脚本：
#启用该功能
sed -i 's/EnableExtraShell=""/EnableExtraShell="true"/g' config/config.sh
#导入脚本/更新脚本
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/diy.sh -O config/diy.sh

13. 更新一键更新脚本：
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/manual-update.sh -O manual-update.sh
bash manual-update.sh

这2个有什么关系吗？ 
要想都更新，5执行一遍，然后13执行一遍，会冲突吗？这样更新完，运行一键bash run-all.sh，是会2个脚本都执行？

**Comment by SuperManito** [comment]
我不明白你为什么想要都更新，需要更新或者有新内容我会发布通知，两个脚本没有任何的关系，`run-all`是一键执行所有活动脚本，用来手动执行所有活动脚本；`manual-update.sh`是一键更新活动脚本，用来更新活动脚本和`run-all.sh`以及定时任务；diy脚本用来添加第三方活动脚本
