### ISSUE TITLE
文档疑似有问题

### ISSUE THREAD

**Issue by PwnerZhang** [SuperManito/JD-FreeFuck#82]
README里面
**2021/2/24 17:50 通知**
`rm -rf /opt/jd/scripts *love.js`
是不是漏了个`/`

**Comment by SuperManito** [comment]
> README里面
> **2021/2/24 17:50 通知**
> `rm -rf /opt/jd/scripts *love.js`
> 是不是漏了个`/`

奥，对
`rm -rf /opt/jd/scripts/*love.js`

**Comment by SuperManito** [comment]
已更正
