### ISSUE TITLE
格式化助力码符号问题

### ISSUE THREAD

**Issue by zhaojie199512** [SuperManito/JD-FreeFuck#83]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [x] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：
使用脚本format_share_jd_code.js后，显示出来了各个账号的助力码和组合好的助力码，确实很方便，就是有一点问题，助力码是用单引号' '括起来，而不是双引号“ ”,这样在config,sh里导入后不识别，必须换成双引号后执行其他活动脚本才能识别助力码。
例如：MyFruit1='e6e04602d5e343258873af1651b603ec'
需要改成MyFruit1="e6e04602d5e343258873af1651b603ec"
### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：无

**Comment by SuperManito** [comment]
好的，我去反馈给作者

**Comment by zhaojie199512** [comment]
> 好的，我去反馈给作者

好滴地，谢谢大佬，大佬继续加油！！！我再去给大佬赞助一瓶快乐水ヽ(￣▽￣)ﾉ

**Comment by SuperManito** [comment]
> > 好的，我去反馈给作者
> 
> 好滴地，谢谢大佬，大佬继续加油！！！我再去给大佬赞助一瓶快乐水ヽ(￣▽￣)ﾉ

谢谢老板
