### ISSUE TITLE
个人建议把format_share_jd_code.js这个获取助力码的js脚本改一下

### ISSUE THREAD

**Issue by qingdeng8866** [SuperManito/JD-FreeFuck#84]
出来的格式化助力码是这样子的
ForOtherJoy1='${MyJoy1}@${MyJoy2}@${MyJoy3}@${MyJoy4}@${MyJoy5}@${MyJoy6}'
建议修复把 ' 改回 ''   要不直接复制去config.sh 不能识别助力码变量

**Comment by SuperManito** [comment]
> 出来的格式化助力码是这样子的
> ForOtherJoy1='${MyJoy1}@${MyJoy2}@${MyJoy3}@${MyJoy4}@${MyJoy5}@${MyJoy6}'
> 建议修复把 ' 改回 '' 要不直接复制去config.sh 不能识别助力码变量

刚更新了，原作者已经修复了这个问题，不能识别的原因是单引号导致的，现在已经改成了双引号，重新导入脚本即可

**Comment by qingdeng8866** [comment]
好的 感谢
