### ISSUE TITLE
VM10 里面centos7部署问题

### ISSUE THREAD

**Issue by liuckv** [SuperManito/JD-FreeFuck#85]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：7 kde 桌面版

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：我是在win7里面安装vm10虚拟机装的centos7的kde桌面版，用bash <(curl -sL https://gitee.com/SuperManito/JD-FreeFuck/raw/main/install.sh)gitee命令部署，可以部署到一半，之后centos7就崩溃了。如果用github命令 部署的话，就没有反应，但是我的vm10已经用SSR翻了，centos 7里面的浏览器都已经可以上gg的了，请问什么问题？

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：[root@localhost ~]# bash <(curl -sL https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
[root@localhost ~]#

**Comment by SuperManito** [comment]
你为什么要看你自己没有同步的fork项目呢？我已经更新很多内容了，你在用旧版本，不发日志你想给我看什么？去看常见问题与帮助2、3
