### ISSUE TITLE
jd.sh 中的 Detect_Cron 运行卡住

### ISSUE THREAD

**Issue by bytepoem** [SuperManito/JD-FreeFuck#86]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：centos 7

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：![image](https://user-images.githubusercontent.com/48577796/109111367-bebe0280-7773-11eb-8c20-9f0b0d2cf517.png)
貌似更新定时任务列表失败 要这样才能运行脚本

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：暂无日志，目前我在 `jd.sh` 脚本中定位到的是 `Import_Conf $1 && Detect_Cron && Set_Env` 中的 `Detect_Cron` 无法运行

**Comment by SuperManito** [comment]
你没用我的一键更新脚本吗?

**Comment by bytepoem** [comment]
> 你没用我的一键更新脚本吗?

```
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/manual-update.sh -O manual-update.sh
bash manual-update.sh
```

执行之后可以了

**Comment by SuperManito** [comment]
> > 你没用我的一键更新脚本吗?
> 
> ```
> wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/manual-update.sh -O manual-update.sh
> bash manual-update.sh
> ```
> 
> 执行之后可以了

嗯
