### ISSUE TITLE
windows ubuntu 粘贴代码 没有反应

### ISSUE THREAD

**Issue by hello1983** [SuperManito/JD-FreeFuck#87]
Windows ubuntu  粘贴代码 没有反应 

```

root@DESKTOP-6N38M89:~# bash <(curl -sL https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)


root@DESKTOP-6N38M89:~#

```

**Comment by SuperManito** [comment]
> Windows ubuntu 粘贴代码 没有反应
> 
> ```
> 
> root@DESKTOP-6N38M89:~# bash <(curl -sL https://raw.githubusercontent.com/SuperManito/JD-FreeFuck/main/install.sh)
> 
> 
> root@DESKTOP-6N38M89:~#
> ```


常见问题与帮助：
2. 如果执行部署脚本命令后没有反应直接结束并跳回终端交互说明您的网络环境存在问题，请检查您的网络连通性以及相关设置。
3. 如果使用Github命令部署项目时提示无法解决Hosts，可通过添加解析记录以解决连通性问题，添加命令如下：

    echo "151.101.88.133 raw.githubusercontent.com" >> /etc/hosts
    echo "151.101.228.133 raw.githubusercontent.com" >> /etc/hosts
