### ISSUE TITLE
大佬，执行source run-all.sh提示No such file or directory，我用winscp进入/opt/jd下没发现run-all.sh脚本，是我闹笑话了还是脚本没生成。

### ISSUE THREAD

**Issue by Bigpangjin** [SuperManito/JD-FreeFuck#90]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [x] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

**Comment by Bigpangjin** [comment]
大佬，执行source run-all.sh提示No such file or directory，我用winscp进入cd /opt/jd下没发现run-all.sh脚本，是我闹笑话了还是脚本没生成

**Comment by SuperManito** [comment]
不可能啊 你装的什么版本

**Comment by Bigpangjin** [comment]
软路由koolshare版LEDE，docker使用的酷软中心带的
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6

**Comment by SuperManito** [comment]
> 软路由koolshare版LEDE，docker使用的酷软中心带的
> Version: 18.09.1
> API version: 1.39
> Go version: go1.10.6

你看错教程了吧

**Comment by Bigpangjin** [comment]
按照docker的命令还是会报错：
root@Openwrt:/# docker exec -it jd source run-all.sh
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"source\": executable file not found in $PATH": unknown
root@Openwrt:/#

**Comment by SuperManito** [comment]
> 按照docker的命令还是会报错：
> root@Openwrt:/# docker exec -it jd source run-all.sh
> OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: "source": executable file not found in $PATH": unknown
> root@Openwrt:/#

刷新一下 我上午改了

**Comment by Bigpangjin** [comment]
刚才重新更新了脚本，但是问题依旧。


+------------------------ 更 新 成 功 ------------------------+ 
 |                                                             | 
 | 特别提示：后续使用遇到问题请访问本人项目页寻求帮助          | 
 |                                                             | 
 |           我不是活动脚本的开发者，所有活动问题与我无关      | 
 |                                                             | 
 | 项目地址：https://github.com/SuperManito/JD-FreeFuck        | 
 |           https://gitee.com/SuperManito/JD-FreeFuck         | 
 |                                                             | 
 +-------------------------------------------------------------+ 
root@jd:/jd $ exit
exit
root@Openwrt:/# docker exec -it jd source run-all.sh
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"source\": executable file not found in $PATH": unknown
root@Openwrt:/#

**Comment by SuperManito** [comment]
> 刚才重新更新了脚本，但是问题依旧。
> 
> +------------------------ 更 新 成 功 ------------------------+
> | |
> | 特别提示：后续使用遇到问题请访问本人项目页寻求帮助 |
> | |
> | 我不是活动脚本的开发者，所有活动问题与我无关 |
> | |
> | 项目地址：https://github.com/SuperManito/JD-FreeFuck |
> | https://gitee.com/SuperManito/JD-FreeFuck |
> | |
> +-------------------------------------------------------------+
> root@jd:/jd $ exit
> exit
> root@Openwrt:/# docker exec -it jd source run-all.sh
> OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: "source": executable file not found in $PATH": unknown
> root@Openwrt:/#

我放错教程了，现在再看 https://github.com/SuperManito/JD-FreeFuck/wiki/Docker-Use-And-Update-Tutorial
