### ISSUE TITLE
填了Cookie  再运行一键命令，就卡住了，一直卡着

### ISSUE THREAD

**Issue by sd462355991111** [SuperManito/JD-FreeFuck#91]
1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

 5. 安装环境具体版本号
A：ubuntu18.04

 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

 7. 详细叙述您的问题
 (1) 具体问题
A：前提Cookie没问题，就版本都正常跑
刚部署后，运行一键命令，就卡住了，一直卡着   我以为是我配置信息哪里复制错了。
又重新部署一遍看下问题出在哪
部署好，不填配置信息，运行一键命令，显示：请先在config.sh中配置好Cookie...
说明可以跑
问题是填了Cookie  再运行一键命令，就卡住了，一直卡着

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

**Comment by mohanfeng3** [comment]
和你一样，cpu100%

**Comment by sd462355991111** [comment]
部署信息太多，ssh显示不全，没办法全部复制，但部署的时候，我大概看了下，没错误信息，或者文件找不到信息，部署应该没问题

**Comment by PwnerZhang** [comment]
> 1. 关于您要提交的问题
>    Q：是否阅读了《特别声明》并已接受此声明
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《部署前须知》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《常见问题与帮助》
> 
> * [x]  是
> * [ ]  否
> 
> Q：是否仔细阅读了《项目须知》
> 
> * [x]  是
> * [ ]  否
> 
> 1. 安装平台
> 
> * [x]  PC
> * [ ]  VPS
> * [ ]  软路由
> * [ ]  NAS
> * [ ]  Other
> 
> 1. 安装平台架构
> 
> * [x]  x86-64 / AMD64
> * [ ]  arm64 / aarch64
> * [ ]  Other
> 
> 1. 安装环境
> 
> * [x]  Ubuntu
> * [ ]  Debian
> * [ ]  CentOS
> * [ ]  Fedora
> * [ ]  Docker
> * [ ]  Other
> 
> 1. 安装环境具体版本号
>    A：ubuntu18.04
> 2. 问题类型
> 
> * [ ]  部署问题
> * [x]  使用问题
> 
> 1. 详细叙述您的问题
>    (1) 具体问题
>    A：前提Cookie没问题，就版本都正常跑
>    刚部署后，运行一键命令，就卡住了，一直卡着   我以为是我配置信息哪里复制错了。
>    又重新部署一遍看下问题出在哪
>    部署好，不填配置信息，运行一键命令，显示：请先在config.sh中配置好Cookie...
>    说明可以跑
>    问题是填了Cookie  再运行一键命令，就卡住了，一直卡着
> 
> ### (2) 详细的系统日志
> _注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_
> 
> A：

和你一样，cpu100%

**Comment by PwnerZhang** [comment]
系统版本：CentOS Linux release 7.9.2009 (Core)

**Comment by sd462355991111** [comment]
大家都这样， 那就是个人问题，等作者修复

**Comment by sd462355991111** [comment]
大家都这样， 那就不是个人问题，等作者修复吧，多等等

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/109251703-e4581400-7826-11eb-9e1f-922ffae02431.png)
刚测试了一下 没有任何问题啊

**Comment by SuperManito** [comment]
@mohanfeng3 @sd462355991111

**Comment by sd462355991111** [comment]
不行，还是卡着

**Comment by SuperManito** [comment]
> > 1. 关于您要提交的问题
> >    Q：是否阅读了《特别声明》并已接受此声明
> > 
> > 
> > * [x]   是
> > * [ ]   否
> > 
> > Q：是否仔细阅读了《部署前须知》
> > 
> > * [x]   是
> > * [ ]   否
> > 
> > Q：是否仔细阅读了《常见问题与帮助》
> > 
> > * [ ]   是
> > * [ ]   否
> > 
> > Q：是否仔细阅读了《项目须知》
> > 
> > * [x]   是
> > * [ ]   否
> > 
> > 
> > 1. 安装平台
> > 
> > 
> > * [x]   PC
> > * [ ]   VPS
> > * [ ]   软路由
> > * [ ]   NAS
> > * [ ]   Other
> > 
> > 
> > 1. 安装平台架构
> > 
> > 
> > * [x]   x86-64 / AMD64
> > * [ ]   arm64 / aarch64
> > * [ ]   Other
> > 
> > 
> > 1. 安装环境
> > 
> > 
> > * [x]   Ubuntu
> > * [ ]   Debian
> > * [ ]   CentOS
> > * [ ]   Fedora
> > * [ ]   Docker
> > * [ ]   Other
> > 
> > 
> > 1. 安装环境具体版本号
> >    A：ubuntu18.04
> > 2. 问题类型
> > 
> > 
> > * [ ]   部署问题
> > * [x]   使用问题
> > 
> > 
> > 1. 详细叙述您的问题
> >    (1) 具体问题
> >    A：前提Cookie没问题，就版本都正常跑
> >    刚部署后，运行一键命令，就卡住了，一直卡着   我以为是我配置信息哪里复制错了。
> >    又重新部署一遍看下问题出在哪
> >    部署好，不填配置信息，运行一键命令，显示：请先在config.sh中配置好Cookie...
> >    说明可以跑
> >    问题是填了Cookie  再运行一键命令，就卡住了，一直卡着
> > 
> > ### (2) 详细的系统日志
> > _注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_
> > A：
> 
> 和你一样，cpu100%

你装的时候肯定占用很大性能，要装很多软件包处理很多东西，你机器性能不够可能会卡住，但只是终端不输出信息并不是真的卡住，如果你用的是国外VPS可能会存在这种问题

**Comment by SuperManito** [comment]
> 不行，还是卡着

截图或发日志 给我看看

**Comment by sd462355991111** [comment]
进程 USER      PR  NI    VIRT    RES    SHR �  %CPU %MEM     TIME+ COMMAND             
 45417 root      20   0   20252   3344   2852 R 100.0  0.1   0:23.09 bash                
 40722 root      20   0   20252   3428   2920 R  99.7  0.1   4:01.85 bash                
 38594 root      20   0   51868   4672   3392 S   1.0  0.1   0:02.59 top                 
 45480 root      20   0   51864   4804   3504 R   1.0  0.1   0:00.22 top

**Comment by sd462355991111** [comment]
是什么日志

**Comment by SuperManito** [comment]
> 是什么日志

终端输出信息

**Comment by sd462355991111** [comment]
![image](https://user-images.githubusercontent.com/78030698/109252043-8bd54680-7827-11eb-9c01-0762a8e99209.png)

**Comment by SuperManito** [comment]
@sd462355991111 你手动执行单个活动脚本看看有输出信息么

**Comment by sd462355991111** [comment]
![image](https://user-images.githubusercontent.com/78030698/109252244-03a37100-7828-11eb-956e-aa5545c5c266.png)

**Comment by sd462355991111** [comment]
单独执行时这样命令吗

**Comment by SuperManito** [comment]
> 单独执行时这样命令吗

对啊 随便执行一个 bash jd.sh bean_change now

**Comment by sd462355991111** [comment]
机器是虚拟机，4核4g  性能够的，我要先在虚拟机运行成功，才部署到vps

**Comment by SuperManito** [comment]
CentOS 部署目前有问题，没拉到库，其它没问题

**Comment by sd462355991111** [comment]
截图你看的到吗，就是这样没输出显示

**Comment by sd462355991111** [comment]
是用Ubuntu18.04

**Comment by sd462355991111** [comment]
单独执行了一下，要等很久，可以执行，就是很占cpu，
现在一键执行看看，估计要等很久，等待中。。。。。。。。

**Comment by sd462355991111** [comment]
现在虚拟机分配8核4g，
运行时候cpu占用63%，大概就是4核多点，1g内存，

**Comment by SuperManito** [comment]
@PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本

**Comment by sd462355991111** [comment]
刚才单独执行美丽颜究院等了很久，ssh有输出显示
现在一键执行，ssh里面只是没显示输出，实际上方糖已经推送了，

**Comment by sd462355991111** [comment]
@SuperManito 喔，辛苦了，理解

**Comment by nxcjs** [comment]
> @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本

大佬，顺手把nodejs的下载地址换成cn吧，org的浙江电信要下一整天，之前就是因为node 下载太慢，所以才手动装的node

**Comment by sd462355991111** [comment]
@nxcjs 一整天，太夸张了吧，我之前慢也是下了1小时，今天部署，很快，1分钟好了

**Comment by sd462355991111** [comment]
@nxcjs 解决Hosts那个命令加了吗

**Comment by SuperManito** [comment]
> > @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本
> 
> 大佬，顺手把nodejs的下载地址换成cn吧，org的浙江电信要下一整天，之前就是因为node 下载太慢，所以才手动装的node

不可能啊，下载node链接用的是中科大的nodesorce源，只要它的源没问题下载就没问题

**Comment by nxcjs** [comment]
> > > @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本
> > 
> > 
> > 大佬，顺手把nodejs的下载地址换成cn吧，org的浙江电信要下一整天，之前就是因为node 下载太慢，所以才手动装的node
> 
> 不可能啊，下载node链接用的是中科大的nodesorce源，只要它的源没问题下载就没问题

================================================================================
 Package      架构         版本                          源                大小
================================================================================
正在安装:
 nodejs       x86_64       2:14.16.0-1nodesource         nodesource        32 M

事务概要
================================================================================
安装  1 软件包

总下载量：32 M
安装大小：91 M
Downloading packages:
nodejs-14.16.0-1nodesource.x86 FAILED
https://mirrors.ustc.edu.cn/nodesource/rpm/pub_14.x/el/7/x86_64/nodejs-14.16.0-1                                                                                                                                                             nodesource.x86_64.rpm: [Errno 12] Timeout on https://rpm.nodesource.com/pub_14.x                                                                                                                                                             /el/7/x86_64/nodejs-14.16.0-1nodesource.x86_64.rpm: (28, 'Operation too slow. Le                                                                                                                                                             ss than 1000 bytes/sec transferred the last 30 seconds')
正在尝试其它镜像。
nodejs-14.16.0-1nodesource.x86 FAILED
https://mirrors.ustc.edu.cn/nodesource/rpm/pub_14.x/el/7/x86_64/nodejs-14.16.0-1                                                                                                                                                             nodesource.x86_64.rpm: [Errno 12] Timeout on https://rpm.nodesource.com/pub_14.x                                                                                                                                                             /el/7/x86_64/nodejs-14.16.0-1nodesource.x86_64.rpm: (28, 'Operation too slow. Le                                                                                                                                                             ss than 1000 bytes/sec transferred the last 30 seconds')
正在尝试其它镜像。
nodejs-14.16.0-1nodesource.x86 FAILED
https://mirrors.ustc.edu.cn/nodesource/rpm/pub_14.x/el/7/x86_64/nodejs-14.16.0-1                                                                                                                                                             nodesource.x86_64.rpm: [Errno 12] Timeout on https://rpm.nodesource.com/pub_14.x                                                                                                                                                             /el/7/x86_64/nodejs-14.16.0-1nodesource.x86_64.rpm: (28, 'Operation too slow. Le                                                                                                                                                             ss than 1000 bytes/sec transferred the last 30 seconds')
正在尝试其它镜像。
nodejs-14.16.0-1nodesource 88% [==============  ]  13 kB/s |  28 MB   04:28 ETA

拉了两次都没啦下来啊

**Comment by SuperManito** [comment]
@nxcjs 你的网络连中科大怎么这么慢。。。你看发的日志上面的链接全是中科大的，nodesource官方源在国外，没科学上网更慢

**Comment by nxcjs** [comment]
> @nxcjs 你的网络连中科大怎么这么慢。。。你看发的日志上面的链接全是中科大的，nodesource官方源在国外，没科学上网更慢

很奇怪，就是这么慢，浙江电信。会不会是ipv6的问题，我直接去hosts改一下看看

**Comment by SuperManito** [comment]
> > @nxcjs 你的网络连中科大怎么这么慢。。。你看发的日志上面的链接全是中科大的，nodesource官方源在国外，没科学上网更慢
> 
> 很奇怪，就是这么慢，浙江电信。会不会是ipv6的问题，我直接去hosts改一下看看

这个项目不支持IPv6，大部分活动的接口都不支持IPv6

**Comment by nxcjs** [comment]
> > > @nxcjs 你的网络连中科大怎么这么慢。。。你看发的日志上面的链接全是中科大的，nodesource官方源在国外，没科学上网更慢
> > 
> > 
> > 很奇怪，就是这么慢，浙江电信。会不会是ipv6的问题，我直接去hosts改一下看看
> 
> 这个项目不支持IPv6，大部分活动的接口都不支持IPv6
> 
> ![image](https://user-images.githubusercontent.com/68613938/109261706-3440d600-783b-11eb-83c7-a707a30e74e8.png)

这个地址 我直接访问就跳转到github上了，我还是挂个梯子吧，安装好了再去撤了

**Comment by mohanfeng3** [comment]
> @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本
重装和你一样的系统再试试，辛苦了，谢谢

**Comment by SuperManito** [comment]
> > @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本
> > 重装和你一样的系统再试试，辛苦了，谢谢

好的

**Comment by mohanfeng3** [comment]
> > > @PwnerZhang @mohanfeng3 @sd462355991111 刚测试了一下确实跟你们说的情况一致，我真的不知道什么情况，Ubuntu20没问题，node官方最近刚把node14.15.4更新到了14.16啊，你们先用新系统吧，我这里定时的错误还没解决呢，真不想维护旧版系统了，我测试不过来还要维护docker版本
> > > 重装和你一样的系统再试试，辛苦了，谢谢
> 
> 好的

ubuntu20.10测试没问题，给你反馈下，一切正常，建议有同样问题的小伙伴都用ubuntu20.10这个系统
