### ISSUE TITLE
sh manual-update.sh 错误

### ISSUE THREAD

**Issue by hello1983** [SuperManito/JD-FreeFuck#93]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [ ] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ ] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

manual-update.sh: 47: Syntax error: "(" unexpected

**Comment by SuperManito** [comment]
这跟没用模板有什么区别？？？我看不到日志没法解决问题

**Comment by yang137312** [comment]
--------------------------------------------------------------

系统时间：2021-02-27 10:17:50

JS脚本目录：/opt/jd/scripts

--------------------------------------------------------------

Fetching origin
Username for 'https://gitee.com': 

这里需要填写账号密码，就算账号密码填写正确之后：
--------------------------------------------------------------

Fetching origin
Username for 'https://gitee.com': yang123888
Password for 'https://yang123888@gitee.com': 
remote: You do not have permission to pull the repository
fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': The requested URL returned error: 403
error: Could not fetch origin
HEAD is now at 3ad49ab 修改文件名字

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by yang137312** [comment]
系统：centos 8

**Comment by SuperManito** [comment]
> 系统时间：2021-02-27 10:17:50
> 
> JS脚本目录：/opt/jd/scripts
> 
> Fetching origin
> Username for 'https://gitee.com':
> 
> ## 这里需要填写账号密码，就算账号密码填写正确之后：
> Fetching origin
> Username for 'https://gitee.com': yang123888
> Password for 'https://yang123888@gitee.com':
> remote: You do not have permission to pull the repository
> fatal: unable to access 'https://gitee.com/lxk0301/jd_scripts/': The requested URL returned error: 403
> error: Could not fetch origin
> HEAD is now at 3ad49ab 修改文件名字
> 
> js脚本更新失败，请检查原因或再次运行git_pull.sh...

直接用root用户登录会导致私钥装不上

#95 看这个解决

**Comment by yang137312** [comment]
okok

**Comment by yang137312** [comment]
运行完之后还是得填写账号密码，而且填写了之后也报上边的错误。。。没有效果。。
[root@iZbp16yavnv9o65fcw4vr0Z jd]# rm -rf ~/.ssh/id_rsa*
[root@iZbp16yavnv9o65fcw4vr0Z jd]# wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa
--2021-02-27 10:27:25--  https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa
Resolving gitee.com (gitee.com)... 212.64.62.183
Connecting to gitee.com (gitee.com)|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘/root/.ssh/id_rsa’

/root/.ssh/id_rsa               [ <=>                                     ]   1.79K  --.-KB/s    in 0s      

2021-02-27 10:27:25 (16.3 MB/s) - ‘/root/.ssh/id_rsa’ saved [1831]

[root@iZbp16yavnv9o65fcw4vr0Z jd]# chmod 600 ~/.ssh/id_rsa
[root@iZbp16yavnv9o65fcw4vr0Z jd]# ssh-keygen -y -f ~/.ssh/id_rsa >~/.ssh/id_rsa.pub
[root@iZbp16yavnv9o65fcw4vr0Z jd]# bash /opt/jd/manual-update.sh

--------------------------------------------------------------

系统时间：2021-02-27 10:27:39

JS脚本目录：/opt/jd/scripts

--------------------------------------------------------------

Fetching origin
Username for 'https://gitee.com':

**Comment by yang137312** [comment]
其实运行时可以运行的，就是更新不了。

**Comment by SuperManito** [comment]
> 其实运行时可以运行的，就是更新不了。
试试这个，如果还有问题那就是你网络问题

   ssh-keyscan gitee.com > /root/.ssh/known_hosts

**Comment by yang137312** [comment]
> > 其实运行时可以运行的，就是更新不了。
> 
> 试试这个，如果还有问题那就是你网络问题
> 
> ```
> ssh-keyscan gitee.com > /root/.ssh/known_hosts
> ```

好的，我试试

**Comment by yang137312** [comment]
> > 其实运行时可以运行的，就是更新不了。
> 
> 试试这个，如果还有问题那就是你网络问题
> 
> ```
> ssh-keyscan gitee.com > /root/.ssh/known_hosts
> ```

还是不行，我重新装一遍吧还是。
