### ISSUE TITLE
好多脚本报API请求失败，请检查网络重试

### ISSUE THREAD

**Issue by atgfss** [SuperManito/JD-FreeFuck#94]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [x] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：centos 7.0

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：好多脚本报API请求失败，请检查网络重试。例如：东东农场，金融养猪，好像只有签到有用，其他大多都报这个错

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：🔔金融养猪, 开始!

====================共有1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021-2-26 17:25:25=====================

"The "listener" argument must be of type Function. Received type object"
金融养猪 API请求失败，请检查网路重试

开始【京东账号1】xxxx

"The "listener" argument must be of type Function. Received type object"
金融养猪 API请求失败，请检查网路重试

🔔金融养猪, 结束! 🕛 0.119 秒

=====================
另外自己检查了代码，看到请求的地址像是不存在，报404，是不是这些功能不能用了？但是我看https://gitee.com/lxk0301/jd_docker/issues 大神的issues里反馈的信息里有人好像是可以用的，不知道是啥原因

**Comment by SuperManito** [comment]
![image](https://user-images.githubusercontent.com/68613938/109289302-fbb3f300-7860-11eb-8b60-0b9b845b0256.png)
能用的，前提是IPv4
