### ISSUE TITLE
无法读取远程仓库,js脚本更新失败.

### ISSUE THREAD

**Issue by X-Firefly** [SuperManito/JD-FreeFuck#95]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [ x ] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x ] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x ] 是
- [ ] 否

## 2. 安装平台

- [x ] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x ] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：无法读取远程仓库。请确认您有正确的访问权限并且仓库存在。
js脚本更新失败，请检查原因或再次运行git_pull.sh...

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：2021-02-26 23:02:37 (35.0 MB/s) - “/opt/jd/sample/computer.list.sample” 已保存 [995]

--------------------------------------------------------------

系统时间：2021-02-26 23:02:37

JS脚本目录：/opt/jd/scripts

--------------------------------------------------------------

正克隆到 '/opt/jd/scripts'...
Warning: Permanently added 'gitee.com,180.97.125.228' (ECDSA) to the list of known hosts.
git@gitee.com: Permission denied (publickey).
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。

js脚本更新失败，请检查原因或再次运行git_pull.sh...

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN panel No description
npm WARN panel No repository field.
npm WARN panel No license field.

added 89 packages from 92 contributors and audited 89 packages in 5.15s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@4.5.5
added 201 packages from 196 contributors in 30.014s

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__

                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/

                        -------------

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /opt/jd/panel/server.js in fork_mode (1 instance)
[PM2] Done.
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ server    │ default     │ N/A     │ fork    │ 5741     │ 0s     │ 0    │ online    │ 0%       │ 28.3mb   │ root     │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
/opt/jd/jd.sh: 第 11 行： cd: /opt/jd/scripts: 没有那个文件或目录
/opt/jd/jd.sh: 第 163 行： cd: /opt/jd/scripts: 没有那个文件或目录
/opt/jd/jd.sh: 第 11 行： cd: /opt/jd/scripts: 没有那个文件或目录
/opt/jd/jd.sh: 第 163 行： cd: /opt/jd/scripts: 没有那个文件或目录
 +------- 已 启 用 控 制 面 板 功 能 -------+ 
 |                                          | 
 | 本地访问：http://127.0.0.1:5678          | 
 |                                          | 
 | 外部访问：http://内部或外部IP地址:5678   | 
 |                                          | 
 | 初始用户名：admin，初始密码：adminadmin  | 
 |                                          | 
 +------------------------------------------+

**Comment by SuperManito** [comment]
执行下面的命令尝试：

    rm -rf ~/.ssh/id_rsa*
    wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keygen -y -f ~/.ssh/id_rsa >~/.ssh/id_rsa.pub
    bash /opt/jd/manual-update.sh

**Comment by X-Firefly** [comment]
> 執行下面的命令嘗試：
> 
> ```
> rm -rf ~/.ssh/id_rsa*
> wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa
> chmod 600 ~/.ssh/id_rsa
> ssh-keygen -y -f ~/.ssh/id_rsa >~/.ssh/id_rsa.pub
> bash /opt/jd/manual-update.sh
> ```

可以拉取了，谢谢。

**Comment by SuperManito** [comment]
不客气

**Comment by sunstear2015** [comment]
wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa d 的时候提示404，昨天这个命令还能执行的，今天不行了。

**Comment by sunstear2015** [comment]
[root@bogon jd]# wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa
--2021-03-02 10:34:44--  https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa
Resolving gitee.com (gitee.com)... 212.64.62.183
Connecting to gitee.com (gitee.com)|212.64.62.183|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-02 10:34:44 ERROR 404: Not Found.
帮忙看下大神，是不是新版本这个密匙删掉了。

**Comment by SuperManito** [comment]
> wget https://gitee.com/SuperManito/JD-FreeFuck/raw/main/source/id_rsa -O ~/.ssh/id_rsa d 的时候提示404，昨天这个命令还能执行的，今天不行了。

是啊，我删了，你不看我项目通知吗？？？？？？
