### ISSUE TITLE
git@gitee.com: Permission denied (publickey). fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by wshok** [SuperManito/JD-FreeFuck#96]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [ ] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [x] PC
- [ ] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：
--------------------------------------------------------------

系统时间：2021-02-27 10:31:58

JS脚本目录：/home/vagrant/workspace/jd/JD-FreeFuck-main/source/scripts

--------------------------------------------------------------

Cloning into '/home/vagrant/workspace/jd/JD-FreeFuck-main/source/scripts'...
git@gitee.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

js脚本更新失败，请检查原因或再次运行git_pull.sh...

**Comment by SuperManito** [comment]
# 95
