### ISSUE TITLE
docker 的log,有没有意义？

### ISSUE THREAD

**Issue by hellovirus** [SuperManito/JD-FreeFuck#97]
docker 版 的git_pull.log 结尾

************************************
shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...

js脚本更新完成...

cat: /jd/scripts/docker/crontab_list.sh: No such file or directory
cat: package.json: No such file or directory
/usr/local/bin/git_pull: line 262: [: -eq: unary operator expected

*************************************************

为什么shell脚本更新失败，
另外这个目录和文件都没有呀

**Comment by hellovirus** [comment]
我安装的是docker版，按照这个部署后，
可以正常打开，修改好cookie后，再重启容器，就会进入无限重启中，
这是怎么回事。

小白，谢谢老大

**Comment by SuperManito** [comment]
已发布新版本
