### ISSUE TITLE
如何取得permission 

### ISSUE THREAD

**Issue by charliesxia** [SuperManito/JD-FreeFuck#98]
Access deined: You do not have permission to pull the repository
fatal: Could not read from remote repository.
拉取脚本失败。。咋整呢
谢谢

## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [ ] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [ ] x86-64 / AMD64
- [x] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [x] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [ ] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [x] 部署问题
- [ ] 使用问题

### (1) 具体问题
A：

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：

**Comment by SuperManito** [comment]
#95
