### ISSUE TITLE
manual更新定时任务不运行

### ISSUE THREAD

**Issue by Kafeyun** [SuperManito/JD-FreeFuck#99]
## 1. 关于您要提交的问题
Q：是否阅读了《特别声明》并已接受此声明

- [x] 是
- [ ] 否

Q：是否仔细阅读了《部署前须知》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《常见问题与帮助》

- [x] 是
- [ ] 否

Q：是否仔细阅读了《项目须知》

- [x] 是
- [ ] 否

## 2. 安装平台

- [] PC
- [x] VPS
- [ ] 软路由
- [ ] NAS
- [ ] Other

## 3. 安装平台架构

- [x] x86-64 / AMD64
- [ ] arm64 / aarch64
- [ ] Other

## 4. 安装环境

- [ ] Ubuntu
- [ ] Debian
- [ ] CentOS
- [ ] Fedora
- [x] Docker
- [ ] Other

## 5. 安装环境具体版本号
A：

## 6. 问题类型

- [ ] 部署问题
- [x] 使用问题

### (1) 具体问题
A：manual-update 没有自动运行，查看log文件夹也没有看到过日志输出

### (2) 详细的系统日志
_注:部署报错请将终端输出的内容（从开始执行脚本到结束）完整粘贴至此处！_

A：无日志，粘贴crontab
55 * * * *  bash manual-update.sh >> log/manual-update.log 2>&1

**Comment by yang137312** [comment]
我昨天也是这个问题，我卸载再装了一遍就好了

**Comment by qaz88q11** [comment]
老竭力和shuye72的一件部署太香了 比这个垃圾强

**Comment by SuperManito** [comment]
已发布全新docker版本
